STM32F103_IMU6050App: basic/array.h File Reference
array.h File Reference
Classes
struct array_t
ARRAY.h.
struct param_t
parameter struct
struct cmd_t
a command structus that would be received on the uart
Functions
int mem_indexOf (void *buf, size_t len, int val, unsigned int fromIndex)
give the first index of a specific character in the array buf
int mem_lastindexOf (void *buf, size_t len, int val, unsigned int fromIndex)
give the last index of a specific character in the array buf
int mem_find_aslist (void *buf, size_t len, int val, uint8_t *ptr_list)
give the first index of a specific values array in the array buf
int mem_find_asArray (void *buf, size_t len, int val, array_t *ptr_list)
give the last index of a specific values array in the array buf
int param_split (array_t parameter, param_t *param)
split the parameter string to parameter-value pairs
int cmd_split (void *buf, size_t len, int val, cmd_t *cmd)
split the command string from the whole message
Function Documentation
cmd_split()
int cmd_split (void * buf, size_t len, int val, cmd_t * cmd)
split the command string from the whole message
split the command string from the whole message
split the command string from the whole message and builds up the different parts of the command struct i.e. the command , parameters , and the values as separated pointers to these strings.
Parameters
buf a pointer to the whole received message on the uart
len defines the length of the received message on the uart
val check the searched key to split the message based on it
cmd a pointer to a command struct that builds the different part of the command
Returns
int
a parameter string length
Definition at line 174 of file array.c.
{
 unsigned int start=0,end=0;
 cmd->param_len=mem_find_asArray(buf,len,val,cmd->parameters);
 cmd->msg.ptr=0;
 cmd->msg.len=0;
 if(cmd->param_len>0)
 {
    start= cmd->parameters[cmd->param_len-1].ptr- (uint8_t*)buf;
    start+= cmd->parameters[cmd->param_len-1].len+1;
 }
 end=mem_indexOf(buf,len,' ',start);
 cmd->msg.len=end-start; //len-start;
 cmd->msg.ptr=(uint8_t*)(buf+start);
 return cmd->param_len;
}
References array_t::len, mem_find_asArray(), mem_indexOf(), cmd_t::msg, cmd_t::param_len, cmd_t::parameters, and array_t::ptr.
mem_find_asArray()
int mem_find_asArray (void * buf, size_t len, int val, array_t * ptr_list)
give the last index of a specific values array in the array buf
Parameters
buf the buffer to look for
len the length of the data buffer
val the key value to check for it
ptr_list
Returns
int
Definition at line 132 of file array.c.
{
   int fromindex=0,previndex=0;
   uint8_t i=0,start=0,end=0;
   while(fromindex!=-1)
   {
      fromindex=mem_indexOf(buf,len,val,fromindex);
      if(fromindex!=-1)
      {
        if(i>0) ptr_list[i-1].len=fromindex-previndex;
         ptr_list[i].ptr=(uint8_t *)(buf+fromindex);//ptr_list[i]=(uint8_t*)(buf+fromindex); //*((uint8_t *)(ptr_list+i))= fromindex;
         previndex=fromindex;
         fromindex++;
         i++;
      }
   }
   if(i>0)
   {
     start=(uint8_t*)ptr_list[i-1].ptr-(uint8_t*)buf;
     end=mem_indexOf(buf,len,' ',start);
     end=mem_indexOf(buf,len,' ',end+1);
     len=end-start;
     ptr_list[i-1].len=len;
   }
   return i;
}
References array_t::len, mem_indexOf(), and array_t::ptr.
Referenced by cmd_split().
mem_find_aslist()
int mem_find_aslist (void * buf, size_t len, int val, uint8_t * ptr_list)
give the first index of a specific values array in the array buf
give the first index of a specific values array in the array buf
Parameters
buf the buffer to look for
len the length of the data buffer
val the key value to check for it
ptr_list indecies list for elements that match the key value
Returns
int the length of the
Return values
the length of the
Definition at line 106 of file array.c.
{
   int fromindex=0;
   uint8_t i=0;
   while(fromindex!=-1)
   {
      fromindex=mem_indexOf(buf,len,val,fromindex);
      if(fromindex!=-1)
      {
         ptr_list[i]=fromindex;
         fromindex++;
         i++;
      }
   }
    return i;
}
References mem_indexOf().
mem_indexOf()
int mem_indexOf (void * buf, size_t len, int val, unsigned int fromIndex)
give the first index of a specific character in the array buf
give the first index of a specific character in the array buf
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
get the first occurance of a key value in a buffer
get the first occurance of a key value in a buffer starting from from a specific index
Parameters
buf the buffer to look for
len the length of the data buffer
val the key value to check for it
fromIndex the index to start the search from
Returns
int
Return values
-1 not found the key value within the buffer
others the index of the first occurance
Definition at line 58 of file array.c.
{
    if (fromIndex >= len)
      return -1;
//  const char* temp =(const char*) memchr(buf + fromIndex,val,len);
    uint8_t* temp =(uint8_t*) memchr(buf + fromIndex,val,len);
    if (temp == NULL)
      return -1;
    return temp - (uint8_t*)buf;
}
Referenced by cmd_split(), mem_find_asArray(), mem_find_aslist(), and param_split().
mem_lastindexOf()
int mem_lastindexOf (void * buf, size_t len, int val, unsigned int fromIndex)
give the last index of a specific character in the array buf
give the last index of a specific character in the array buf
get the last occurance of a key value in a buffer starting from from a specific index
Parameters
buf the buffer to look for
len the length of the data buffer
val the key value to check for it
fromIndex the index to start the search from
Returns
int
Return values
-1 not found the key value within the buffer
others the index of the first occurance
Definition at line 85 of file array.c.
{
    if (fromIndex >= len)
      return -1;
    uint8_t* temp =(uint8_t*) memchr(buf + fromIndex,val,len);
    if (temp == NULL)
      return -1;
    return temp - (uint8_t*)buf;
}
param_split()
int param_split (array_t parameter, param_t * ptr_param)
split the parameter string to parameter-value pairs
split the parameter string to parameter-value pairs
splits the parameter string to parameter-value pairs
Parameters
parameter it is the parameter-value string array
ptr_param it a struct the spilt the paratmeter string to param-value pairs
Returns
int
Definition at line 202 of file array.c.
{
 int par_start=0,par_end=0,data_end=0;
 uint8_t par_len=0,data_len=0;
 par_start=mem_indexOf(parameter.ptr,parameter.len,'-',0);
 par_end=  mem_indexOf(parameter.ptr,parameter.len,' ',0);
 if(par_start !=-1 && par_end!=-1)
 {
    par_len=par_end-par_start;
    data_len=parameter.len-par_end-1;
    ptr_param->param=(uint8_t*)(parameter.ptr+par_start);
    ptr_param->param_len=par_len;
    ptr_param->data=(uint8_t*)(parameter.ptr+par_end+1);
    ptr_param->data_len=data_len;
 }
 return data_len;
}
References param_t::data, param_t::data_len, array_t::len, mem_indexOf(), param_t::param, param_t::param_len, and array_t::ptr.