STM32F103_IMU6050App: basic/crc.c File Reference
crc.c File Reference
#include "init.h"
Functions
static void crc32a_calc_byte (uint8_t val, uint32_t *crc)
crc.c this source code for crc implementation
static void crc32b_calc_byte (uint8_t val, uint32_t *crc)
implements the polynom shifting and xor
uint32_t crc32b_calc (uint8_t *msg, size_t len)
calculate the crc32 as a 32-bit for an array of bytes
uint32_t crc32a_calc (uint8_t *msg, size_t len)
calculate the crc32 as a 32-bit for an array of bytes
uint32_t crc32_calc_as (uint8_t *msg, size_t len, uint8_t type)
calculate the crc 32 as reversed or normal one for a given message based on a type given
uint32_t crc32_calc (uint8_t *msg, size_t len)
calculate the crc32 for an array of bytes the normal
Function Documentation
crc32_calc()
uint32_t crc32_calc (uint8_t * msg, size_t len)
calculate the crc32 for an array of bytes the normal
Definition at line 150 of file crc.c.
{
  return crc32b_calc(msg,len);
}
References crc32b_calc().
crc32_calc_as()
uint32_t crc32_calc_as (uint8_t * msg, size_t len, uint8_t type)
calculate the crc 32 as reversed or normal one for a given message based on a type given
calculate the crc32 for an array of bytes the normal or reversed
Parameters
msg the message to calculate the crc32
len the message length
type type of crc to calculate
Returns
uint32_t
Definition at line 140 of file crc.c.
{
  switch (type)
  {
    case 0: return crc32a_calc(msg,len); // normal crc
    case 1: return crc32b_calc(msg,len); // reversed crc
  }
    return crc32b_calc(msg,len);
}
References crc32a_calc(), and crc32b_calc().
crc32a_calc()
uint32_t crc32a_calc (uint8_t * msg, size_t len)
calculate the crc32 as a 32-bit for an array of bytes
calculate the crc32 for an array of bytes
it uses a reversed crc32 polynominal algorithm that allows to calculate the crc32 value starting form the least significant bit in the lowest byte in the array
Parameters
msg an array of bytes as the message to calculate the crc32
len length of the message
Returns
32bit crc
Definition at line 119 of file crc.c.
{
  uint32_t crc=0xffffffff;
  uint8_t val=0;
  for(size_t i=0;i<len;i++)
  {
      val=msg[i];
    crc32a_calc_byte(val,(uint32_t*)&crc);
  }
  crc=reverse_dword(crc);
    return ~crc;
}
References crc32a_calc_byte(), and reverse_dword().
Referenced by crc32_calc_as().
crc32a_calc_byte()
void crc32a_calc_byte (uint8_t val, uint32_t * crc) static
crc.c this source code for crc implementation
implements the polynom shifting and xor
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
implements the polynom shifting and xor due to one byte and for each bit of its bits it uses the reversed Generatorpolynom= 0xEDB88320
Parameters
val a byte value from the message
crc a 32bit pointer to allow nested call for
Returns
nothing
Definition at line 94 of file crc.c.
{
  int8_t i=0;
  uint32_t polynom = 0x04C11DB7;// Generatorpolynom
  for (i=0; i<8; i++)
  {
    if (((*crc>>31)&1) != (val&1))
        *crc = (*crc<<1) ^polynom;
    else
        (*crc) = *crc <<1;
    val >>= 1;
  }
}
Referenced by crc32a_calc().
crc32b_calc()
uint32_t crc32b_calc (uint8_t * msg, size_t len)
calculate the crc32 as a 32-bit for an array of bytes
calculate the reversed crc32 for an array of bytes
it uses a reversed crc32 polynominal algorithm that allows to calculate the crc32 value starting form the least significant bit in the lowest byte in the array
Parameters
msg an array of bytes as the message to calculate the crc32
len length of the message
Returns
32bit crc
Definition at line 71 of file crc.c.
{
  uint32_t crc=0xFFFFFFFF;
  uint8_t val=0;
  for(size_t i=0;i<len;i++)
  {
    val=msg[i];
    crc32b_calc_byte(val,(uint32_t*)&crc);
  }
    return ~crc;
}
References crc32b_calc_byte().
Referenced by crc32_calc(), and crc32_calc_as().
crc32b_calc_byte()
void crc32b_calc_byte (uint8_t val, uint32_t * crc) static
implements the polynom shifting and xor
implements the polynom shifting and xor due to one byte and for each bit of its bits it uses the reversed Generatorpolynom= 0xEDB88320
Parameters
val a byte value from the message
crc a 32bit pointer to allow nested call for
Returns
nothing
Definition at line 46 of file crc.c.
{
  uint8_t i=0;
  uint32_t polynom = 0xEDB88320;// Generatorpolynom
  for (i=0; i<8; i++)
  {
    if ((*crc&1) != (val&1))
        *crc = (*crc>>1) ^polynom;
    else
        (*crc) = *crc >>1;
    val >>= 1;
  }
}
Referenced by crc32b_calc().