STM32F103_IMU6050App: basic/gpio.h File Reference
gpio.h File Reference
Classes
struct gpio_t
struct reg_t
Enumerations
enum GPIO_MODE {
GPIO_MODE_ANALOG =0x00 , GPIO_MODE_OUT_PP_10MHZ =0x01 , GPIO_MODE_OUT_PP_2MHZ =0x02 , GPIO_MODE_OUT_PP_50MHZ =0x03 ,
GPIO_MODE_IN_FLOATING =0x04 , GPIO_MODE_OUT_OD_10MHZ =0x05 , GPIO_MODE_OUT_OD_2MHZ =0x06 , GPIO_MODE_OUT_OD_50MHZ =0x07 ,
GPIO_MODE_IN_PUPD =0x08 , GPIO_MODE_AF_PP_10MHZ =0x09 , GPIO_MODE_AF_PP_2MHZ =0x0A , GPIO_MODE_AF_PP_50MHZ =0x0B ,
GPIO_MODE_RESEVED =0x0C , GPIO_MODE_AF_OD_10MHZ =0x0D , GPIO_MODE_AF_OD_2MHZ =0x0E , GPIO_MODE_AF_OD_50MHZ =0x0F
}
gpio.h
Functions
void reg_sbits (__IO uint32_t *reg, uint32_t bits)
gpio.c
void reg_cbits (__IO uint32_t *reg, uint32_t bits)
void gpio_init (GPIO_TypeDef *port, uint16_t pin, GPIOMode_TypeDef mode, GPIOSpeed_TypeDef speed)
void gpio_pinmode (gpio_t pio, GPIOMode_TypeDef mode, GPIOSpeed_TypeDef speed)
void gpio_pin_mode (gpio_t pio, uint8_t mode)
void gpio_set (gpio_t pio)
void gpio_clear (gpio_t pio)
void gpio_toggle (gpio_t pio)
void gpio_in_pullup (gpio_t pio)
void gpio_in_pulldown (gpio_t pio)
void gpio_in_float (gpio_t pio)
uint8_t gpio_get (gpio_t pio)
uint8_t gpio_get_out (gpio_t pio)
Enumeration Type Documentation
GPIO_MODE
enum GPIO_MODE
gpio.h
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Enumerator
GPIO_MODE_ANALOG
GPIO_MODE_OUT_PP_10MHZ
GPIO_MODE_OUT_PP_2MHZ
GPIO_MODE_OUT_PP_50MHZ
GPIO_MODE_IN_FLOATING
GPIO_MODE_OUT_OD_10MHZ
GPIO_MODE_OUT_OD_2MHZ
GPIO_MODE_OUT_OD_50MHZ
GPIO_MODE_IN_PUPD
GPIO_MODE_AF_PP_10MHZ
GPIO_MODE_AF_PP_2MHZ
GPIO_MODE_AF_PP_50MHZ
GPIO_MODE_RESEVED
GPIO_MODE_AF_OD_10MHZ
GPIO_MODE_AF_OD_2MHZ
GPIO_MODE_AF_OD_50MHZ
Definition at line 24 of file gpio.h.
              {
    GPIO_MODE_ANALOG=0x00,
    GPIO_MODE_OUT_PP_10MHZ=0x01,
    GPIO_MODE_OUT_PP_2MHZ=0x02,
    GPIO_MODE_OUT_PP_50MHZ=0x03,
    GPIO_MODE_IN_FLOATING=0x04,
    GPIO_MODE_OUT_OD_10MHZ=0x05,
    GPIO_MODE_OUT_OD_2MHZ=0x06,
    GPIO_MODE_OUT_OD_50MHZ=0x07,
    GPIO_MODE_IN_PUPD=0x08,
    GPIO_MODE_AF_PP_10MHZ=0x09,
    GPIO_MODE_AF_PP_2MHZ=0x0A,
    GPIO_MODE_AF_PP_50MHZ=0x0B,
    GPIO_MODE_RESEVED=0x0C,
    GPIO_MODE_AF_OD_10MHZ=0x0D,
    GPIO_MODE_AF_OD_2MHZ=0x0E,
    GPIO_MODE_AF_OD_50MHZ=0x0F,
};
Function Documentation
gpio_clear()
void gpio_clear (gpio_t pio)
Definition at line 104 of file gpio.c.
{
  pio.port->BRR|=(uint16_t)(1<<pio.pin);
}
References gpio_t::pin, and gpio_t::port.
Referenced by blink_init(), keypad_read(), lcd_en_clear(), lcd_port_write_byte(), lcd_rs_clear(), pilot_write(), and rly_write().
gpio_get()
uint8_t gpio_get (gpio_t pio)
Definition at line 140 of file gpio.c.
{
  //if((pio.port->IDR & (uint32_t)(1<<pio.pin)))
  if(bit_is_set(pio.port->IDR,pio.pin))
   return 1;
  return 0;
}
References bit_is_set, gpio_t::pin, and gpio_t::port.
Referenced by keypad_port_get_input_data(), and lcd_port_read_byte().
gpio_get_out()
uint8_t gpio_get_out (gpio_t pio)
Definition at line 148 of file gpio.c.
{
 return (uint8_t) (pio.port->ODR & (uint32_t)(1<<pio.pin));
}
References gpio_t::pin, and gpio_t::port.
gpio_in_float()
void gpio_in_float (gpio_t pio)
Definition at line 135 of file gpio.c.
{
  gpio_pin_mode(pio,GPIO_MODE_IN_FLOATING);
}
References GPIO_MODE_IN_FLOATING, and gpio_pin_mode().
gpio_in_pulldown()
void gpio_in_pulldown (gpio_t pio)
Definition at line 129 of file gpio.c.
{
  gpio_pin_mode(pio,GPIO_MODE_IN_PUPD);
  pio.port->BSRR &=~((uint32_t)1<<pio.pin);
}
References GPIO_MODE_IN_PUPD, gpio_pin_mode(), gpio_t::pin, and gpio_t::port.
gpio_in_pullup()
void gpio_in_pullup (gpio_t pio)
Definition at line 123 of file gpio.c.
{
  gpio_pin_mode(pio,GPIO_MODE_IN_PUPD);
  pio.port->BSRR|=((uint32_t)1<<pio.pin);
}
References GPIO_MODE_IN_PUPD, gpio_pin_mode(), gpio_t::pin, and gpio_t::port.
Referenced by keypad_port_input_pullup(), lcd_en_pinmode_in(), lcd_port_pinmode_in(), and lcd_rs_pinmode_in().
gpio_init()
void gpio_init (GPIO_TypeDef * port, uint16_t pin, GPIOMode_TypeDef mode, GPIOSpeed_TypeDef speed)
Definition at line 48 of file gpio.c.
{
    GPIO_InitTypeDef gpioinit;
    GPIO_StructInit((GPIO_InitTypeDef *)&gpioinit);
    gpioinit.GPIO_Mode=mode;
    gpioinit.GPIO_Speed=speed;
    gpioinit.GPIO_Pin=(uint32_t)(1<<pin);
    GPIO_Init(port,(GPIO_InitTypeDef *)&gpioinit);
}
Referenced by blink_init().
gpio_pin_mode()
void gpio_pin_mode (gpio_t pio, uint8_t mode)
Definition at line 68 of file gpio.c.
{
    uint32_t temp=0,a=0;
    uint16_t shift=0;
  shift=(pio.pin<8)?pio.pin:pio.pin-8;
  shift<<=2;
  temp= (uint32_t)(mode & 0x0f);
  if(pio.pin<8)
  {
    a = pio.port->CRL & ~(0x0f<<shift);
    a|= temp<<shift;
    pio.port->CRL=a;
  }
  else
  {
    a =pio.port->CRH & ~(0x0f<<shift);
    a|=temp<<shift;
    pio.port->CRH=a;
  }
}
References gpio_t::pin, and gpio_t::port.
Referenced by blink_init(), disable_buffer(), gpio_in_float(), gpio_in_pulldown(), gpio_in_pullup(), i2c_init(), keypad_init(), keypad_read(), lcd_en_pinmode_out(), lcd_port_pinmode_out(), lcd_rs_pinmode_out(), pilot_init(), rly_init(), and USART1_init().
gpio_pinmode()
void gpio_pinmode (gpio_t pio, GPIOMode_TypeDef mode, GPIOSpeed_TypeDef speed)
Definition at line 58 of file gpio.c.
{
    GPIO_InitTypeDef gpioinit;
    GPIO_StructInit((GPIO_InitTypeDef *)&gpioinit);
    gpioinit.GPIO_Mode=mode;
    gpioinit.GPIO_Speed=speed;
    gpioinit.GPIO_Pin=(uint32_t)(1<<io.pin);
    GPIO_Init(io.port,(GPIO_InitTypeDef *)&gpioinit);
}
References gpio_t::pin, and gpio_t::port.
Referenced by blink_init().
gpio_set()
void gpio_set (gpio_t pio)
Definition at line 97 of file gpio.c.
{
    pio.port->BSRR|=(uint16_t)(1<<pio.pin);
    //sbit(pio.port->BSRR,pio.pin);
}
References gpio_t::pin, and gpio_t::port.
Referenced by disable_buffer(), keypad_init(), keypad_read(), lcd_en_set(), lcd_port_write_byte(), lcd_rs_set(), pilot_write(), and rly_write().
gpio_toggle()
void gpio_toggle (gpio_t pio)
Definition at line 109 of file gpio.c.
{
// uint8_t val=(pio.port->ODR)&((uint16_t)(1<<pio.pin));
 if(bit_is_set(pio.port->ODR,pio.pin))
  sbit(pio.port->BRR,pio.pin);
 else
  sbit(pio.port->BSRR,pio.pin);
}
References bit_is_set, gpio_t::pin, gpio_t::port, and sbit.
Referenced by rtc_task().
reg_cbits()
void reg_cbits (__IO uint32_t * reg, uint32_t bits)
Definition at line 34 of file gpio.c.
{
 if(reg!=NULL)
  {
    *reg&=~bits;
  }
}
Referenced by i2c_init().
reg_sbits()
void reg_sbits (__IO uint32_t * reg, uint32_t bits)
gpio.c
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Definition at line 26 of file gpio.c.
{
if(reg!=NULL)
 {
        *reg|=bits;
 }
}
Referenced by i2c_init().