STM32F103_IMU6050App: TM_MPU6050_Functions
TM_MPU6050_Functions
Library Functions.
Functions
uint8_t mpu6050_init (MPU6050_t *mpu, MPU6050_Accel_Range_t Accel_Range, MPU6050_Gyro_Range_t Gyro_Range)
Initializes MPU6050 and I2C peripheral.
uint8_t mpu6050_reset (MPU6050_t *mpu)
uint8_t mpu6050_read_Accelerometer (MPU6050_t *mpu)
Reads accelerometer data from sensor.
uint8_t mpu6050_read_Gyroscope (MPU6050_t *mpu)
Reads gyroscope data from sensor.
uint8_t mpu6050_read_Temperature (MPU6050_t *mpu)
Reads temperature data from sensor.
uint8_t mpu6050_read_All (MPU6050_t *mpu)
Reads accelerometer, gyroscope and temperature data from sensor.
uint8_t mpu6050_setGyroRange (MPU6050_t *mpu, MPU6050_Gyro_Range_t Gyro_range)
Sets gyroscope sensitivity.
uint8_t mpu6050_setAccelRange (MPU6050_t *mpu, MPU6050_Accel_Range_t Accel_Range)
Sets accelerometer sensitivity.
uint8_t mpu6050_setDataRate (MPU6050_t *mpu, uint8_t rate)
Sets output data rate.
uint8_t mpu6050_EnableInterrupts (MPU6050_t *mpu)
uint8_t mpu6050_DisableInterrupts (MPU6050_t *mpu)
Disables interrupts.
uint8_t mpu6050_read_Interrupts (MPU6050_t *mpu, MPU6050_Interrupt_t *InterruptsStruct)
Reads and clears interrupts.
uint8_t mpu6050_setClock (MPU6050_t *mpu, MPU6050_Clock_Select_t clock_select)
uint8_t mpu6050_setSampleRateDivisor (MPU6050_t *mpu, uint8_t SampleRateDiv)
uint8_t mpu6050_setCycleRate (MPU6050_t *mpu, MPU6050_Cycle_Rate_t rate)
uint8_t mpu6050_enableSleep (MPU6050_t *mpu, uint8_t enable)
uint8_t mpu6050_enableCycle (MPU6050_t *mpu, uint8_t enable)
uint8_t mpu6050_setI2CBypass (MPU6050_t *mpu, uint8_t bypass)
uint8_t mpu6050_set_lpf (MPU6050_t *mpu, MPU6050_LPF_bandwidth_t bandwidth)
uint8_t mpu6050_set_hpf (MPU6050_t *mpu, MPU6050_Accel_HPF_t bandwidth)
uint8_t mpu6050_setInterruptPinPolarity (MPU6050_t *mpu, uint8_t active_low)
uint8_t mpu6050_setInterruptPinLatch (MPU6050_t *mpu, uint8_t held)
uint8_t mpu6050_setFsyncSampleOutput (MPU6050_t *mpu, MPU6050_Fsync_out_t fsync_output)
uint8_t mpu6050_setMotionInterrupt (MPU6050_t *mpu, uint8_t active)
uint8_t mpu6050_setMotionDetectionThreshold (MPU6050_t *mpu, uint8_t thr)
uint8_t mpu6050_setMotionDetectionDuration (MPU6050_t *mpu, uint8_t dur)
uint8_t mpu6050_setGyroStandby (MPU6050_t *mpu, uint8_t xAxisStandby, uint8_t yAxisStandby, uint8_t zAxisStandby)
uint8_t mpu6050_setAccelerometerStandby (MPU6050_t *mpu, uint8_t xAxisStandby, uint8_t yAxisStandby, uint8_t zAxisStandby)
uint8_t mpu6050_setTemperatureStandby (MPU6050_t *mpu, uint8_t enable)
uint8_t mpu6050_read_reg (MPU6050_t *mpu, uint8_t reg_address, uint8_t *data)
uint8_t mpu6050_getClock (MPU6050_t *mpu, uint8_t *data)
uint8_t mpu6050_getSampleRateDivisor (MPU6050_t *mpu, uint8_t *data)
uint8_t mpu6050_getCycleRate (MPU6050_t *mpu, uint8_t *data)
uint8_t mpu6050_getFsyncSampleOutput (MPU6050_t *mpu, uint8_t *data)
uint8_t mpu6050_get_lpf (MPU6050_t *mpu, uint8_t *data)
uint8_t mpu6050_get_hpf (MPU6050_t *mpu, uint8_t *data)
uint8_t mpu6050_getAccelRange (MPU6050_t *mpu, uint8_t *data)
uint8_t mpu6050_getGyroRange (MPU6050_t *mpu, uint8_t *data)
uint8_t mpu6050_getMotionInterruptStatus (MPU6050_t *mpu, uint8_t *status)
void mpu6050_clear_All (MPU6050_t *mpu)
void mpu6050_clear_Accelometer (MPU6050_t *mpu)
void mpu6050_clear_Gyroscope (MPU6050_t *mpu)
void mpu6050_clear_Temperature (MPU6050_t *mpu)
void mpu6050_uart_print (USART_TypeDef *uart, MPU6050_t *mpu)
void mpu6050_uart_print_Accelometer (USART_TypeDef *uart, MPU6050_t *mpu)
void mpu6050_uart_print_Gyroscope (USART_TypeDef *uart, MPU6050_t *mpu)
void mpu6050_uart_print_Temperature (USART_TypeDef *uart, MPU6050_t *mpu)
void mpu6050_uart_print_raw_Accelometer (USART_TypeDef *uart, MPU6050_t *mpu)
void mpu6050_uart_print_raw_Gyroscope (USART_TypeDef *uart, MPU6050_t *mpu)
void mpu6050_uart_print_raw_Temperature (USART_TypeDef *uart, MPU6050_t *mpu)
void mpu6050_uart_print_raw_Data (USART_TypeDef *uart, MPU6050_t *mpu)
void mpu6050_uart_print_raw_Array (USART_TypeDef *uart, MPU6050_t *mpu)
Variables
uint8_t MPU6050_Interrupt_t::Status
uint8_t MPU6050_Interrupt_t::DataReady:1
Data ready interrupt.
uint8_t MPU6050_Interrupt_t::reserved2:2
Reserved bits.
uint8_t MPU6050_Interrupt_t::Master:1
Master interrupt.
uint8_t MPU6050_Interrupt_t::FifoOverflow:1
FIFO overflow interrupt.
uint8_t MPU6050_Interrupt_t::reserved1:1
Reserved bit.
uint8_t MPU6050_Interrupt_t::MotionDetection:1
Motion detected interrupt.
uint8_t MPU6050_Interrupt_t::reserved0:1
Reserved bit.
struct {
uint8_t MPU6050_Interrupt_t::DataReady:1
Data ready interrupt.
uint8_t MPU6050_Interrupt_t::reserved2:2
Reserved bits.
uint8_t MPU6050_Interrupt_t::Master:1
Master interrupt.
uint8_t MPU6050_Interrupt_t::FifoOverflow:1
FIFO overflow interrupt.
uint8_t MPU6050_Interrupt_t::reserved1:1
Reserved bit.
uint8_t MPU6050_Interrupt_t::MotionDetection:1
Motion detected interrupt.
uint8_t MPU6050_Interrupt_t::reserved0:1
Reserved bit.
} MPU6050_Interrupt_t::F
uint8_t mpu6050_raw_t::Array [MPU6050_RAW_ALL_LEN]
uint8_t mpu6050_raw_t::accel_x_high
uint8_t mpu6050_raw_t::accel_x_low
uint8_t mpu6050_raw_t::accel_y_high
uint8_t mpu6050_raw_t::accel_y_low
uint8_t mpu6050_raw_t::accel_z_high
uint8_t mpu6050_raw_t::accel_z_low
uint8_t mpu6050_raw_t::temp_high
uint8_t mpu6050_raw_t::temp_low
uint8_t mpu6050_raw_t::gyro_x_high
uint8_t mpu6050_raw_t::gyro_x_low
uint8_t mpu6050_raw_t::gyro_y_high
uint8_t mpu6050_raw_t::gyro_y_low
uint8_t mpu6050_raw_t::gyro_z_high
uint8_t mpu6050_raw_t::gyro_z_low
struct {
uint8_t mpu6050_raw_t::accel_x_high
uint8_t mpu6050_raw_t::accel_x_low
uint8_t mpu6050_raw_t::accel_y_high
uint8_t mpu6050_raw_t::accel_y_low
uint8_t mpu6050_raw_t::accel_z_high
uint8_t mpu6050_raw_t::accel_z_low
uint8_t mpu6050_raw_t::temp_high
uint8_t mpu6050_raw_t::temp_low
uint8_t mpu6050_raw_t::gyro_x_high
uint8_t mpu6050_raw_t::gyro_x_low
uint8_t mpu6050_raw_t::gyro_y_high
uint8_t mpu6050_raw_t::gyro_y_low
uint8_t mpu6050_raw_t::gyro_z_high
uint8_t mpu6050_raw_t::gyro_z_low
};
uint8_t MPU6050_t::Address
I2C address of device.
float MPU6050_t::Gyro_Mult
Gyroscope corrector from raw data to "degrees/s".
float MPU6050_t::Acce_Mult
Accelerometer corrector from raw data to "g".
int16_t MPU6050_t::Accelerometer_X
Accelerometer value X axis.
int16_t MPU6050_t::Accelerometer_Y
Accelerometer value Y axis.
int16_t MPU6050_t::Accelerometer_Z
Accelerometer value Z axis.
int16_t MPU6050_t::Gyroscope_X
Gyroscope value X axis.
int16_t MPU6050_t::Gyroscope_Y
Gyroscope value Y axis.
int16_t MPU6050_t::Gyroscope_Z
Gyroscope value Z axis.
float MPU6050_t::Temperature
Temperature in degrees.
mpu6050_raw_t MPU6050_t::data
uint8_t mpu6050_big_accel_t::Array [6]
int16_t mpu6050_big_accel_t::acc_x
int16_t mpu6050_big_accel_t::acc_y
int16_t mpu6050_big_accel_t::acc_z
struct {
int16_t mpu6050_big_accel_t::acc_x
int16_t mpu6050_big_accel_t::acc_y
int16_t mpu6050_big_accel_t::acc_z
};
int8_t mpu6050_big_accel_t::acc_x_high
uint8_t mpu6050_big_accel_t::acc_x_low
int8_t mpu6050_big_accel_t::acc_y_hig
uint8_t mpu6050_big_accel_t::acc_y_low
int8_t mpu6050_big_accel_t::acc_z_high
uint8_t mpu6050_big_accel_t::acc_z_low
struct {
int8_t mpu6050_big_accel_t::acc_x_high
uint8_t mpu6050_big_accel_t::acc_x_low
int8_t mpu6050_big_accel_t::acc_y_hig
uint8_t mpu6050_big_accel_t::acc_y_low
int8_t mpu6050_big_accel_t::acc_z_high
uint8_t mpu6050_big_accel_t::acc_z_low
};
uint8_t mpu6050_big_gyro_t::Array [6]
uint16_t mpu6050_big_gyro_t::gyro_x
uint16_t mpu6050_big_gyro_t::gyro_y
uint16_t mpu6050_big_gyro_t::gyro_z
struct {
uint16_t mpu6050_big_gyro_t::gyro_x
uint16_t mpu6050_big_gyro_t::gyro_y
uint16_t mpu6050_big_gyro_t::gyro_z
};
uint8_t mpu6050_big_gyro_t::gyro_x_high
uint8_t mpu6050_big_gyro_t::gyro_x_low
uint8_t mpu6050_big_gyro_t::gyro_y_high
uint8_t mpu6050_big_gyro_t::gyro_y_low
uint8_t mpu6050_big_gyro_t::gyro_z_high
uint8_t mpu6050_big_gyro_t::gyro_z_low
struct {
uint8_t mpu6050_big_gyro_t::gyro_x_high
uint8_t mpu6050_big_gyro_t::gyro_x_low
uint8_t mpu6050_big_gyro_t::gyro_y_high
uint8_t mpu6050_big_gyro_t::gyro_y_low
uint8_t mpu6050_big_gyro_t::gyro_z_high
uint8_t mpu6050_big_gyro_t::gyro_z_low
};
uint8_t mpu6050_big_temp_t::Array [2]
uint16_t mpu6050_big_temp_t::val
uint8_t mpu6050_big_temp_t::temp_high
uint8_t mpu6050_big_temp_t::temp_low
struct {
uint8_t mpu6050_big_temp_t::temp_high
uint8_t mpu6050_big_temp_t::temp_low
};
Detailed Description
Library Functions.
Function Documentation
mpu6050_clear_Accelometer()
void mpu6050_clear_Accelometer (MPU6050_t * mpu)
Definition at line 835 of file mpu6050.c.
{
    uint8_t i=0;
    mpu->Accelerometer_X=0;
    mpu->Accelerometer_Y=0;
    mpu->Accelerometer_X=0;
    for(i=0;i<MPU6050_RAW_ACCEL_LEN;i++)
        mpu->data.Array[i+MPU6050_RAW_ACCEL_Base]=0;
}
References MPU6050_t::Accelerometer_X, MPU6050_t::Accelerometer_Y, mpu6050_raw_t::Array, MPU6050_t::data, MPU6050_RAW_ACCEL_Base, and MPU6050_RAW_ACCEL_LEN.
mpu6050_clear_All()
void mpu6050_clear_All (MPU6050_t * mpu)
Definition at line 820 of file mpu6050.c.
{
    uint8_t i=0;
    for(i=0;i<MPU6050_RAW_ALL_LEN;i++)
        mpu->data.Array[i]=0;
    mpu->Accelerometer_X=0;
    mpu->Accelerometer_Y=0;
    mpu->Accelerometer_X=0;
    mpu->Gyroscope_X=0;
    mpu->Gyroscope_Y=0;
    mpu->Gyroscope_Z=0;
    mpu->Temperature=0.0f;
}
References MPU6050_t::Accelerometer_X, MPU6050_t::Accelerometer_Y, mpu6050_raw_t::Array, MPU6050_t::data, MPU6050_t::Gyroscope_X, MPU6050_t::Gyroscope_Y, MPU6050_t::Gyroscope_Z, MPU6050_RAW_ALL_LEN, and MPU6050_t::Temperature.
mpu6050_clear_Gyroscope()
void mpu6050_clear_Gyroscope (MPU6050_t * mpu)
Definition at line 845 of file mpu6050.c.
{
    uint8_t i=0;
    mpu->Gyroscope_X=0;
    mpu->Gyroscope_Y=0;
    mpu->Gyroscope_Z=0;
    for(i=0;i<MPU6050_RAW_GYRO_LEN;i++)
        mpu->data.Array[i+MPU6050_RAW_GYRO_Base]=0;
}
References mpu6050_raw_t::Array, MPU6050_t::data, MPU6050_t::Gyroscope_X, MPU6050_t::Gyroscope_Y, MPU6050_t::Gyroscope_Z, MPU6050_RAW_GYRO_Base, and MPU6050_RAW_GYRO_LEN.
mpu6050_clear_Temperature()
void mpu6050_clear_Temperature (MPU6050_t * mpu)
Definition at line 855 of file mpu6050.c.
{
    mpu->Temperature=0.0f;
    mpu->data.temp_high=0;
    mpu->data.temp_low=0;
}
References MPU6050_t::data, mpu6050_raw_t::temp_high, mpu6050_raw_t::temp_low, and MPU6050_t::Temperature.
mpu6050_DisableInterrupts()
uint8_t mpu6050_DisableInterrupts (MPU6050_t * mpu)
Disables interrupts.
Parameters
mpu Pointer to MPU6050_t structure indicating MPU6050 device
Return values
Member of MPU6050_Result_t enumeration
Definition at line 370 of file mpu6050.c.
{
    /* Disable interrupts */
  return i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_INT_ENABLE, 0x00);
}
References MPU6050_t::Address, i2c_write_7bit_base_byte_std(), MPU6050_I2C, and MPU6050_INT_ENABLE.
mpu6050_enableCycle()
uint8_t mpu6050_enableCycle (MPU6050_t * mpu, uint8_t enable)
Definition at line 514 of file mpu6050.c.
{
    uint8_t error=0,temp=0;
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_PWR_MGMT_1, &temp);
  if(error) return error;
    temp = (temp & 0xcf) | (uint8_t)enable << 5;
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_PWR_MGMT_1, temp);
  if(error) return error;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), i2c_write_7bit_base_byte_std(), MPU6050_I2C, MPU6050_PWR_MGMT_1, and TM_MPU6050_Result_Ok.
mpu6050_EnableInterrupts()
uint8_t mpu6050_EnableInterrupts (MPU6050_t * mpu)
Definition at line 347 of file mpu6050.c.
{
    uint8_t temp=0,error=0;
    /* Enable interrupts for data ready and motion detect */
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_INT_ENABLE, 0x21);//I2C_Write
    if(error) return error;
    /* Clear IRQ flag on any read operation */
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_INT_PIN_CFG, &temp);//I2C_Read
    if(error) return error;
    temp |= 0x10;
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_INT_PIN_CFG, temp);//I2C_Write
    if(error) return error;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), i2c_write_7bit_base_byte_std(), MPU6050_I2C, MPU6050_INT_ENABLE, MPU6050_INT_PIN_CFG, and TM_MPU6050_Result_Ok.
mpu6050_enableSleep()
uint8_t mpu6050_enableSleep (MPU6050_t * mpu, uint8_t enable)
Definition at line 502 of file mpu6050.c.
{
    uint8_t error=0,temp=0;
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_PWR_MGMT_1, &temp);
  if(error) return error;
    temp = (temp & 0xaf) | (uint8_t)enable << 6;
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_PWR_MGMT_1, temp);
  if(error) return error;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), i2c_write_7bit_base_byte_std(), MPU6050_I2C, MPU6050_PWR_MGMT_1, and TM_MPU6050_Result_Ok.
mpu6050_get_hpf()
uint8_t mpu6050_get_hpf (MPU6050_t * mpu, uint8_t * data)
Definition at line 768 of file mpu6050.c.
{
  /* read MPU6050_ACCEL_CONFIG register*/
  uint8_t error=0, temp=0;
  error=i2c_read_7bit_base_byte_std(MPU6050_I2C,mpu->Address,MPU6050_ACCEL_CONFIG,&temp);
  if(error) return error;
  *hpf=temp & 0x07 ;
  /* Return OK */
  return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), MPU6050_ACCEL_CONFIG, MPU6050_I2C, and TM_MPU6050_Result_Ok.
mpu6050_get_lpf()
uint8_t mpu6050_get_lpf (MPU6050_t * mpu, uint8_t * data)
Definition at line 757 of file mpu6050.c.
{
    /* read MPU6050_CONFIG register*/
  uint8_t error=0, temp=0;
  error=i2c_read_7bit_base_byte_std(MPU6050_I2C,mpu->Address,MPU6050_CONFIG,&temp);
  if(error) return error;
        *lpf=temp & 0x07 ;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), MPU6050_CONFIG, MPU6050_I2C, and TM_MPU6050_Result_Ok.
mpu6050_getAccelRange()
uint8_t mpu6050_getAccelRange (MPU6050_t * mpu, uint8_t * data)
Definition at line 779 of file mpu6050.c.
{
  /* read MPU6050_ACCEL_CONFIG register*/
  uint8_t error=0, temp=0;
  error=i2c_read_7bit_base_byte_std(MPU6050_I2C,mpu->Address,MPU6050_ACCEL_CONFIG,&temp);
  if(error) return error;
  *data=((uint8_t)temp>>3) &0x03 ;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), MPU6050_ACCEL_CONFIG, MPU6050_I2C, and TM_MPU6050_Result_Ok.
mpu6050_getClock()
uint8_t mpu6050_getClock (MPU6050_t * mpu, uint8_t * data)
Definition at line 718 of file mpu6050.c.
{
 /* read MPU6050_PWR_MGMT_1 register*/
  uint8_t error=0, temp=0;
  error=i2c_read_7bit_base_byte_std(MPU6050_I2C,mpu->Address,MPU6050_PWR_MGMT_1,&temp);
  if(error) return error;
    *data=temp & 0x07;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), MPU6050_I2C, MPU6050_PWR_MGMT_1, and TM_MPU6050_Result_Ok.
mpu6050_getCycleRate()
uint8_t mpu6050_getCycleRate (MPU6050_t * mpu, uint8_t * data)
Definition at line 735 of file mpu6050.c.
{
 /* read MPU6050_PWR_MGMT_2 register*/
  uint8_t error=0, temp=0;
  error=i2c_read_7bit_base_byte_std(MPU6050_I2C,mpu->Address,MPU6050_PWR_MGMT_2,&temp);
  if(error) return error;
    *data=(uint8_t)(temp>>6)& 0x02;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), MPU6050_I2C, MPU6050_PWR_MGMT_2, and TM_MPU6050_Result_Ok.
mpu6050_getFsyncSampleOutput()
uint8_t mpu6050_getFsyncSampleOutput (MPU6050_t * mpu, uint8_t * data)
Definition at line 746 of file mpu6050.c.
{
    /* read MPU6050_CONFIG register*/
  uint8_t error=0, temp=0;
  error=i2c_read_7bit_base_byte_std(MPU6050_I2C,mpu->Address,MPU6050_CONFIG,&temp);
  if(error) return error;
    *data=((uint8_t)temp>>3) &0x03 ;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), MPU6050_CONFIG, MPU6050_I2C, and TM_MPU6050_Result_Ok.
mpu6050_getGyroRange()
uint8_t mpu6050_getGyroRange (MPU6050_t * mpu, uint8_t * data)
Definition at line 791 of file mpu6050.c.
{
  /* read MPU6050_GYRO_CONFIG register*/
  uint8_t error=0, temp=0;
  error=i2c_read_7bit_base_byte_std(MPU6050_I2C,mpu->Address,MPU6050_GYRO_CONFIG,&temp);
  if(error) return error;
  *data=((uint8_t)temp>>3) &0x03 ;
  /* Return OK */
  return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), MPU6050_GYRO_CONFIG, MPU6050_I2C, and TM_MPU6050_Result_Ok.
mpu6050_getMotionInterruptStatus()
uint8_t mpu6050_getMotionInterruptStatus (MPU6050_t * mpu, uint8_t * status)
Definition at line 802 of file mpu6050.c.
{
 /*
   Adafruit_BusIO_Register status =
      Adafruit_BusIO_Register(i2c_dev, MPU6050_INT_STATUS, 1);
  Adafruit_BusIO_RegisterBits motion =
      Adafruit_BusIO_RegisterBits(&status, 1, 6);
  return (bool)motion.read();
 */
  return 0;
}
mpu6050_getSampleRateDivisor()
uint8_t mpu6050_getSampleRateDivisor (MPU6050_t * mpu, uint8_t * data)
Definition at line 729 of file mpu6050.c.
{
    /* read MPU6050_SMPLRT_DIV register*/
    return mpu6050_read_reg(mpu,MPU6050_SMPLRT_DIV,data);
}
References mpu6050_read_reg(), and MPU6050_SMPLRT_DIV.
mpu6050_init()
uint8_t mpu6050_init (MPU6050_t * mpu, MPU6050_Accel_Range_t Accel_Range, MPU6050_Gyro_Range_t Gyro_Range)
Initializes MPU6050 and I2C peripheral.
Parameters
mpu Pointer to empty TM_MPU6050_t structure Device_ID: MPU6050 has one pin, AD0 which can be used to set address of device. This feature allows you to use 2 different sensors on the same board with same library. If you set AD0 pin to low, then this parameter should be MPU6050_Device_0, but if AD0 pin is high, then you should use MPU6050_Device_1
Parameter can be a value of MPU6050_Device_t enumeration
Parameters
Accel_Range Set accelerometer sensitivity. This parameter can be a value of MPU6050_Accel_Range_t enumeration
Gyro_Range Set gyroscope sensitivity. This parameter can be a value of TM_MPU6050_Gyro_Range_t enumeration
Return values
Initialization status:
MPU6050_Result_t: Everything OK
Other member: in other cases
Config accelerometer
Definition at line 71 of file mpu6050.c.
{
  //uint8_t temp=0,error=0;
    /* Format I2C address */
    //DataStruct->Address = MPU6050_I2C_ADDR | (uint8_t)DeviceNumber;
    //TM_I2C_Init(MPU6050_I2C, MPU6050_I2C_PINSPACK, MPU6050_I2C_CLOCK);
    /* Check if device is connected */
    /*if(I2C_IsDeviceConnected(MPU6050_I2C, mpu->Address) != I2C_Result_Ok)
          return MPU6050_Result_DeviceNotConnected;
    */
    /* Check who am I */
    //TM_I2C_Read(MPU6050_I2C, DataStruct->Address, MPU6050_WHO_AM_I, &temp);
  //error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_WHO_AM_I, &temp);
  //if(error) return error;
    //if (temp != MPU6050_DEVICE_ID )
    //  return TM_MPU6050_Result_DeviceInvalid;
    // Config SampleRateDivisor
    uint8_t temp=0,error=0;
    //_delay_ms(200);
    /*
        // Wakeup MPU6050
    uart_print(USART1,"mpu_rst:");
    error=mpu6050_reset(mpu);
    uart_print(USART1,"\t rst:");
    uart_print_integer(USART1,error,10);
    uart_print(USART1,"\n");
     if(error) return error;
     */
    /*
    uart_print(USART1,"Read MPU6050_WHO_AM_I  :");
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_WHO_AM_I , &temp);
    uart_print(USART1,"\n Response MPU6050_WHO_AM_I  er:");
    uart_print_integer(USART1,error,16);
    uart_print(USART1,"\t rd:");
    uart_print_integer(USART1,temp,16);
    uart_print(USART1,"\r\n");
    if(error) return error;
  */
/*
    temp=0x67;
    uart_print(USART1,"write MPU6050_SMPLRT_DIV:");
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_SMPLRT_DIV, temp);//I2C_Read
    uart_print(USART1,"\t er:");
    uart_print_integer(USART1,error,16);
    uart_print(USART1,"\t rw:");
    uart_print_integer(USART1,temp,16);
    uart_print(USART1,"\r\n");
    //if(error) return error;
    temp=0x0;
    uart_print(USART1,"read MPU6050_SMPLRT_DIV:");
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_SMPLRT_DIV, &temp);//I2C_Read
    uart_print(USART1,"\t er:");
    uart_print_integer(USART1,error,16);
    uart_print(USART1,"\t rd:");
    uart_print_integer(USART1,temp,16);
    uart_print(USART1,"\r\n");
    //if(error) return error;
    temp=0xA4;
    uart_print(USART1,"write MPU6050_SMPLRT_DIV:");
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_SMPLRT_DIV, temp);//I2C_Read
    uart_print(USART1,"\t er:");
    uart_print_integer(USART1,error,16);
    uart_print(USART1,"\t rw:");
    uart_print_integer(USART1,temp,16);
    uart_print(USART1,"\r\n");
    //if(error) return error;
    temp=0x0;
    uart_print(USART1,"read MPU6050_SMPLRT_DIV:");
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_SMPLRT_DIV, &temp);//I2C_Read
    uart_print(USART1,"\t er:");
    uart_print_integer(USART1,error,16);
    uart_print(USART1,"\t rd:");
    uart_print_integer(USART1,temp,16);
    uart_print(USART1,"\r\n");
    //if(error) return error;
    temp=0;
    uart_print(USART1,"Read MPU6050_WHO_AM_I  :");
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_WHO_AM_I , &temp);
    uart_print(USART1,"\n Response MPU6050_WHO_AM_I  er:");
    uart_print_integer(USART1,error,16);
    uart_print(USART1,"\t rd:");
    uart_print_integer(USART1,temp,16);
    uart_print(USART1,"\r\n");
    //if(error) return error;
*/
    // Wakeup MPU6050
    uart_print(USART1,"mpu_rst:");
    error=mpu6050_reset(mpu);
    uart_print(USART1,"\t rst:");
    uart_print_integer(USART1,error,10);
    uart_print(USART1,"\n");
     //if(error) return error;
    // Config SampleRateDivisor
     uart_print(USART1,"mpu_smpl:");
     error=mpu6050_setSampleRateDivisor(mpu,MPU6050_DataRate_1KHz);
     uart_print(USART1,"\t smpl:");
     uart_print_integer(USART1,error,10);
     uart_print(USART1,"\n");
    //if(error) return error;
    // Config low pass filter
    uart_print(USART1,"mpu_lpf:");
    error=mpu6050_set_lpf(mpu,MPU6050_BAND_260_HZ);
    uart_print_integer(USART1,error,10);
    uart_print(USART1,"\n");
    //if(error) return error;
    // Configure High pass filter
    uart_print(USART1,"mpu_hpf:");
    error=mpu6050_set_hpf(mpu,MPU6050_HIGHPASS_2_5_HZ);
    uart_print_integer(USART1,error,10);
    uart_print(USART1,"\n");
    //if(error) return error;
   // Config accelerometer
    uart_print(USART1,"mpu_accel_rng:");
    error=mpu6050_setAccelRange(mpu,  Accel_Range);
    uart_print_integer(USART1,error,10);
    uart_print(USART1,"\n");
    //if(error) return error;
    uart_print(USART1,"mpu_gyro_rng:");
    error=mpu6050_setGyroRange(mpu,Gyro_Range);
    uart_print_integer(USART1,error,10);
    uart_print(USART1,"\n");
    //if(error) return error;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_BAND_260_HZ, MPU6050_DataRate_1KHz, MPU6050_HIGHPASS_2_5_HZ, mpu6050_reset(), mpu6050_set_hpf(), mpu6050_set_lpf(), mpu6050_setAccelRange(), mpu6050_setGyroRange(), mpu6050_setSampleRateDivisor(), TM_MPU6050_Result_Ok, uart_print(), and uart_print_integer().
Referenced by mpu6050_task().
mpu6050_read_Accelerometer()
uint8_t mpu6050_read_Accelerometer (MPU6050_t * mpu)
Reads accelerometer data from sensor.
Parameters
mpu Pointer to MPU6050_t structure to store data to
Return values
Member of MPU6050_Result_t:
MPU6050_Result_Ok: everything is OK
Other: in other cases
Definition at line 242 of file mpu6050.c.
{
    uint8_t data[6]={0};
    uint8_t error=0;
    /* Read accelerometer data */
  error=i2c_read_7bit_base_nbyte_std(MPU6050_I2C,mpu->Address, MPU6050_ACCEL_XOUT_H, data, 6);
  if(error) return error;
    /* Format */
    mpu->Accelerometer_X = (int16_t)(data[0] << 8 | data[1]);
    mpu->Accelerometer_Y = (int16_t)(data[2] << 8 | data[3]);
    mpu->Accelerometer_Z = (int16_t)(data[4] << 8 | data[5]);
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Accelerometer_X, MPU6050_t::Accelerometer_Y, MPU6050_t::Accelerometer_Z, MPU6050_t::Address, i2c_read_7bit_base_nbyte_std(), MPU6050_ACCEL_XOUT_H, MPU6050_I2C, and TM_MPU6050_Result_Ok.
mpu6050_read_All()
uint8_t mpu6050_read_All (MPU6050_t * mpu)
Reads accelerometer, gyroscope and temperature data from sensor.
Parameters
mpu Pointer to MPU6050_t structure to store data to
Return values
Member of MPU6050_Result_t:
MPU6050_Result_Ok: everything is OK
Other: in other cases
Definition at line 310 of file mpu6050.c.
{
    int16_t temp;
    //mpu6050_clear_All(mpu);
    /* Read full raw data, 14bytes */
    i2c_read_7bit_base_nbyte_std(MPU6050_I2C, mpu->Address, MPU6050_ACCEL_XOUT_H, mpu->data.Array, MPU6050_RAW_ALL_LEN );
    /* Format accelerometer data */
    mpu->Accelerometer_X = (int16_t)(mpu->data.Array[0] << 8 | mpu->data.Array[1]);
    mpu->Accelerometer_Y = (int16_t)(mpu->data.Array[2] << 8 | mpu->data.Array[3]);
    mpu->Accelerometer_Z = (int16_t)(mpu->data.Array[4] << 8 | mpu->data.Array[5]);
    /* Format temperature */
    temp = (mpu->data.Array[6] << 8 | mpu->data.Array[7]);
    mpu->Temperature = (float)((float)( (int16_t)temp) / (float)340.0f + (float)36.53);
    /* Format gyroscope data */
    mpu->Gyroscope_X = (int16_t)(mpu->data.Array[8]  << 8 | mpu->data.Array[9]);
    mpu->Gyroscope_Y = (int16_t)(mpu->data.Array[10] << 8 | mpu->data.Array[11]);
    mpu->Gyroscope_Z = (int16_t)(mpu->data.Array[12] << 8 | mpu->data.Array[13]);
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Accelerometer_X, MPU6050_t::Accelerometer_Y, MPU6050_t::Accelerometer_Z, MPU6050_t::Address, mpu6050_raw_t::Array, MPU6050_t::data, MPU6050_t::Gyroscope_X, MPU6050_t::Gyroscope_Y, MPU6050_t::Gyroscope_Z, i2c_read_7bit_base_nbyte_std(), MPU6050_ACCEL_XOUT_H, MPU6050_I2C, MPU6050_RAW_ALL_LEN, MPU6050_t::Temperature, and TM_MPU6050_Result_Ok.
Referenced by mpu6050_task().
mpu6050_read_Gyroscope()
uint8_t mpu6050_read_Gyroscope (MPU6050_t * mpu)
Reads gyroscope data from sensor.
Parameters
mpu Pointer to MPU6050_t structure to store data to
Return values
Member of MPU6050_Result_t:
MPU6050_Result_Ok: everything is OK
Other: in other cases
Definition at line 265 of file mpu6050.c.
{
    uint8_t data[6]={0};
    uint8_t error=0;
    /* Read accelerometer data */
  error=i2c_read_7bit_base_nbyte_std(MPU6050_I2C,mpu->Address, MPU6050_GYRO_XOUT_H, data, 6);
  if(error) return error;
    /* Format */
    mpu->Gyroscope_X = (int16_t)(data[0] << 8 | data[1]);
    mpu->Gyroscope_Y = (int16_t)(data[2] << 8 | data[3]);
    mpu->Gyroscope_Z = (int16_t)(data[4] << 8 | data[5]);
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, MPU6050_t::Gyroscope_X, MPU6050_t::Gyroscope_Y, MPU6050_t::Gyroscope_Z, i2c_read_7bit_base_nbyte_std(), MPU6050_GYRO_XOUT_H, MPU6050_I2C, and TM_MPU6050_Result_Ok.
mpu6050_read_Interrupts()
uint8_t mpu6050_read_Interrupts (MPU6050_t * mpu, MPU6050_Interrupt_t * InterruptsStruct)
Reads and clears interrupts.
Parameters
mpu Pointer to MPU6050_t structure indicating MPU6050 device
*InterruptsStruct Pointer to MPU6050_Interrupt_t structure to store status in
Return values
Member of MPU6050_Result_t enumeration
Definition at line 382 of file mpu6050.c.
{
    uint8_t read,error=0;
    /* Reset structure */
    InterruptsStruct->Status = 0;
    /* Read interrupts status register */
  error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_INT_STATUS, &read);
  if(error) return error;
    /* Fill value */
    InterruptsStruct->Status = read;
    /* Return OK */
    return TM_MPU6050_Result_Ok;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), MPU6050_I2C, MPU6050_INT_STATUS, MPU6050_Interrupt_t::Status, and TM_MPU6050_Result_Ok.
mpu6050_read_reg()
uint8_t mpu6050_read_reg (MPU6050_t * mpu, uint8_t reg_address, uint8_t * data)
Definition at line 707 of file mpu6050.c.
{
    /* read MPU6050_SMPLRT_DIV register*/
  uint8_t error=0, temp=0;
  error=i2c_read_7bit_base_byte_std(MPU6050_I2C,mpu->Address,reg_address,&temp);
  if(error) return error;
    *data=temp;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), MPU6050_I2C, and TM_MPU6050_Result_Ok.
Referenced by mpu6050_getSampleRateDivisor().
mpu6050_read_Temperature()
uint8_t mpu6050_read_Temperature (MPU6050_t * mpu)
Reads temperature data from sensor.
Parameters
*mpu Pointer to MPU6050_t structure to store data to
Return values
Member of MPU6050_Result_t:
MPU6050_Result_Ok: everything is OK
Other: in other cases
Definition at line 288 of file mpu6050.c.
{
    uint8_t data[2]={0};
    uint8_t error=0;
    int16_t temp=0;
    /* Read accelerometer data */
  error=i2c_read_7bit_base_nbyte_std(MPU6050_I2C,mpu->Address,MPU6050_TEMP_H, data, 2);
  if(error) return error;
    /* Format */
    temp = (data[0] << 8 | data[1]);
    mpu->Temperature = (float)((int16_t)temp / (float)340.0 + (float)36.53);
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_nbyte_std(), MPU6050_I2C, MPU6050_TEMP_H, MPU6050_t::Temperature, and TM_MPU6050_Result_Ok.
mpu6050_reset()
uint8_t mpu6050_reset (MPU6050_t * mpu)
Definition at line 219 of file mpu6050.c.
{
  uint8_t error=0;
 error=i2c_write_7bit_base_byte_std(MPU6050_I2C,mpu->Address,MPU6050_PWR_MGMT_1, 0x00); // should be 0x80
    _delay_ms(200);
   if(error) return error;
  error=i2c_write_7bit_base_byte_std(MPU6050_I2C,mpu->Address,MPU6050_SIGNAL_PATH_RESET, 0x07); // should be0x80
    _delay_ms(200);
    if(error) return error;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References _delay_ms(), MPU6050_t::Address, i2c_write_7bit_base_byte_std(), MPU6050_I2C, MPU6050_PWR_MGMT_1, MPU6050_SIGNAL_PATH_RESET, and TM_MPU6050_Result_Ok.
Referenced by mpu6050_init().
mpu6050_set_hpf()
uint8_t mpu6050_set_hpf (MPU6050_t * mpu, MPU6050_Accel_HPF_t bandwidth)
Definition at line 572 of file mpu6050.c.
{
  uint8_t error=0,temp=0;
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_ACCEL_CONFIG, &temp);
    uart_print(USART1,"\t rd_AccCONFIG:");
    uart_print_integer(USART1,error,10);
    uart_print(USART1,"\t ");
    uart_print_integer(USART1,temp,10);
    uart_print(USART1,"\n");
    i2c_uart_print(USART1);
  //if(error) return error;
    temp =  (temp & 0xf8)|(uint8_t)bandwidth;
    uart_print(USART1,"\t to write");
    uart_print_integer(USART1,temp,10);
    uart_print(USART1,"\n");
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address,MPU6050_ACCEL_CONFIG, temp);
    uart_print(USART1,"\t wr_CONFIG:");
    uart_print_integer(USART1,error,10);
    uart_print(USART1,"\t ");
    uart_print_integer(USART1,temp,10);
    uart_print(USART1,"\n");
    i2c_uart_print(USART1);
  //if(error) return error;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), i2c_uart_print(), i2c_write_7bit_base_byte_std(), MPU6050_ACCEL_CONFIG, MPU6050_I2C, TM_MPU6050_Result_Ok, uart_print(), and uart_print_integer().
Referenced by mpu6050_init().
mpu6050_set_lpf()
uint8_t mpu6050_set_lpf (MPU6050_t * mpu, MPU6050_LPF_bandwidth_t bandwidth)
Definition at line 544 of file mpu6050.c.
{
  uint8_t error=0,temp=0;
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_CONFIG, &temp);
    uart_print(USART1,"\t rd_CONFIG:");
    uart_print_integer(USART1,error,10);
    uart_print(USART1,"\t ");
    uart_print_integer(USART1,temp,10);
    uart_print(USART1,"\n");
    i2c_uart_print(USART1);
  //if(error) return error;
    temp =  (temp & 0xf8)|(uint8_t)bandwidth;
    uart_print(USART1,"\t to write");
    uart_print_integer(USART1,temp,10);
    uart_print(USART1,"\n");
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address,MPU6050_CONFIG, temp);
    uart_print(USART1,"\t wr_CONFIG:");
    uart_print_integer(USART1,error,10);
    uart_print(USART1,"\t ");
    uart_print_integer(USART1,temp,10);
    uart_print(USART1,"\n");
    i2c_uart_print(USART1);
    //if(error) return error;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), i2c_uart_print(), i2c_write_7bit_base_byte_std(), MPU6050_CONFIG, MPU6050_I2C, TM_MPU6050_Result_Ok, uart_print(), and uart_print_integer().
Referenced by mpu6050_init().
mpu6050_setAccelerometerStandby()
uint8_t mpu6050_setAccelerometerStandby (MPU6050_t * mpu, uint8_t xAxisStandby, uint8_t yAxisStandby, uint8_t zAxisStandby)
Definition at line 676 of file mpu6050.c.
{
  uint8_t error=0,temp=0,stdby=0;
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_PWR_MGMT_2, &temp);
  if(error) return error;
    stdby=(uint8_t)(xAxisStandby << 2 | yAxisStandby << 1 | zAxisStandby);
    temp = (uint8_t) (temp & 0xf8) | (stdby<<3) ;
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_PWR_MGMT_2, temp);
  if(error) return error;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), i2c_write_7bit_base_byte_std(), MPU6050_I2C, MPU6050_PWR_MGMT_2, and TM_MPU6050_Result_Ok.
mpu6050_setAccelRange()
uint8_t mpu6050_setAccelRange (MPU6050_t * mpu, MPU6050_Accel_Range_t Accel_Range)
Sets accelerometer sensitivity.
Parameters
*mpu Pointer to MPU6050_t structure indicating MPU6050 device
AccelerometerSensitivity Gyro sensitivity value. This parameter can be a value of MPU6050_AccelRange_t enumeration
Return values
Member of MPU6050_Result_t enumeration
Definition at line 444 of file mpu6050.c.
{
    uint8_t temp=0;
    uint8_t error=0;
    /* Config accelerometer */
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_ACCEL_CONFIG, &temp);
  if(error) return error;
    temp = (temp & 0xE7) | (uint8_t)Accel_Range << 3;
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_ACCEL_CONFIG, temp);
  if(error) return error;
    /* Set sensitivities for multiplying gyro and accelerometer data */
    switch (Accel_Range)
    {
        case MPU6050_Accel_Range_2G:  mpu->Acce_Mult = (float)1 / MPU6050_ACCE_SENS_2;  break;
        case MPU6050_Accel_Range_4G:  mpu->Acce_Mult = (float)1 / MPU6050_ACCE_SENS_4;  break;
        case MPU6050_Accel_Range_8G:  mpu->Acce_Mult = (float)1 / MPU6050_ACCE_SENS_8;  break;
        case MPU6050_Accel_Range_16G: mpu->Acce_Mult = (float)1 / MPU6050_ACCE_SENS_16; break;
        default:
        break;
    }
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Acce_Mult, MPU6050_t::Address, i2c_read_7bit_base_byte_std(), i2c_write_7bit_base_byte_std(), MPU6050_ACCE_SENS_16, MPU6050_ACCE_SENS_2, MPU6050_ACCE_SENS_4, MPU6050_ACCE_SENS_8, MPU6050_ACCEL_CONFIG, MPU6050_Accel_Range_16G, MPU6050_Accel_Range_2G, MPU6050_Accel_Range_4G, MPU6050_Accel_Range_8G, MPU6050_I2C, and TM_MPU6050_Result_Ok.
Referenced by mpu6050_init().
mpu6050_setClock()
uint8_t mpu6050_setClock (MPU6050_t * mpu, MPU6050_Clock_Select_t clock_select)
Definition at line 469 of file mpu6050.c.
{
  return 0;
}
mpu6050_setCycleRate()
uint8_t mpu6050_setCycleRate (MPU6050_t * mpu, MPU6050_Cycle_Rate_t rate)
Definition at line 490 of file mpu6050.c.
{
    uint8_t error=0,temp=0;
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_PWR_MGMT_2, &temp);
  if(error) return error;
    temp = (temp & 0x3f) | (uint8_t)rate << 6;
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_PWR_MGMT_2, temp);
  if(error) return error;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), i2c_write_7bit_base_byte_std(), MPU6050_I2C, MPU6050_PWR_MGMT_2, and TM_MPU6050_Result_Ok.
mpu6050_setDataRate()
uint8_t mpu6050_setDataRate (MPU6050_t * mpu, uint8_t rate)
Sets output data rate.
Parameters
*mpu Pointer to MPU6050_t structure indicating MPU6050 device
rate Data rate value. An 8-bit value for prescaler value
Return values
Member of MPU6050_Result_t enumeration
Definition at line 480 of file mpu6050.c.
{
    return i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_SMPLRT_DIV, rate);
}
References MPU6050_t::Address, i2c_write_7bit_base_byte_std(), MPU6050_I2C, and MPU6050_SMPLRT_DIV.
mpu6050_setFsyncSampleOutput()
uint8_t mpu6050_setFsyncSampleOutput (MPU6050_t * mpu, MPU6050_Fsync_out_t fsync_output)
Definition at line 625 of file mpu6050.c.
{
 return 0;
}
mpu6050_setGyroRange()
uint8_t mpu6050_setGyroRange (MPU6050_t * mpu, MPU6050_Gyro_Range_t Gyro_range)
Sets gyroscope sensitivity.
Parameters
*mpu Pointer to TM_MPU6050_t structure indicating MPU6050 device
GyroscopeSensitivity Gyro sensitivity value. This parameter can be a value of MPU6050_Gyro_Range_t enumeration
Return values
Member of TM_MPU6050_Result_t enumeration
Definition at line 412 of file mpu6050.c.
{
  uint8_t temp=0;
  uint8_t error=0;
    /* Config gyroscope */
    //TM_I2C_Read(MPU6050_I2C, DataStruct->Address, MPU6050_GYRO_CONFIG, &temp);
  error=i2c_read_7bit_base_byte_std(MPU6050_I2C,mpu->Address,MPU6050_GYRO_CONFIG, &temp);
  if(error) return error;
    temp = (temp & 0xE7) | (uint8_t)Gyro_range << 3;
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_GYRO_CONFIG, temp);//TM_I2C_Write(MPU6050_I2C, mpu->Address, MPU6050_GYRO_CONFIG, temp);
    if(error) return error;
    switch (Gyro_range)
    {
        case MPU6050_Gyro_Range_250s: mpu->Gyro_Mult = (float)1 / MPU6050_GYRO_SENS_250;  break;
        case MPU6050_Gyro_Range_500s: mpu->Gyro_Mult = (float)1 / MPU6050_GYRO_SENS_500;  break;
        case MPU6050_Gyro_Range_1000s:mpu->Gyro_Mult = (float)1 / MPU6050_GYRO_SENS_1000; break;
        case MPU6050_Gyro_Range_2000s:mpu->Gyro_Mult = (float)1 / MPU6050_GYRO_SENS_2000; break;
        default:
        break;
    }
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, MPU6050_t::Gyro_Mult, i2c_read_7bit_base_byte_std(), i2c_write_7bit_base_byte_std(), MPU6050_GYRO_CONFIG, MPU6050_Gyro_Range_1000s, MPU6050_Gyro_Range_2000s, MPU6050_Gyro_Range_250s, MPU6050_Gyro_Range_500s, MPU6050_GYRO_SENS_1000, MPU6050_GYRO_SENS_2000, MPU6050_GYRO_SENS_250, MPU6050_GYRO_SENS_500, MPU6050_I2C, and TM_MPU6050_Result_Ok.
Referenced by mpu6050_init().
mpu6050_setGyroStandby()
uint8_t mpu6050_setGyroStandby (MPU6050_t * mpu, uint8_t xAxisStandby, uint8_t yAxisStandby, uint8_t zAxisStandby)
Definition at line 663 of file mpu6050.c.
{
 uint8_t error=0,temp=0,stdby=0;
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_PWR_MGMT_2, &temp);
  if(error) return error;
    stdby=(uint8_t)(xAxisStandby << 2 | yAxisStandby << 1 | zAxisStandby);
    temp = (temp & 0xf8) |stdby;
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_PWR_MGMT_2, temp);
  if(error) return error;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), i2c_write_7bit_base_byte_std(), MPU6050_I2C, MPU6050_PWR_MGMT_2, and TM_MPU6050_Result_Ok.
mpu6050_setI2CBypass()
uint8_t mpu6050_setI2CBypass (MPU6050_t * mpu, uint8_t bypass)
Definition at line 526 of file mpu6050.c.
{
    uint8_t error=0,temp=0;
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_INT_PIN_CFG, &temp);
  if(error) return error;
    temp =  (uint8_t)bypass << 1;
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address,MPU6050_INT_PIN_CFG, temp);
  if(error) return error;
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_USER_CTRL, &temp);
  if(error) return error;
    temp &=0x57;
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address,MPU6050_USER_CTRL, temp);
  if(error) return error;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), i2c_write_7bit_base_byte_std(), MPU6050_I2C, MPU6050_INT_PIN_CFG, MPU6050_USER_CTRL, and TM_MPU6050_Result_Ok.
mpu6050_setInterruptPinLatch()
uint8_t mpu6050_setInterruptPinLatch (MPU6050_t * mpu, uint8_t held)
mpu6050_setInterruptPinPolarity()
uint8_t mpu6050_setInterruptPinPolarity (MPU6050_t * mpu, uint8_t active_low)
Definition at line 601 of file mpu6050.c.
{
    /*
      Adafruit_BusIO_Register int_pin_config =
      Adafruit_BusIO_Register(i2c_dev, MPU6050_INT_PIN_CONFIG, 1);
  Adafruit_BusIO_RegisterBits int_level =
      Adafruit_BusIO_RegisterBits(&int_pin_config, 1, 7);
  int_level.write(active_low);
    */
 return 0;
}
mpu6050_setMotionDetectionDuration()
uint8_t mpu6050_setMotionDetectionDuration (MPU6050_t * mpu, uint8_t dur)
Definition at line 653 of file mpu6050.c.
{
        /*
      Adafruit_BusIO_Register duration =
      Adafruit_BusIO_Register(i2c_dev, MPU6050_MOT_DUR, 1);
  duration.write(dur);
    */
 return 0;
}
mpu6050_setMotionDetectionThreshold()
uint8_t mpu6050_setMotionDetectionThreshold (MPU6050_t * mpu, uint8_t thr)
Definition at line 643 of file mpu6050.c.
{
    /*
      Adafruit_BusIO_Register threshold =
    Adafruit_BusIO_Register(i2c_dev, MPU6050_MOT_THR, 1);
    threshold.write(thr);
    */
 return 0;
}
mpu6050_setMotionInterrupt()
uint8_t mpu6050_setMotionInterrupt (MPU6050_t * mpu, uint8_t active)
Definition at line 630 of file mpu6050.c.
{
    /*
      Adafruit_BusIO_Register int_enable =
      Adafruit_BusIO_Register(i2c_dev, MPU6050_INT_ENABLE, 1);
  Adafruit_BusIO_RegisterBits int_motion =
      Adafruit_BusIO_RegisterBits(&int_enable, 1, 6);
  int_motion.write(active);
 */
return 0;
}
mpu6050_setSampleRateDivisor()
uint8_t mpu6050_setSampleRateDivisor (MPU6050_t * mpu, uint8_t SampleRateDiv)
Definition at line 485 of file mpu6050.c.
{
     return i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_SMPLRT_DIV, SampleRateDiv);
}
References MPU6050_t::Address, i2c_write_7bit_base_byte_std(), MPU6050_I2C, and MPU6050_SMPLRT_DIV.
Referenced by mpu6050_init().
mpu6050_setTemperatureStandby()
uint8_t mpu6050_setTemperatureStandby (MPU6050_t * mpu, uint8_t enable)
Definition at line 689 of file mpu6050.c.
{
  uint8_t error=0,temp=0;
    error=i2c_read_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_PWR_MGMT_1, &temp);
  if(error) return error;
    temp = (temp & 0xE7) | (enable<<3) ;
    error=i2c_write_7bit_base_byte_std(MPU6050_I2C, mpu->Address, MPU6050_PWR_MGMT_1, temp);
  if(error) return error;
    /* Return OK */
    return TM_MPU6050_Result_Ok; //  or return I2C_NO_ERROR;
}
References MPU6050_t::Address, i2c_read_7bit_base_byte_std(), i2c_write_7bit_base_byte_std(), MPU6050_I2C, MPU6050_PWR_MGMT_1, and TM_MPU6050_Result_Ok.
mpu6050_uart_print()
void mpu6050_uart_print (USART_TypeDef * uart, MPU6050_t * mpu)
Definition at line 867 of file mpu6050.c.
{
    // print Accelometer
     mpu6050_uart_print_Accelometer(uart,mpu);
    // print Gyroscope
      mpu6050_uart_print_Gyroscope(uart,mpu);
    // print temprature
     mpu6050_uart_print_Temperature(uart,mpu);
}
References mpu6050_uart_print_Accelometer(), mpu6050_uart_print_Gyroscope(), and mpu6050_uart_print_Temperature().
Referenced by mpu6050_task().
mpu6050_uart_print_Accelometer()
void mpu6050_uart_print_Accelometer (USART_TypeDef * uart, MPU6050_t * mpu)
Definition at line 877 of file mpu6050.c.
{
    uart_print(uart,"\t Accel_X:");
    uart_print_integer(uart,mpu->Accelerometer_X,10);
    uart_print(uart,"\t Accel_Y:");
    uart_print_integer(uart,mpu->Accelerometer_Y,10);
    uart_print(uart,"\t Accel_Z:");
    uart_print_integer(uart,mpu->Accelerometer_Z,10);
    uart_print(uart,"\n");
}
References MPU6050_t::Accelerometer_X, MPU6050_t::Accelerometer_Y, MPU6050_t::Accelerometer_Z, uart_print(), and uart_print_integer().
Referenced by mpu6050_uart_print().
mpu6050_uart_print_Gyroscope()
void mpu6050_uart_print_Gyroscope (USART_TypeDef * uart, MPU6050_t * mpu)
Definition at line 888 of file mpu6050.c.
{
    uart_print(uart,"\t Gyro_X:");
    uart_print_integer(uart,mpu->Gyroscope_X,10);
    uart_print(uart,"\t Gyro_Y:");
    uart_print_integer(uart,mpu->Gyroscope_Y,10);
    uart_print(uart,"\t Gyro_Z:");
    uart_print_integer(uart,mpu->Gyroscope_Z,10);
    uart_print(uart,"\n");
}
References MPU6050_t::Gyroscope_X, MPU6050_t::Gyroscope_Y, MPU6050_t::Gyroscope_Z, uart_print(), and uart_print_integer().
Referenced by mpu6050_uart_print().
mpu6050_uart_print_raw_Accelometer()
void mpu6050_uart_print_raw_Accelometer (USART_TypeDef * uart, MPU6050_t * mpu)
Definition at line 913 of file mpu6050.c.
{
    WORD_BYTES t;
    t.word=0;
    t.byte.high=mpu->data.accel_x_high;
    t.byte.low=mpu->data.accel_x_low;
    uart_print(uart,"\t ACCEL_XOUT:");
    uart_print_integer(uart,t.word,16);
    t.byte.high=mpu->data.accel_y_high;
    t.byte.low=mpu->data.accel_y_low;
    uart_print(uart,"\t ACCEL_YOUT:");
    uart_print_integer(uart,t.word,16);
    t.byte.high=mpu->data.accel_z_high;
    t.byte.low=mpu->data.accel_z_low;
    uart_print(uart,"\t ACCEL_ZOUT:");
    uart_print_integer(uart,t.word,16);
    uart_print(uart,"\r\n");
}
References mpu6050_raw_t::accel_x_high, mpu6050_raw_t::accel_x_low, mpu6050_raw_t::accel_y_high, mpu6050_raw_t::accel_y_low, mpu6050_raw_t::accel_z_high, mpu6050_raw_t::accel_z_low, WORD_BYTES::byte, MPU6050_t::data, WORD_BYTES::high, WORD_BYTES::low, uart_print(), uart_print_integer(), and WORD_BYTES::word.
Referenced by mpu6050_uart_print_raw_Data().
mpu6050_uart_print_raw_Array()
void mpu6050_uart_print_raw_Array (USART_TypeDef * uart, MPU6050_t * mpu)
Definition at line 971 of file mpu6050.c.
{
    uint8_t i=0, index=MPU6050_ACCEL_OUT;
    for (i=0;i<MPU6050_RAW_ALL_LEN ;i++)
    {
        uart_print(uart,"\t reg @ (");
        uart_print_integer(uart,index,16);
        uart_print(uart,"):");
        uart_print_integer(uart,mpu->data.Array[i],16);
        uart_print(uart,"\n");
        index++;
    }
    uart_print(uart,"\r\n\n");
}
References mpu6050_raw_t::Array, MPU6050_t::data, MPU6050_ACCEL_OUT, MPU6050_RAW_ALL_LEN, uart_print(), and uart_print_integer().
Referenced by mpu6050_task().
mpu6050_uart_print_raw_Data()
void mpu6050_uart_print_raw_Data (USART_TypeDef * uart, MPU6050_t * mpu)
Definition at line 906 of file mpu6050.c.
{
     mpu6050_uart_print_raw_Accelometer(uart,mpu);
     mpu6050_uart_print_raw_Gyroscope(uart,mpu);
     mpu6050_uart_print_raw_Temperature(uart,mpu);
}
References mpu6050_uart_print_raw_Accelometer(), mpu6050_uart_print_raw_Gyroscope(), and mpu6050_uart_print_raw_Temperature().
Referenced by mpu6050_task().
mpu6050_uart_print_raw_Gyroscope()
void mpu6050_uart_print_raw_Gyroscope (USART_TypeDef * uart, MPU6050_t * mpu)
Definition at line 935 of file mpu6050.c.
{
    WORD_BYTES t;
    t.word=0;
    t.byte.high=mpu->data.gyro_x_high;
    t.byte.low=mpu->data.gyro_x_low;
    uart_print(uart,"\t GYRO_XOUT:");
    uart_print_integer(uart,t.word,16);
    t.byte.high=mpu->data.gyro_y_high;
    t.byte.low=mpu->data.gyro_y_low;
    uart_print(uart,"\t GYRO_YOUT:");
    uart_print_integer(uart,t.word,16);
    t.byte.high=mpu->data.gyro_z_high;
    t.byte.low=mpu->data.gyro_z_low;
    uart_print(uart,"\t GYRO_ZOUT:");
    uart_print_integer(uart,t.word,16);
    uart_print(uart,"\r\n");
}
References WORD_BYTES::byte, MPU6050_t::data, mpu6050_raw_t::gyro_x_high, mpu6050_raw_t::gyro_x_low, mpu6050_raw_t::gyro_y_high, mpu6050_raw_t::gyro_y_low, mpu6050_raw_t::gyro_z_high, mpu6050_raw_t::gyro_z_low, WORD_BYTES::high, WORD_BYTES::low, uart_print(), uart_print_integer(), and WORD_BYTES::word.
Referenced by mpu6050_uart_print_raw_Data().
mpu6050_uart_print_raw_Temperature()
void mpu6050_uart_print_raw_Temperature (USART_TypeDef * uart, MPU6050_t * mpu)
Definition at line 958 of file mpu6050.c.
{
    WORD_BYTES t;
    t.word=0;
    t.byte.high=mpu->data.temp_high;
    t.byte.low=mpu->data.temp_low;
    uart_print(uart,"\t TEMP_OUT:");
    uart_print_integer(uart,t.word,16);
    uart_print(uart,"\r\n");
}
References WORD_BYTES::byte, MPU6050_t::data, WORD_BYTES::high, WORD_BYTES::low, mpu6050_raw_t::temp_high, mpu6050_raw_t::temp_low, uart_print(), uart_print_integer(), and WORD_BYTES::word.
Referenced by mpu6050_uart_print_raw_Data().
mpu6050_uart_print_Temperature()
void mpu6050_uart_print_Temperature (USART_TypeDef * uart, MPU6050_t * mpu)
Definition at line 899 of file mpu6050.c.
{
    uart_print(uart,"\t Temp:");
    uart_print_float(uart,mpu->Temperature,2);
    uart_print(uart,"\n");
}
References MPU6050_t::Temperature, uart_print(), and uart_print_float().
Referenced by mpu6050_uart_print().
Variable Documentation
struct { ... } mpu6050_raw_t::@76
struct { ... } mpu6050_big_accel_t::@78
struct { ... } mpu6050_big_accel_t::@80
struct { ... } mpu6050_big_gyro_t::@82
struct { ... } mpu6050_big_gyro_t::@84
struct { ... } mpu6050_big_temp_t::@86
[1/2]
int16_t { ... } ::acc_x
Definition at line 467 of file mpu6050.h.
acc_x [2/2]
int16_t mpu6050_big_accel_t::acc_x
Definition at line 467 of file mpu6050.h.
acc_x_high [1/2]
int8_t mpu6050_big_accel_t::acc_x_high
Definition at line 473 of file mpu6050.h.
[2/2]
int8_t { ... } ::acc_x_high
Definition at line 473 of file mpu6050.h.
[1/2]
uint8_t { ... } ::acc_x_low
Definition at line 474 of file mpu6050.h.
acc_x_low [2/2]
uint8_t mpu6050_big_accel_t::acc_x_low
Definition at line 474 of file mpu6050.h.
acc_y [1/2]
int16_t mpu6050_big_accel_t::acc_y
Definition at line 468 of file mpu6050.h.
[2/2]
int16_t { ... } ::acc_y
Definition at line 468 of file mpu6050.h.
[1/2]
int8_t { ... } ::acc_y_hig
Definition at line 475 of file mpu6050.h.
acc_y_hig [2/2]
int8_t mpu6050_big_accel_t::acc_y_hig
Definition at line 475 of file mpu6050.h.
[1/2]
uint8_t { ... } ::acc_y_low
Definition at line 476 of file mpu6050.h.
acc_y_low [2/2]
uint8_t mpu6050_big_accel_t::acc_y_low
Definition at line 476 of file mpu6050.h.
[1/2]
int16_t { ... } ::acc_z
Definition at line 469 of file mpu6050.h.
acc_z [2/2]
int16_t mpu6050_big_accel_t::acc_z
Definition at line 469 of file mpu6050.h.
[1/2]
int8_t { ... } ::acc_z_high
Definition at line 477 of file mpu6050.h.
acc_z_high [2/2]
int8_t mpu6050_big_accel_t::acc_z_high
Definition at line 477 of file mpu6050.h.
acc_z_low [1/2]
uint8_t mpu6050_big_accel_t::acc_z_low
Definition at line 478 of file mpu6050.h.
[2/2]
uint8_t { ... } ::acc_z_low
Definition at line 478 of file mpu6050.h.
Acce_Mult
float MPU6050_t::Acce_Mult
Accelerometer corrector from raw data to "g".
Only for private use
Definition at line 440 of file mpu6050.h.
Referenced by mpu6050_setAccelRange().
accel_x_high [1/2]
uint8_t mpu6050_raw_t::accel_x_high
Definition at line 414 of file mpu6050.h.
Referenced by mpu6050_uart_print_raw_Accelometer().
[2/2]
uint8_t { ... } ::accel_x_high
Definition at line 414 of file mpu6050.h.
accel_x_low [1/2]
uint8_t mpu6050_raw_t::accel_x_low
Definition at line 415 of file mpu6050.h.
Referenced by mpu6050_uart_print_raw_Accelometer().
[2/2]
uint8_t { ... } ::accel_x_low
Definition at line 415 of file mpu6050.h.
accel_y_high [1/2]
uint8_t mpu6050_raw_t::accel_y_high
Definition at line 416 of file mpu6050.h.
Referenced by mpu6050_uart_print_raw_Accelometer().
[2/2]
uint8_t { ... } ::accel_y_high
Definition at line 416 of file mpu6050.h.
accel_y_low [1/2]
uint8_t mpu6050_raw_t::accel_y_low
Definition at line 417 of file mpu6050.h.
Referenced by mpu6050_uart_print_raw_Accelometer().
[2/2]
uint8_t { ... } ::accel_y_low
Definition at line 417 of file mpu6050.h.
accel_z_high [1/2]
uint8_t mpu6050_raw_t::accel_z_high
Definition at line 418 of file mpu6050.h.
Referenced by mpu6050_uart_print_raw_Accelometer().
[2/2]
uint8_t { ... } ::accel_z_high
Definition at line 418 of file mpu6050.h.
accel_z_low [1/2]
uint8_t mpu6050_raw_t::accel_z_low
Definition at line 419 of file mpu6050.h.
Referenced by mpu6050_uart_print_raw_Accelometer().
[2/2]
uint8_t { ... } ::accel_z_low
Definition at line 419 of file mpu6050.h.
Accelerometer_X
int16_t MPU6050_t::Accelerometer_X
Accelerometer value X axis.
Definition at line 442 of file mpu6050.h.
Referenced by mpu6050_clear_Accelometer(), mpu6050_clear_All(), mpu6050_read_Accelerometer(), mpu6050_read_All(), and mpu6050_uart_print_Accelometer().
Accelerometer_Y
int16_t MPU6050_t::Accelerometer_Y
Accelerometer value Y axis.
Definition at line 443 of file mpu6050.h.
Referenced by mpu6050_clear_Accelometer(), mpu6050_clear_All(), mpu6050_read_Accelerometer(), mpu6050_read_All(), and mpu6050_uart_print_Accelometer().
Accelerometer_Z
int16_t MPU6050_t::Accelerometer_Z
Accelerometer value Z axis.
Definition at line 444 of file mpu6050.h.
Referenced by mpu6050_read_Accelerometer(), mpu6050_read_All(), and mpu6050_uart_print_Accelometer().
Address
uint8_t MPU6050_t::Address
I2C address of device.
Only for private use
Definition at line 438 of file mpu6050.h.
Referenced by mpu6050_DisableInterrupts(), mpu6050_enableCycle(), mpu6050_EnableInterrupts(), mpu6050_enableSleep(), mpu6050_get_hpf(), mpu6050_get_lpf(), mpu6050_getAccelRange(), mpu6050_getClock(), mpu6050_getCycleRate(), mpu6050_getFsyncSampleOutput(), mpu6050_getGyroRange(), mpu6050_read_Accelerometer(), mpu6050_read_All(), mpu6050_read_Gyroscope(), mpu6050_read_Interrupts(), mpu6050_read_reg(), mpu6050_read_Temperature(), mpu6050_reset(), mpu6050_set_hpf(), mpu6050_set_lpf(), mpu6050_setAccelerometerStandby(), mpu6050_setAccelRange(), mpu6050_setCycleRate(), mpu6050_setDataRate(), mpu6050_setGyroRange(), mpu6050_setGyroStandby(), mpu6050_setI2CBypass(), mpu6050_setSampleRateDivisor(), mpu6050_setTemperatureStandby(), and mpu6050_task().
Array [1/4]
uint8_t mpu6050_big_temp_t::Array[2]
Definition at line 505 of file mpu6050.h.
Array [2/4]
uint8_t mpu6050_big_accel_t::Array[6]
Definition at line 465 of file mpu6050.h.
Array [3/4]
uint8_t mpu6050_big_gyro_t::Array[6]
Definition at line 485 of file mpu6050.h.
Array [4/4]
uint8_t mpu6050_raw_t::Array[MPU6050_RAW_ALL_LEN]
Definition at line 411 of file mpu6050.h.
Referenced by mpu6050_clear_Accelometer(), mpu6050_clear_All(), mpu6050_clear_Gyroscope(), mpu6050_read_All(), and mpu6050_uart_print_raw_Array().
data
mpu6050_raw_t MPU6050_t::data
Definition at line 449 of file mpu6050.h.
Referenced by mpu6050_clear_Accelometer(), mpu6050_clear_All(), mpu6050_clear_Gyroscope(), mpu6050_clear_Temperature(), mpu6050_read_All(), mpu6050_uart_print_raw_Accelometer(), mpu6050_uart_print_raw_Array(), mpu6050_uart_print_raw_Gyroscope(), and mpu6050_uart_print_raw_Temperature().
[1/2]
uint8_t { ... } ::DataReady
Data ready interrupt.
Definition at line 383 of file mpu6050.h.
DataReady [2/2]
uint8_t MPU6050_Interrupt_t::DataReady
Data ready interrupt.
Definition at line 383 of file mpu6050.h.
struct { ... } MPU6050_Interrupt_t::F
[1/2]
uint8_t { ... } ::FifoOverflow
FIFO overflow interrupt.
Not enabled with library
Definition at line 386 of file mpu6050.h.
FifoOverflow [2/2]
uint8_t MPU6050_Interrupt_t::FifoOverflow
FIFO overflow interrupt.
Not enabled with library
Definition at line 386 of file mpu6050.h.
Gyro_Mult
float MPU6050_t::Gyro_Mult
Gyroscope corrector from raw data to "degrees/s".
Only for private use
Definition at line 439 of file mpu6050.h.
Referenced by mpu6050_setGyroRange().
gyro_x [1/2]
uint16_t mpu6050_big_gyro_t::gyro_x
Definition at line 487 of file mpu6050.h.
[2/2]
uint16_t { ... } ::gyro_x
Definition at line 487 of file mpu6050.h.
gyro_x_high [1/4]
uint8_t mpu6050_raw_t::gyro_x_high
Definition at line 424 of file mpu6050.h.
Referenced by mpu6050_uart_print_raw_Gyroscope().
[2/4]
uint8_t { ... } ::gyro_x_high
Definition at line 424 of file mpu6050.h.
gyro_x_high [3/4]
uint8_t mpu6050_big_gyro_t::gyro_x_high
Definition at line 493 of file mpu6050.h.
[4/4]
uint8_t { ... } ::gyro_x_high
Definition at line 493 of file mpu6050.h.
gyro_x_low [1/4]
uint8_t mpu6050_raw_t::gyro_x_low
Definition at line 425 of file mpu6050.h.
Referenced by mpu6050_uart_print_raw_Gyroscope().
[2/4]
uint8_t { ... } ::gyro_x_low
Definition at line 425 of file mpu6050.h.
gyro_x_low [3/4]
uint8_t mpu6050_big_gyro_t::gyro_x_low
Definition at line 494 of file mpu6050.h.
[4/4]
uint8_t { ... } ::gyro_x_low
Definition at line 494 of file mpu6050.h.
gyro_y [1/2]
uint16_t mpu6050_big_gyro_t::gyro_y
Definition at line 488 of file mpu6050.h.
[2/2]
uint16_t { ... } ::gyro_y
Definition at line 488 of file mpu6050.h.
gyro_y_high [1/4]
uint8_t mpu6050_raw_t::gyro_y_high
Definition at line 426 of file mpu6050.h.
Referenced by mpu6050_uart_print_raw_Gyroscope().
[2/4]
uint8_t { ... } ::gyro_y_high
Definition at line 426 of file mpu6050.h.
gyro_y_high [3/4]
uint8_t mpu6050_big_gyro_t::gyro_y_high
Definition at line 495 of file mpu6050.h.
[4/4]
uint8_t { ... } ::gyro_y_high
Definition at line 495 of file mpu6050.h.
gyro_y_low [1/4]
uint8_t mpu6050_raw_t::gyro_y_low
Definition at line 427 of file mpu6050.h.
Referenced by mpu6050_uart_print_raw_Gyroscope().
[2/4]
uint8_t { ... } ::gyro_y_low
Definition at line 427 of file mpu6050.h.
gyro_y_low [3/4]
uint8_t mpu6050_big_gyro_t::gyro_y_low
Definition at line 496 of file mpu6050.h.
[4/4]
uint8_t { ... } ::gyro_y_low
Definition at line 496 of file mpu6050.h.
gyro_z [1/2]
uint16_t mpu6050_big_gyro_t::gyro_z
Definition at line 489 of file mpu6050.h.
[2/2]
uint16_t { ... } ::gyro_z
Definition at line 489 of file mpu6050.h.
[1/4]
uint8_t { ... } ::gyro_z_high
Definition at line 428 of file mpu6050.h.
gyro_z_high [2/4]
uint8_t mpu6050_raw_t::gyro_z_high
Definition at line 428 of file mpu6050.h.
Referenced by mpu6050_uart_print_raw_Gyroscope().
[3/4]
uint8_t { ... } ::gyro_z_high
Definition at line 497 of file mpu6050.h.
gyro_z_high [4/4]
uint8_t mpu6050_big_gyro_t::gyro_z_high
Definition at line 497 of file mpu6050.h.
[1/4]
uint8_t { ... } ::gyro_z_low
Definition at line 429 of file mpu6050.h.
gyro_z_low [2/4]
uint8_t mpu6050_raw_t::gyro_z_low
Definition at line 429 of file mpu6050.h.
Referenced by mpu6050_uart_print_raw_Gyroscope().
gyro_z_low [3/4]
uint8_t mpu6050_big_gyro_t::gyro_z_low
Definition at line 498 of file mpu6050.h.
[4/4]
uint8_t { ... } ::gyro_z_low
Definition at line 498 of file mpu6050.h.
Gyroscope_X
int16_t MPU6050_t::Gyroscope_X
Gyroscope value X axis.
Definition at line 445 of file mpu6050.h.
Referenced by mpu6050_clear_All(), mpu6050_clear_Gyroscope(), mpu6050_read_All(), mpu6050_read_Gyroscope(), and mpu6050_uart_print_Gyroscope().
Gyroscope_Y
int16_t MPU6050_t::Gyroscope_Y
Gyroscope value Y axis.
Definition at line 446 of file mpu6050.h.
Referenced by mpu6050_clear_All(), mpu6050_clear_Gyroscope(), mpu6050_read_All(), mpu6050_read_Gyroscope(), and mpu6050_uart_print_Gyroscope().
Gyroscope_Z
int16_t MPU6050_t::Gyroscope_Z
Gyroscope value Z axis.
Definition at line 447 of file mpu6050.h.
Referenced by mpu6050_clear_All(), mpu6050_clear_Gyroscope(), mpu6050_read_All(), mpu6050_read_Gyroscope(), and mpu6050_uart_print_Gyroscope().
[1/2]
uint8_t { ... } ::Master
Master interrupt.
Not enabled with library
Definition at line 385 of file mpu6050.h.
Master [2/2]
uint8_t MPU6050_Interrupt_t::Master
Master interrupt.
Not enabled with library
Definition at line 385 of file mpu6050.h.
[1/2]
uint8_t { ... } ::MotionDetection
Motion detected interrupt.
Definition at line 388 of file mpu6050.h.
MotionDetection [2/2]
uint8_t MPU6050_Interrupt_t::MotionDetection
Motion detected interrupt.
Definition at line 388 of file mpu6050.h.
reserved0 [1/2]
uint8_t MPU6050_Interrupt_t::reserved0
Reserved bit.
Definition at line 389 of file mpu6050.h.
[2/2]
uint8_t { ... } ::reserved0
Reserved bit.
Definition at line 389 of file mpu6050.h.
reserved1 [1/2]
uint8_t MPU6050_Interrupt_t::reserved1
Reserved bit.
Definition at line 387 of file mpu6050.h.
[2/2]
uint8_t { ... } ::reserved1
Reserved bit.
Definition at line 387 of file mpu6050.h.
reserved2 [1/2]
uint8_t MPU6050_Interrupt_t::reserved2
Reserved bits.
Definition at line 384 of file mpu6050.h.
[2/2]
uint8_t { ... } ::reserved2
Reserved bits.
Definition at line 384 of file mpu6050.h.
Status
uint8_t MPU6050_Interrupt_t::Status
Definition at line 380 of file mpu6050.h.
Referenced by mpu6050_read_Interrupts().
[1/4]
uint8_t { ... } ::temp_high
Definition at line 421 of file mpu6050.h.
temp_high [2/4]
uint8_t mpu6050_raw_t::temp_high
Definition at line 421 of file mpu6050.h.
Referenced by mpu6050_clear_Temperature(), and mpu6050_uart_print_raw_Temperature().
temp_high [3/4]
uint8_t mpu6050_big_temp_t::temp_high
Definition at line 508 of file mpu6050.h.
[4/4]
uint8_t { ... } ::temp_high
Definition at line 508 of file mpu6050.h.
temp_low [1/4]
uint8_t mpu6050_raw_t::temp_low
Definition at line 422 of file mpu6050.h.
Referenced by mpu6050_clear_Temperature(), and mpu6050_uart_print_raw_Temperature().
[2/4]
uint8_t { ... } ::temp_low
Definition at line 422 of file mpu6050.h.
temp_low [3/4]
uint8_t mpu6050_big_temp_t::temp_low
Definition at line 509 of file mpu6050.h.
[4/4]
uint8_t { ... } ::temp_low
Definition at line 509 of file mpu6050.h.
Temperature
float MPU6050_t::Temperature
Temperature in degrees.
Definition at line 448 of file mpu6050.h.
Referenced by mpu6050_clear_All(), mpu6050_clear_Temperature(), mpu6050_read_All(), mpu6050_read_Temperature(), and mpu6050_uart_print_Temperature().
val
uint16_t mpu6050_big_temp_t::val
Definition at line 506 of file mpu6050.h.