STM32F103_IMU6050App: i2c/i2c-std.h File Reference
i2c-std.h File Reference
Macros
#define I2C_MAX_BUSY_TIME 3500
i2c-std.h
#define I2C_MAX_WAIT_TIME 3500
#define I2C_TIMEOUT_FLAG 3500U
Timeout 35 ms
#define I2C_TIMEOUT_BUSY_FLAG 2500U
Timeout 25 ms
#define I2C_TIMEOUT_STOP_FLAG 50U
Timeout 5 ms
#define I2C_AR_ADD 0x01
#define I2C_7BIT_ADD_WRITE(ADDRESS) ((uint8_t) ((ADDRESS) & (uint8_t) (~I2C_AR_ADD)))
#define I2C_7BIT_ADD_READ(ADDRESS) ((uint8_t) ((ADDRESS) | (uint8_t) (I2C_AR_ADD)))
#define I2C_ERROR_BERR 0x00000001U
BERR error
#define I2C_ERROR_ARLO 0x00000002U
ARLO error
#define I2C_ERROR_AF 0x00000004U
AF error
#define HAL_I2C_ERROR_OVR 0x00000008U
OVR error
#define HAL_I2C_ERROR_DMA 0x00000010U
DMA transfer error
#define HAL_I2C_ERROR_TIMEOUT 0x00000020U
Timeout Error
#define HAL_I2C_ERROR_SIZE 0x00000040U
Size Management error.
#define HAL_I2C_ERROR_DMA_PARAM 0x00000080U
DMA Parameter Error
#define HAL_I2C_WRONG_START 0x00000200U
Wrong start Error
#define UNUSED(tmpreg) (void)(tmpreg)
#define I2C_FLAG_MASK 0x0000FFFFU
#define _I2C_GET_FLAG(I2Cx, __FLAG__)
#define _I2C_CLEAR_FLAG(I2Cx, __FLAG__) (I2Cx->SR1 = ~((__FLAG__) & I2C_FLAG_MASK))
Clears the I2C pending flags which are cleared by writing 0 in a specific bit.
#define _I2C_CLEAR_ADDRFLAG(I2Cx)
Clears the I2C ADDR pending flag.
#define _I2C_CLEAR_STOPFLAG(I2Cx)
Clears the I2C STOPF pending flag.
#define _I2C_ENABLE(I2Cx) SET_BIT(I2Cx->CR1, I2C_CR1_PE)
Enable the specified I2C peripheral.
#define _I2C_DISABLE(I2Cx) CLEAR_BIT(I2Cx->CR1, I2C_CR1_PE)
Disable the specified I2C peripheral.
Enumerations
enum I2C_ERROR_TYPE {
I2C_OK =0x00U , I2C_TIMEOUT = 0x0A , I2C_BUSY_ERROR =0x01 , I2C_START_ERROR =0x02 ,
I2C_STOP_ERROR =0x03 , I2C_NACK_ERROR =0x04 , I2C_TX_BTF_ERROR =0x05 , I2C_TX_TXE_ERROR =0x06 ,
I2C_RX_RXNE_ERROR =0x07 , I2C_RX_BTF_ERROR =0x08 , I2C_ERROR =0x09U
}
Functions
void i2c_init_std (I2C_TypeDef *I2CX, uint32_t clock_speed, uint16_t ownaddress)
uint8_t i2c_write_7bit_byte_std (I2C_TypeDef *I2CX, uint8_t slave_address, uint8_t data)
uint8_t i2c_write_7bit_nbyte_std (I2C_TypeDef *I2CX, uint8_t slave_address, uint8_t *buf, size_t n)
uint8_t i2c_read_7bit_byte_std (I2C_TypeDef *I2CX, uint8_t slave_address, uint8_t *data)
uint8_t i2c_read_7bit_word_std (I2C_TypeDef *I2CX, uint8_t slave_address, uint16_t *data)
uint8_t i2c_read_7bit_nbyte_std (I2C_TypeDef *I2CX, uint8_t slave_address, uint8_t *buf, size_t n)
uint8_t i2c_write_7bit_base_byte_std (I2C_TypeDef *I2CX, uint8_t slave_address, uint8_t base_address, uint8_t data)
uint8_t i2c_write_7bit_base_nbyte_std (I2C_TypeDef *I2CX, uint8_t slave_address, uint8_t base_address, uint8_t *buf, size_t n)
uint8_t i2c_read_7bit_base_byte_std (I2C_TypeDef *I2CX, uint8_t slave_address, uint8_t base_address, uint8_t *data)
uint8_t i2c_read_7bit_base_word_std (I2C_TypeDef *I2CX, uint8_t slave_address, uint8_t base_address, uint16_t *data)
uint8_t i2c_read_7bit_base_nbyte_std (I2C_TypeDef *I2CX, uint8_t slave_address, uint8_t base_address, uint8_t *buf, size_t n)
Variables
volatile uint32_t I2Cx_Timeout
Macro Definition Documentation
_I2C_CLEAR_ADDRFLAG
#define _I2C_CLEAR_ADDRFLAG (I2Cx)
Value:
do{                                  \
    __IO uint32_t tmpreg = 0x00U;    \
    tmpreg = I2Cx->SR1;              \
    tmpreg = I2Cx->SR2;              \
    UNUSED(tmpreg);                  \
  } while(0)
Clears the I2C ADDR pending flag.
Parameters
__HANDLE__ specifies the I2C Handle. This parameter can be I2C where x: 1, 2, or 3 to select the I2C peripheral.
Return values
None
Definition at line 110 of file i2c-std.h.
_I2C_CLEAR_FLAG
#define _I2C_CLEAR_FLAG (I2Cx, __FLAG__) (I2Cx->SR1 = ~((__FLAG__) & I2C_FLAG_MASK))
Clears the I2C pending flags which are cleared by writing 0 in a specific bit.
Parameters
I2Cx specifies the I2C Handle.
__FLAG__ specifies the flag to clear. This parameter can be any combination of the following values:
I2C_FLAG_OVR: Overrun/Underrun flag (Slave mode)
I2C_FLAG_AF: Acknowledge failure flag
I2C_FLAG_ARLO: Arbitration lost flag (Master mode)
I2C_FLAG_BERR: Bus error flag
Return values
None
Definition at line 103 of file i2c-std.h.
_I2C_CLEAR_STOPFLAG
#define _I2C_CLEAR_STOPFLAG (I2Cx)
Value:
do{                                     \
    __IO uint32_t tmpreg = 0x00U;       \
    tmpreg = I2Cx->SR1;                 \
    SET_BIT(I2Cx->CR1, I2C_CR1_PE);     \
    UNUSED(tmpreg);                      \
  } while(0)
Clears the I2C STOPF pending flag.
Parameters
I2Cx specifies the I2C Handle.
Return values
None
Definition at line 122 of file i2c-std.h.
_I2C_DISABLE
#define _I2C_DISABLE (I2Cx) CLEAR_BIT(I2Cx->CR1, I2C_CR1_PE)
Disable the specified I2C peripheral.
Parameters
I2Cx specifies the I2C Handle.
Return values
None
Definition at line 140 of file i2c-std.h.
_I2C_ENABLE
#define _I2C_ENABLE (I2Cx) SET_BIT(I2Cx->CR1, I2C_CR1_PE)
Enable the specified I2C peripheral.
Parameters
I2Cx specifies the I2C Handle.
Return values
None
Definition at line 134 of file i2c-std.h.
_I2C_GET_FLAG
#define _I2C_GET_FLAG (I2Cx, __FLAG__)
Value:
                                      ((((uint8_t)((__FLAG__) >> 16U)) == 0x01U) ? \
                                      (((((I2Cx)->SR1) & ((__FLAG__) & I2C_FLAG_MASK)) == ((__FLAG__) & I2C_FLAG_MASK)) ? SET : RESET) : \
                                      (((((I2Cx)->SR2) & ((__FLAG__) & I2C_FLAG_MASK)) == ((__FLAG__) & I2C_FLAG_MASK)) ? SET : RESET))
Definition at line 89 of file i2c-std.h.
HAL_I2C_ERROR_DMA
#define HAL_I2C_ERROR_DMA 0x00000010U
DMA transfer error
Definition at line 53 of file i2c-std.h.
HAL_I2C_ERROR_DMA_PARAM
#define HAL_I2C_ERROR_DMA_PARAM 0x00000080U
DMA Parameter Error
Definition at line 56 of file i2c-std.h.
HAL_I2C_ERROR_OVR
#define HAL_I2C_ERROR_OVR 0x00000008U
OVR error
Definition at line 52 of file i2c-std.h.
HAL_I2C_ERROR_SIZE
#define HAL_I2C_ERROR_SIZE 0x00000040U
Size Management error.
Definition at line 55 of file i2c-std.h.
HAL_I2C_ERROR_TIMEOUT
#define HAL_I2C_ERROR_TIMEOUT 0x00000020U
Timeout Error
Definition at line 54 of file i2c-std.h.
HAL_I2C_WRONG_START
#define HAL_I2C_WRONG_START 0x00000200U
Wrong start Error
Definition at line 57 of file i2c-std.h.
I2C_7BIT_ADD_READ
#define I2C_7BIT_ADD_READ (ADDRESS) ((uint8_t) ((ADDRESS) | (uint8_t) (I2C_AR_ADD)))
Definition at line 39 of file i2c-std.h.
I2C_7BIT_ADD_WRITE
#define I2C_7BIT_ADD_WRITE (ADDRESS) ((uint8_t) ((ADDRESS) & (uint8_t) (~I2C_AR_ADD)))
Definition at line 38 of file i2c-std.h.
I2C_AR_ADD
#define I2C_AR_ADD 0x01
Definition at line 37 of file i2c-std.h.
I2C_ERROR_AF
#define I2C_ERROR_AF 0x00000004U
AF error
Definition at line 51 of file i2c-std.h.
I2C_ERROR_ARLO
#define I2C_ERROR_ARLO 0x00000002U
ARLO error
Definition at line 50 of file i2c-std.h.
I2C_ERROR_BERR
#define I2C_ERROR_BERR 0x00000001U
BERR error
Definition at line 49 of file i2c-std.h.
I2C_FLAG_MASK
#define I2C_FLAG_MASK 0x0000FFFFU
Definition at line 87 of file i2c-std.h.
I2C_MAX_BUSY_TIME
#define I2C_MAX_BUSY_TIME 3500
i2c-std.h
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Definition at line 26 of file i2c-std.h.
I2C_MAX_WAIT_TIME
#define I2C_MAX_WAIT_TIME 3500
Definition at line 27 of file i2c-std.h.
I2C_TIMEOUT_BUSY_FLAG
#define I2C_TIMEOUT_BUSY_FLAG 2500U
Timeout 25 ms
Definition at line 30 of file i2c-std.h.
I2C_TIMEOUT_FLAG
#define I2C_TIMEOUT_FLAG 3500U
Timeout 35 ms
Definition at line 29 of file i2c-std.h.
I2C_TIMEOUT_STOP_FLAG
#define I2C_TIMEOUT_STOP_FLAG 50U
Timeout 5 ms
Definition at line 31 of file i2c-std.h.
UNUSED
#define UNUSED (tmpreg) (void)(tmpreg)
Definition at line 86 of file i2c-std.h.
Enumeration Type Documentation
I2C_ERROR_TYPE
enum I2C_ERROR_TYPE
Enumerator
I2C_OK
I2C_TIMEOUT
I2C_BUSY_ERROR
I2C_START_ERROR
I2C_STOP_ERROR
I2C_NACK_ERROR
I2C_TX_BTF_ERROR
I2C_TX_TXE_ERROR
I2C_RX_RXNE_ERROR
I2C_RX_BTF_ERROR
I2C_ERROR
Definition at line 59 of file i2c-std.h.
{
I2C_OK                =0x00U,
I2C_TIMEOUT           = 0x0A,
//I2C_ERROR           =0x01U,
//I2C_BUSY             =0x02U,
I2C_BUSY_ERROR         =0x01,
I2C_START_ERROR        =0x02,
I2C_STOP_ERROR         =0x03,
I2C_NACK_ERROR         =0x04,
I2C_TX_BTF_ERROR        =0x05,
I2C_TX_TXE_ERROR        =0x06,
I2C_RX_RXNE_ERROR       =0x07,
I2C_RX_BTF_ERROR        =0x08,
I2C_ERROR               =0x09U,
}I2C_ERROR_TYPE;
Function Documentation
i2c_init_std()
void i2c_init_std (I2C_TypeDef * I2CX, uint32_t clock_speed, uint16_t ownaddress)
Definition at line 881 of file i2c-std.c.
{
    GPIO_InitTypeDef _gpio_init_struct;
    I2C_InitTypeDef _i2c_init_struct;
 /*1. Enable the Clock  the AFIO/GPIO Modules using RCC_APB2PeriphClockCmd*/
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO| RCC_APB2Periph_GPIOB,ENABLE);
 /* 1.,2. Enable the Clock  the I2Cx Modules  and its GPIO pins mode */
    if(I2CX==I2C1)
    {
    /*Enable the Clock  the AFIO/GPIO Modules using RCC_APB2PeriphClockCmd*/
     RCC_APB1PeriphClockCmd(RCC_APB1Periph_I2C1,ENABLE);
    /* Configure the pins required by the Module (AFIO_OUT or INPUT, ANALOG...) & remap incase of requirement */
      GPIO_StructInit((GPIO_InitTypeDef*)& _gpio_init_struct);
      // I2C1_SCL=PB6,I2C1_SDA=PB7
     _gpio_init_struct.GPIO_Pin=GPIO_Pin_6 | GPIO_Pin_7;
     _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
     _gpio_init_struct.GPIO_Mode=GPIO_Mode_AF_OD;
      GPIO_Init(GPIOB,&_gpio_init_struct);
    /* I2C1 Hardware reset/set of the module */
     RCC_APB1PeriphResetCmd(RCC_APB1Periph_I2C1,ENABLE);
     RCC_APB1PeriphResetCmd(RCC_APB1Periph_I2C1,DISABLE);
    }
    else
    { //I2C2
            /*Enable the Clock  the AFIO/GPIO Modules using RCC_APB2PeriphClockCmd*/
     RCC_APB1PeriphClockCmd(RCC_APB1Periph_I2C2,ENABLE);
    /* Configure the pins required by the Module (AFIO_OUT or INPUT, ANALOG...) & remap incase of requirement */
      GPIO_StructInit((GPIO_InitTypeDef*)& _gpio_init_struct);
      // I2C2_SCL=PB10,I2C2_SDA=PB11
     _gpio_init_struct.GPIO_Pin=GPIO_Pin_10 | GPIO_Pin_11;
     _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
     _gpio_init_struct.GPIO_Mode=GPIO_Mode_AF_OD;
      GPIO_Init(GPIOB,&_gpio_init_struct);
    /* I2C2 Hardware reset/set of the module */
     RCC_APB1PeriphResetCmd(RCC_APB1Periph_I2C2,ENABLE);
     RCC_APB1PeriphResetCmd(RCC_APB1Periph_I2C2,DISABLE);
    }
  /* 3. Configure the peripheral hardware interrupt @ level of  NVIC  link to IRQ and set priority */
  /*   NVIC_InitTypeDef NVIC_InitStruct;
     NVIC_InitStruct.NVIC_IRQChannel=I2C1_EV_IRQn;
     NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority=0;
     NVIC_InitStruct.NVIC_IRQChannelSubPriority=9;
     NVIC_InitStruct.NVIC_IRQChannelCmd=ENABLE;
     NVIC_Init((NVIC_InitTypeDef*) &NVIC_InitStruct);
  */
/* 4.  the peripheral hardware  of the I2C */
    I2C_StructInit((I2C_InitTypeDef *)& _i2c_init_struct);
    _i2c_init_struct.I2C_Mode=I2C_Mode_I2C ;
    _i2c_init_struct.I2C_DutyCycle=I2C_DutyCycle_2;
    _i2c_init_struct.I2C_Ack=I2C_Ack_Enable;
    _i2c_init_struct.I2C_AcknowledgedAddress=I2C_AcknowledgedAddress_7bit ;
    _i2c_init_struct. I2C_OwnAddress1=ownaddress;
    _i2c_init_struct.I2C_ClockSpeed=clock_speed;
    // reset the I2C Module
    I2CX->CR1|=I2C_CR1_SWRST;
    I2CX->CR1&=~I2C_CR1_SWRST;
    I2C_Init((I2C_TypeDef*)I2CX,(I2C_InitTypeDef *)& _i2c_init_struct);
    //I2CX->TRISE=37;
  /* 5. Configure the peripheral interrupt @ level of the peripheral or DMA */
    //I2C_ITConfig(I2C1, I2C_IT_EVT| I2C_IT_EVT,ENABLE);
  /* 6. Enable the peripheral Module */
    //I2C_Cmd((I2C_TypeDef*)I2CX,ENABLE);
    I2CX->CR1|=I2C_CR1_PE;
}
Referenced by mpu6050_task(), and system_init().
i2c_read_7bit_base_byte_std()
uint8_t i2c_read_7bit_base_byte_std (I2C_TypeDef * I2CX, uint8_t slave_address, uint8_t base_address, uint8_t * data)
Definition at line 1157 of file i2c-std.c.
{
  uint8_t error=0;
   error=i2c_read_7bit_base_nbyte_std(I2CX,slave_address,base_address,(uint8_t *)data, 1);
   //uart_print(USART1,"RX DATA:");
   //uart_print_integer(USART1,*data,16);
   //uart_print(USART1,"\r\n");
  if(error!=I2C_OK)
   return error;
  return I2C_OK;
  /*
  // get the error of the any sub operation where a non-zero value indicate an error
  uint8_t error=0;
 //wait check that the I2c module is not busy
    uart_print(USART1,"\nRX_BuSY ...\r\n");
    error=i2c_ready_std(I2CX);
    if(error)//(error=i2c_ready_std(I2CX)))
      return error;
  // send the start condition
//    uart_print(USART1,"start condition:");
    uart_print(USART1,"RX_SB ...\r\n");
    error=i2c_start_std(I2CX);
    if(error)//(error=i2c_start_std(I2CX)))
        return error;
    uart_print(USART1,"RX_SLAVE_ADDR ...\r\n");
    //EV5: send the slave address with write operation master transmit
    error=i2c_send_7bit_slave_address_wr_std(I2CX,slave_address);
    if(error)//(error=i2c_send_7bit_slave_address_wr_std(I2CX,slave_address)))
        return error;
//    uart_print(USART1,"REG:");
    uart_print(USART1,"RX_REG_DATA ...\r\n");
    //Ev6: send the base byte
    error=i2c_write_byte_std(I2CX,base_address);
    if(error)//(error=i2c_write_byte_std(I2CX,base_address)))
      return error;
  // send the repeat start condition
    uart_print(USART1,"repeat start....\r\n");
    error=i2c_start_std(I2CX);
    if(error)//(error=i2c_start_std(I2CX)))
        return error;
 // Enable Acknowledgment , clear POS flag
    I2C_AcknowledgeConfig(I2CX , ENABLE);
    I2C_NACKPositionConfig(I2CX , I2C_NACKPosition_Current);
 //EV5: send the slave address with read operation master transmit
    uart_print(USART1,"RX_ Slave RD: \r\n");
    error=i2c_send_7bit_slave_address_rd_std(I2CX,slave_address);
    if(error)//(error=i2c_send_7bit_slave_address_rd_std(I2CX,slave_address)))
      return error;
     (void)I2CX->SR1;
     (void)I2CX->SR2;
    uart_print(USART1,"RX_DATA:");
    error=i2c_read_lastbyte_std(I2CX,data);
    uart_print_integer(USART1,*data,16);
    uart_print(USART1,"\r\n");
   if(error)//(error=i2c_read_lastbyte_std(I2CX,data)))
    return error;
  // generate the stop condition : note stop generation is done implicitly by the
    uart_print(USART1,"RX_STOP :\r\n");
    error=i2c_stop_std(I2CX);
    if(error)//(error=i2c_stop_std(I2CX)))// if((error=i2c_wait_stop_event_std(I2CX)))
      return error;
  // all operation has succeeded no error to return
    return I2C_OK;
    */
}
References I2C_OK, and i2c_read_7bit_base_nbyte_std().
Referenced by mpu6050_enableCycle(), mpu6050_EnableInterrupts(), mpu6050_enableSleep(), mpu6050_get_hpf(), mpu6050_get_lpf(), mpu6050_getAccelRange(), mpu6050_getClock(), mpu6050_getCycleRate(), mpu6050_getFsyncSampleOutput(), mpu6050_getGyroRange(), mpu6050_read_Interrupts(), mpu6050_read_reg(), mpu6050_set_hpf(), mpu6050_set_lpf(), mpu6050_setAccelerometerStandby(), mpu6050_setAccelRange(), mpu6050_setCycleRate(), mpu6050_setGyroRange(), mpu6050_setGyroStandby(), mpu6050_setI2CBypass(), mpu6050_setTemperatureStandby(), and mpu6050_task().
i2c_read_7bit_base_nbyte_std()
uint8_t i2c_read_7bit_base_nbyte_std (I2C_TypeDef * I2CX, uint8_t slave_address, uint8_t base_address, uint8_t * buf, size_t n)
Definition at line 1288 of file i2c-std.c.
{
  // get the error of the any sub operation where a non-zero value indicate an error
  uint8_t error=0;
 //wait check that the I2c module is not busy
  //wait check that the I2c module is not busy
    //uart_print(USART1,"\nRX_BuSY ...\r\n");
    if((error=i2c_ready_std(I2CX)))
        return error;
   /* Enable I2C peripheral */
     //SET_BIT(I2CX->CR1, I2C_CR1_PE);               // done
   /* Disable Pos */
     //CLEAR_BIT(I2CX->CR1, I2C_CR1_POS);            // done
   /* Enable Acknowledge */
     //SET_BIT(I2CX->CR1, I2C_CR1_ACK);    // done
    /* Generate Start */
     //SET_BIT(I2CX->CR1, I2C_CR1_START);  // done
  // send the start condition
    //uart_print(USART1,"RX_SB ...\r\n");
    error=i2c_start_std(I2CX);
    if(error)
        return error;
    //EV5: send the slave address with write operation master transmit
    //uart_print(USART1,"RX_SLAVE_ADDR_WR ...\r\n");
    error=i2c_send_7bit_slave_address_wr_std(I2CX,slave_address);
    if(error)
        return error;
    //Ev6: send the base byte
    //uart_print(USART1,"RX_REG_DATA ...\r\n");
    error=i2c_write_byte_std(I2CX,base_address);
    if(error)
        return error;
  // send the repeat start condition
    //uart_print(USART1,"repeat start....\r\n");
    error=i2c_start_std(I2CX);
    if(error)
        return error;
 // Enable Acknowledgment , clear POS flag
     //I2C_AcknowledgeConfig(I2CX , ENABLE);
     //I2C_NACKPositionConfig(I2CX , I2C_NACKPosition_Current);
//EV5: send the slave address with a read operation master transmit
    //uart_print(USART1,"RX_ SLAVE_ADDR_RD... \r\n");
    error=i2c_send_7bit_slave_address_rd_std(I2CX,slave_address);
    if(error)
      return error;
//EV7:
    //uart_print(USART1,"DATA RD .... \r\n");
    error=i2c_read_nbyte_std(I2CX,buf,n);
   if(error)
    return error;
// generate the stop condition : note stop generation is done implicitly by the
    //uart_print(USART1,"Stop Condition: \r\n");
   if((error=i2c_wait_stop_event_std(I2CX)))
    return error;
    // all operation has succeeded no error to return
    return I2C_OK;
}
References I2C_OK, i2c_read_nbyte_std(), i2c_ready_std(), i2c_send_7bit_slave_address_rd_std(), i2c_send_7bit_slave_address_wr_std(), i2c_start_std(), i2c_wait_stop_event_std(), and i2c_write_byte_std().
Referenced by i2c_read_7bit_base_byte_std(), i2c_read_7bit_base_word_std(), mpu6050_read_Accelerometer(), mpu6050_read_All(), mpu6050_read_Gyroscope(), and mpu6050_read_Temperature().
i2c_read_7bit_base_word_std()
uint8_t i2c_read_7bit_base_word_std (I2C_TypeDef * I2CX, uint8_t slave_address, uint8_t base_address, uint16_t * data)
Definition at line 1235 of file i2c-std.c.
{
  uint8_t error=0;
  WORD_BYTES t;
   t.word=0;
  if((error=i2c_read_7bit_base_nbyte_std(I2CX,slave_address,base_address,(uint8_t *)t.bytes, 2)))
    return error;
   *data=t.word;
  return I2C_OK;
  /*
  // get the error of the any sub operation where a non-zero value indicate an error
  uint8_t error=0;
  uint8_t buf[2];
 //wait check that the I2c module is not busy
    if((error=i2c_ready_std(I2CX)))
        return error;
  // send the start condition  (wait for EV5) as the end of start condition
    if((error=i2c_start_std(I2CX)))
        return error;
    //EV5: send the slave address with write operation master transmit
    if((error=i2c_send_7bit_slave_address_wr_std(I2CX,slave_address)))
        return error;
    //Ev6: send the base byte
    if((error=i2c_write_byte_std(I2CX,base_address)))
        return error;
  // send the repeat start condition
    if((error=i2c_start_std(I2CX)))
        return error;
 // Enable Acknowledgment , clear POS flag
     I2C_AcknowledgeConfig(I2CX , ENABLE);
     I2C_NACKPositionConfig(I2CX, I2C_NACKPosition_Current);
//EV5: send the slave address with read operation master transmit
    if((error=i2c_send_7bit_slave_address_rd_std(I2CX,slave_address)))
        return error;
   if((error=i2c_read_last2byte_std(I2CX,buf)))
    return error;
    *data=(uint16_t)(buf[1]<<8 | buf[0]);
    // generate the stop condition : note stop generation is done implicitly by the
    if((error=i2c_wait_stop_event_std(I2CX)))
        return error;
    // all operation has succeeded no error to return
    return I2C_OK;
    */
}
References WORD_BYTES::bytes, I2C_OK, i2c_read_7bit_base_nbyte_std(), and WORD_BYTES::word.
i2c_read_7bit_byte_std()
uint8_t i2c_read_7bit_byte_std (I2C_TypeDef * I2CX, uint8_t slave_address, uint8_t * data)
Definition at line 1018 of file i2c-std.c.
{
  uint8_t error=0;
  if((error=i2c_read_7bit_nbyte_std(I2CX,slave_address, (uint8_t *)data, 1)))
   return error;
  return I2C_OK;
}
References I2C_OK, and i2c_read_7bit_nbyte_std().
i2c_read_7bit_nbyte_std()
uint8_t i2c_read_7bit_nbyte_std (I2C_TypeDef * I2CX, uint8_t slave_address, uint8_t * buf, size_t n)
Definition at line 1039 of file i2c-std.c.
{
  // get the error of the any sub operation where a non-zero value indicate an error
  uint8_t error=0;
 //wait check that the I2c module is not busy
    if((error=i2c_ready_std(I2CX)))
        return error;
  // send the repeat start condition
    if((error=i2c_start_std(I2CX)))
        return error;
 // Enable Acknowledgment , clear POS flag
     I2C_AcknowledgeConfig(I2CX , ENABLE);
     I2C_NACKPositionConfig(I2CX , I2C_NACKPosition_Current);
//EV5: send the slave address with a read operation master transmit
    if((error=i2c_send_7bit_slave_address_rd_std(I2CX,slave_address)))
        return error;
//EV7:
   if((error=i2c_read_nbyte_std(I2CX,buf,n)))
    return error;
// generate the stop condition : note stop generation is done implicitly by the
   if((error=i2c_wait_stop_event_std(I2CX)))
      return error;
    // all operation has succeeded no error to return
    return I2C_OK;
}
References I2C_OK, i2c_read_nbyte_std(), i2c_ready_std(), i2c_send_7bit_slave_address_rd_std(), i2c_start_std(), and i2c_wait_stop_event_std().
Referenced by i2c_read_7bit_byte_std(), and i2c_read_7bit_word_std().
i2c_read_7bit_word_std()
uint8_t i2c_read_7bit_word_std (I2C_TypeDef * I2CX, uint8_t slave_address, uint16_t * data)
Definition at line 1028 of file i2c-std.c.
{
  uint8_t error=0;
  WORD_BYTES t;
  t.word=0;
  if((error=i2c_read_7bit_nbyte_std(I2CX,slave_address, (uint8_t *)t.bytes, 2)))
   return error;
  *data=t.word;
  return I2C_OK;
}
References WORD_BYTES::bytes, I2C_OK, i2c_read_7bit_nbyte_std(), and WORD_BYTES::word.
i2c_write_7bit_base_byte_std()
uint8_t i2c_write_7bit_base_byte_std (I2C_TypeDef * I2CX, uint8_t slave_address, uint8_t base_address, uint8_t data)
Definition at line 1078 of file i2c-std.c.
{
 // get the result of any sub operation where a non-zero value indicates an error condition
    uint8_t error=0;
  //uart_print(USART1,"\nTX_BuSY ...\r\n");
  //wait check that the I2c module is not busy
    if((error=i2c_ready_std(I2CX)))
        return error;
  //uart_print(USART1,"TX_SB ...\r\n");
  // send the start condition
    if((error=i2c_start_std(I2CX)))
        return error;
   //uart_print(USART1,"TX_SLAVE_ADDR ...\r\n");
    //EV5: send the slave address with write operation master transmit
    if((error=i2c_send_7bit_slave_address_wr_std(I2CX,slave_address)))
        return error;
//      (void) I2CX ->SR1;
//      (void) I2CX ->SR2; // Clear ADDR flag
   //uart_print(USART1,"TX_BASE_ADDR ...\r\n");
    //Ev6: send the byte :: the base address in the slave Memory/register map to start writing to
    i2c_write_byte_std(I2CX,base_address);
    //if((error=i2c_write_byte_std(I2CX,base_address)))
    //    return error;
      //cbits(I2CX->SR1,I2C_SR1_AF);
   //uart_print(USART1,"TX_REG_DATA ...\r\n");
    //Ev6: send the byte
    i2c_write_byte_std(I2CX,data);
    //if((error=i2c_write_byte_std(I2CX,data)))
    //    return error;
     // cbits(I2CX->SR1,I2C_SR1_AF);
   //uart_print(USART1,"TX_STOP ...\r\n");
    // generate the stop condition
    i2c_stop_std(I2CX);
    if((error=i2c_stop_std(I2CX)))
        return error;
    return I2C_OK;
}
References I2C_OK, i2c_ready_std(), i2c_send_7bit_slave_address_wr_std(), i2c_start_std(), i2c_stop_std(), and i2c_write_byte_std().
Referenced by mpu6050_DisableInterrupts(), mpu6050_enableCycle(), mpu6050_EnableInterrupts(), mpu6050_enableSleep(), mpu6050_reset(), mpu6050_set_hpf(), mpu6050_set_lpf(), mpu6050_setAccelerometerStandby(), mpu6050_setAccelRange(), mpu6050_setCycleRate(), mpu6050_setDataRate(), mpu6050_setGyroRange(), mpu6050_setGyroStandby(), mpu6050_setI2CBypass(), mpu6050_setSampleRateDivisor(), and mpu6050_setTemperatureStandby().
i2c_write_7bit_base_nbyte_std()
uint8_t i2c_write_7bit_base_nbyte_std (I2C_TypeDef * I2CX, uint8_t slave_address, uint8_t base_address, uint8_t * buf, size_t n)
Definition at line 1124 of file i2c-std.c.
{
 // get the error of the any sub operation where a non-zero value indicate an error
  uint8_t error=0;
  //wait check that the I2c module is not busy
    if((error=i2c_ready_std(I2CX)))
        return error;
  // send the start condition
    if((error=i2c_start_std(I2CX)))
        return error;
    //EV5: send the slave address with write operation master transmit
    if((error=i2c_send_7bit_slave_address_wr_std(I2CX,slave_address)))
        return error;
    //Ev6: send the byte :: the base address in the slave Memory/register map to start writing to
    if((error=i2c_write_byte_std(I2CX,base_address)))
        return error;
    //Ev6: send the byte
    if((error=i2c_write_nbyte_std(I2CX,buf,n)))
        return error;
    // generate the stop condition
    if((error=i2c_stop_std(I2CX)))
        return error;
    // all operation has succeeded no error to return
    return 0;
}
References i2c_ready_std(), i2c_send_7bit_slave_address_wr_std(), i2c_start_std(), i2c_stop_std(), i2c_write_byte_std(), and i2c_write_nbyte_std().
i2c_write_7bit_byte_std()
uint8_t i2c_write_7bit_byte_std (I2C_TypeDef * I2CX, uint8_t slave_address, uint8_t data)
Definition at line 962 of file i2c-std.c.
{
 // get the result of any sub operation where a non-zero value indicates an error condition
    uint8_t error=0;
  //wait check that the I2c module is not busy
    if((error=i2c_ready_std(I2CX)))
        return error;
  // send the start condition
    if((error=i2c_start_std(I2CX)))
        return error;
    //EV5: send the slave address with write operation master transmit
    if((error=i2c_send_7bit_slave_address_wr_std(I2CX,slave_address)))
        return error;
    //Ev6: send the byte
    if((error=i2c_write_byte_std(I2CX,data)))
        return error;
    // generate the stop condition
    if((error=i2c_stop_std(I2CX)))
        return error;
    return I2C_OK;
}
References I2C_OK, i2c_ready_std(), i2c_send_7bit_slave_address_wr_std(), i2c_start_std(), i2c_stop_std(), and i2c_write_byte_std().
i2c_write_7bit_nbyte_std()
uint8_t i2c_write_7bit_nbyte_std (I2C_TypeDef * I2CX, uint8_t slave_address, uint8_t * buf, size_t n)
Definition at line 990 of file i2c-std.c.
{
 // get the error of the any sub operation where a non-zero value indicate an error
  uint8_t error=0;
  //wait check that the I2c module is not busy
    if((error=i2c_ready_std(I2CX)))
        return error;
  // send the start condition
    if((error=i2c_start_std(I2CX)))
        return error;
    //EV5: send the slave address with write operation master transmit
    if((error=i2c_send_7bit_slave_address_wr_std(I2CX,slave_address)))
        return error;
    //Ev6: send the byte
    if((error=i2c_write_nbyte_std(I2CX,buf,n)))
        return error;
    // generate the stop condition
    if((error=i2c_stop_std(I2CX)))
        return error;
    // all operation has succeeded no error to return
    return 0;
}
References i2c_ready_std(), i2c_send_7bit_slave_address_wr_std(), i2c_start_std(), i2c_stop_std(), and i2c_write_nbyte_std().
Variable Documentation
I2Cx_Timeout
volatile uint32_t I2Cx_Timeout extern
Definition at line 51 of file i2c-std.c.
Referenced by i2c_read7_v1(), i2c_ready_std(), i2c_wait_7bit_slave_address_rd_std(), i2c_wait_7bit_slave_address_wr_std(), i2c_wait_read_byte_btf_std(), i2c_wait_read_byte_rxne_std(), i2c_wait_start_event_std(), i2c_wait_stop_event_std(), i2c_wait_write_byte_btf_std(), i2c_wait_write_byte_txe_std(), and i2c_write7_v1().