STM32F103_IMU6050App: i2c/i2c.h File Reference
i2c.h File Reference
#include "i2c-com.h"
#include "i2c-std.h"
Classes
union I2c_tx_byte_t
data structure Bit definition for I2C_OAR1 register
struct i2c_t
a gloabl variale define the I2C receive Ring Queue
Macros
#define I2C_WAIT_TIMEOUT 20000
i2c.h
#define I2C_DELIMITER_SIZE 4
#define I2C_HEADER_SIZE 4
#define I2C_BUFFER_SIZE 64
#define I2C_BUFFER_MASK (I2C_BUFFER_SIZE - 1)
#define I2C_MAX_RX_QUEUE_LEN 120
#define I2C_MAX_TX_QUEUE_LEN 120
#define I2C_MAX_FRAME_LEN 40
#define I2C_MAX_PAYLOAD_LEN (I2C_MAX_FRAME_LEN-I2C_LINK_HEADER_LEN)
#define I2C_PACKET_P 0x06
#define I2C_PAYLOAD_P 0x08
Enumerations
enum I2C_STATE {
_I2C_WAIT , _I2C_READ_BYTE , _I2C_READ_2BYTE , _I2C_READ_NBYTE ,
_I2C_WRITE_BYTE , _I2C_WRIE_NBYTE , _I2C_FAULT
}
enum I2C_WR_BYTE_STATE {
_I2C_WR_BYTE_WAIT_BUSY , _I2C_WR_BYTE_START_SEND , _I2C_WR_BYTE_START_WAIT , _I2C_WR_BYTE_SLAVE_WR ,
_I2C_WR_BYTE_SlAVE_WR_WAIT , _I2C_WR_BYTE_MASTER , _I2C_WR_BYTE_MASTER_WAIT , _I2C_WR_BYTE_STOP_SEND ,
_I2C_WR_BYTE_STOP_WAIT , _I2C_WR_BYTE_FAULT
}
enum I2C_WRITE_BYTE_STATE {
_I2C_WRITE_BYTE_WAIT_BUSY , _I2C_WRITE_BYTE_START_SEND , _I2C_WRITE_BYTE_START_WAIT , _I2C_WRITE_BYTE_SLAVE_WR ,
_I2C_WRITE_BYTE_SlAVE_WR_WAIT , _I2C_WRITE_BYTE_REG_AR , _I2C_WRITE_BYTE_REG_AR_WAIT , _I2C_WRITE_BYTE_MASTER ,
_I2C_WRITE_BYTE_MASTER_WAIT , _I2C_WRITE_BYTE_STOP_SEND , _I2C_WRITE_BYTE_STOP_WAIT , _I2C_WRITE_BYTE_FAULT
}
enum I2C_WRITE_NBYTE_STATE {
_I2C_WRITE_NBYTE_WAIT_BUSY , _I2C_WRITE_NBYTE_START_SEND , _I2C_WRITE_NBYTE_START_WAIT , _I2C_WRITE_NBYTE_SLAVE_WR ,
_I2C_WRITE_NBYTE_SlAVE_WR_WAIT , _I2C_WRITE_NBYTE_REG_AR , _I2C_WRITE_NBYTE_REG_AR_WAIT , _I2C_WRITE_NBYTE_MASTER ,
_I2C_WRITE_NBYTE_MASTER_WAIT , _I2C_WRITE_NBYTE_STOP_SEND , _I2C_WRITE_NBYTE_STOP_WAIT , _I2C_WRITE_NBYTE_FAULT
}
enum I2C_READ_BYTE_STATE {
_I2C_READ_BYTE_WAIT_BUSY , _I2C_READ_BYTE_START_SEND , _I2C_READ_BYTE_START_WAIT , _I2C_READ_BYTE_SLAVE_WR ,
_I2C_READ_BYTE_SlAVE_WR_WAIT , _I2C_READ_BYTE_REG_AR , _I2C_READ_BYTE_REG_AR_WAIT , _I2C_READ_BYTE_RESTART_SEND ,
_I2C_READ_BYTE_RESTART_WAIT , _I2C_READ_BYTE_SLAVE_RD , _I2C_READ_BYTE_SlAVE_RD_WAIT , _I2C_READ_BYTE_MASTER_RD ,
_I2C_READ_BYTE_MASTER_RD_WAIT , _I2C_READ_BYTE_STOP_SEND , _I2C_READ_BYTE_STOP_WAIT , _I2C_READ_BYTE_FAULT
}
enum I2C_READ_2BYTE_STATE {
_I2C_READ_2BYTE_WAIT_BUSY , _I2C_READ_2BYTE_START_SEND , _I2C_READ_2BYTE_START_WAIT , _I2C_READ_2BYTE_SLAVE_WR ,
_I2C_READ_2BYTE_SlAVE_WR_WAIT , _I2C_READ_2BYTE_REG_AR , _I2C_READ_2BYTE_REG_AR_WAIT , _I2C_READ_2BYTE_RESTART_SEND ,
_I2C_READ_2BYTE_RESTART_WAIT , _I2C_READ_2BYTE_SLAVE_RD , _I2C_READ_2BYTE_SlAVE_RD_WAIT , _I2C_READ_2BYTE_MASTER_RD ,
_I2C_READ_2BYTE_MASTER_RD_WAIT , _I2C_READ_2BYTE_STOP_SEND , _I2C_READ_2BYTE_STOP_WAIT , _I2C_READ_2BYTE_FAULT
}
enum I2C_READ_NBYTE_STATE {
_I2C_READ_NBYTE_WAIT_BUSY , _I2C_READ_NBYTE_START_SEND , _I2C_READ_NBYTE_START_WAIT , _I2C_READ_NBYTE_SLAVE_WR ,
_I2C_READ_NBYTE_SlAVE_WR_WAIT , _I2C_READ_NBYTE_REG_AR , _I2C_READ_NBYTE_REG_AR_WAIT , _I2C_READ_NBYTE_RESTART_SEND ,
_I2C_READ_NBYTE_RESTART_WAIT , _I2C_READ_NBYTE_SLAVE_RD , _I2C_READ_NBYTE_SlAVE_RD_WAIT , _I2C_READ_NBYTE_MASTER_RD ,
_I2C_READ_NBYTE_MASTER_RD_WAIT , _I2C_READ_NBYTE_MASTER_RD_N1 , _I2C_READ_NBYTE_MASTER_RD_N1_WAIT , _I2C_READ_NBYTE_STOP_SEND ,
_I2C_READ_NBYTE_STOP_WAIT , _I2C_READ_NBYTE_FAULT
}
Functions
void i2c1_init (uint32_t clock_speed, uint16_t ownaddress)
void i2c_init ()
void i2c_uart_print (USART_TypeDef *uart)
uint8_t i2c_start ()
initiate start condition
uint8_t i2_stop ()
initiate start condition
uint8_t i2c_send_byte (uint8_t data)
initiate stop condition
uint8_t i2c_send_sla_wr (uint8_t SLA_W)
send a byte via TWI bus
uint8_t i2c_send_sla_rd (uint8_t SLA_R)
send a slave with write operation via TWI bus
uint8_t i2c_write_data (uint8_t data)
send a slave with read operation via TWI bus
uint8_t i2c_read_data (uint8_t *data, uint8_t ack)
write data
Variables
i2c_t myi2c
I2C_TypeDef_t * i2cx
i2c.c
Macro Definition Documentation
I2C_BUFFER_MASK
#define I2C_BUFFER_MASK (I2C_BUFFER_SIZE - 1)
Definition at line 146 of file i2c.h.
I2C_BUFFER_SIZE
#define I2C_BUFFER_SIZE 64
Definition at line 145 of file i2c.h.
I2C_DELIMITER_SIZE
#define I2C_DELIMITER_SIZE 4
Definition at line 143 of file i2c.h.
I2C_HEADER_SIZE
#define I2C_HEADER_SIZE 4
Definition at line 144 of file i2c.h.
I2C_MAX_FRAME_LEN
#define I2C_MAX_FRAME_LEN 40
Definition at line 156 of file i2c.h.
I2C_MAX_PAYLOAD_LEN
#define I2C_MAX_PAYLOAD_LEN (I2C_MAX_FRAME_LEN-I2C_LINK_HEADER_LEN)
Definition at line 157 of file i2c.h.
I2C_MAX_RX_QUEUE_LEN
#define I2C_MAX_RX_QUEUE_LEN 120
Definition at line 153 of file i2c.h.
I2C_MAX_TX_QUEUE_LEN
#define I2C_MAX_TX_QUEUE_LEN 120
Definition at line 154 of file i2c.h.
I2C_PACKET_P
#define I2C_PACKET_P 0x06
Definition at line 159 of file i2c.h.
I2C_PAYLOAD_P
#define I2C_PAYLOAD_P 0x08
Definition at line 160 of file i2c.h.
I2C_WAIT_TIMEOUT
#define I2C_WAIT_TIMEOUT 20000
i2c.h
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Definition at line 24 of file i2c.h.
Enumeration Type Documentation
I2C_READ_2BYTE_STATE
enum I2C_READ_2BYTE_STATE
Enumerator
_I2C_READ_2BYTE_WAIT_BUSY
wait until the i2c Module is not busy any more
_I2C_READ_2BYTE_START_SEND
send start condition
_I2C_READ_2BYTE_START_WAIT
wait start condition to complete
_I2C_READ_2BYTE_SLAVE_WR
send slave address with write operation condition
_I2C_READ_2BYTE_SlAVE_WR_WAIT
wait slave to AK/NAK condition to complete
_I2C_READ_2BYTE_REG_AR
send base register address to slave define
_I2C_READ_2BYTE_REG_AR_WAIT
wait slave to AK/NAK condition to complete
_I2C_READ_2BYTE_RESTART_SEND
send a repeat start condition
_I2C_READ_2BYTE_RESTART_WAIT
wait start condition to complete
_I2C_READ_2BYTE_SLAVE_RD
send slave address with READ operation condition
_I2C_READ_2BYTE_SlAVE_RD_WAIT
wait slave to AK/NAK condition to complete
_I2C_READ_2BYTE_MASTER_RD
master read one byte from the slave with NAK condition
_I2C_READ_2BYTE_MASTER_RD_WAIT
wait master read operation finish NAK condition to complete
_I2C_READ_2BYTE_STOP_SEND
send stop condition
_I2C_READ_2BYTE_STOP_WAIT
wait stop condition to complete
_I2C_READ_2BYTE_FAULT
Definition at line 99 of file i2c.h.
{
 _I2C_READ_2BYTE_WAIT_BUSY,
 _I2C_READ_2BYTE_START_SEND,
 _I2C_READ_2BYTE_START_WAIT,
 _I2C_READ_2BYTE_SLAVE_WR,
 _I2C_READ_2BYTE_SlAVE_WR_WAIT,
 _I2C_READ_2BYTE_REG_AR,
 _I2C_READ_2BYTE_REG_AR_WAIT,
 _I2C_READ_2BYTE_RESTART_SEND,
 _I2C_READ_2BYTE_RESTART_WAIT,
 _I2C_READ_2BYTE_SLAVE_RD,
 _I2C_READ_2BYTE_SlAVE_RD_WAIT,
 _I2C_READ_2BYTE_MASTER_RD,
 _I2C_READ_2BYTE_MASTER_RD_WAIT,
 _I2C_READ_2BYTE_STOP_SEND,
 _I2C_READ_2BYTE_STOP_WAIT,
 _I2C_READ_2BYTE_FAULT
};
I2C_READ_BYTE_STATE
enum I2C_READ_BYTE_STATE
Enumerator
_I2C_READ_BYTE_WAIT_BUSY
wait until the i2c Module is not busy any more
_I2C_READ_BYTE_START_SEND
send start condition
_I2C_READ_BYTE_START_WAIT
wait start condition to complete
_I2C_READ_BYTE_SLAVE_WR
send slave address with write operation condition
_I2C_READ_BYTE_SlAVE_WR_WAIT
wait slave to AK/NAK condition to complete
_I2C_READ_BYTE_REG_AR
send base register address to slave define
_I2C_READ_BYTE_REG_AR_WAIT
wait slave to AK/NAK condition to complete
_I2C_READ_BYTE_RESTART_SEND
send a repeat start condition
_I2C_READ_BYTE_RESTART_WAIT
wait start condition to complete
_I2C_READ_BYTE_SLAVE_RD
send slave address with READ operation condition
_I2C_READ_BYTE_SlAVE_RD_WAIT
wait slave to AK/NAK condition to complete
_I2C_READ_BYTE_MASTER_RD
master reads one byte from the slave with NAK condition
_I2C_READ_BYTE_MASTER_RD_WAIT
wait master read operation finish NAK condition to complete
_I2C_READ_BYTE_STOP_SEND
send stop condition
_I2C_READ_BYTE_STOP_WAIT
wait stop condition to complete
_I2C_READ_BYTE_FAULT
Definition at line 79 of file i2c.h.
{
 _I2C_READ_BYTE_WAIT_BUSY,
 _I2C_READ_BYTE_START_SEND,
 _I2C_READ_BYTE_START_WAIT,
 _I2C_READ_BYTE_SLAVE_WR,
 _I2C_READ_BYTE_SlAVE_WR_WAIT,
 _I2C_READ_BYTE_REG_AR,
 _I2C_READ_BYTE_REG_AR_WAIT,
 _I2C_READ_BYTE_RESTART_SEND,
 _I2C_READ_BYTE_RESTART_WAIT,
 _I2C_READ_BYTE_SLAVE_RD,
 _I2C_READ_BYTE_SlAVE_RD_WAIT,
 _I2C_READ_BYTE_MASTER_RD,
 _I2C_READ_BYTE_MASTER_RD_WAIT,
 _I2C_READ_BYTE_STOP_SEND,
 _I2C_READ_BYTE_STOP_WAIT,
 _I2C_READ_BYTE_FAULT
};
I2C_READ_NBYTE_STATE
enum I2C_READ_NBYTE_STATE
Enumerator
_I2C_READ_NBYTE_WAIT_BUSY
wait until the i2c Module is not busy any more
_I2C_READ_NBYTE_START_SEND
send start condition
_I2C_READ_NBYTE_START_WAIT
wait start condition to complete
_I2C_READ_NBYTE_SLAVE_WR
send slave address with write operation condition
_I2C_READ_NBYTE_SlAVE_WR_WAIT
wait slave to AK/NAK condition to complete
_I2C_READ_NBYTE_REG_AR
send base register address to slave define
_I2C_READ_NBYTE_REG_AR_WAIT
wait slave to AK/NAK condition to complete
_I2C_READ_NBYTE_RESTART_SEND
send a repeat start condition
_I2C_READ_NBYTE_RESTART_WAIT
wait start condition to complete
_I2C_READ_NBYTE_SLAVE_RD
send slave address with READ operation condition
_I2C_READ_NBYTE_SlAVE_RD_WAIT
wait slave to AK/NAK condition to complete
_I2C_READ_NBYTE_MASTER_RD
master read one byte from the slave with AK condition
_I2C_READ_NBYTE_MASTER_RD_WAIT
wait master read operation finish AK condition to complete
_I2C_READ_NBYTE_MASTER_RD_N1
master read one byte from the slave with NAK condition
_I2C_READ_NBYTE_MASTER_RD_N1_WAIT
wait master read operation finish NAK condition to complete
_I2C_READ_NBYTE_STOP_SEND
send stop condition
_I2C_READ_NBYTE_STOP_WAIT
wait stop condition to complete
_I2C_READ_NBYTE_FAULT
Definition at line 118 of file i2c.h.
{
 _I2C_READ_NBYTE_WAIT_BUSY,
 _I2C_READ_NBYTE_START_SEND,
 _I2C_READ_NBYTE_START_WAIT,
 _I2C_READ_NBYTE_SLAVE_WR,
 _I2C_READ_NBYTE_SlAVE_WR_WAIT,
 _I2C_READ_NBYTE_REG_AR,
 _I2C_READ_NBYTE_REG_AR_WAIT,
 _I2C_READ_NBYTE_RESTART_SEND,
 _I2C_READ_NBYTE_RESTART_WAIT,
 _I2C_READ_NBYTE_SLAVE_RD,
 _I2C_READ_NBYTE_SlAVE_RD_WAIT,
_I2C_READ_NBYTE_MASTER_RD,
_I2C_READ_NBYTE_MASTER_RD_WAIT,
_I2C_READ_NBYTE_MASTER_RD_N1,
_I2C_READ_NBYTE_MASTER_RD_N1_WAIT,
 _I2C_READ_NBYTE_STOP_SEND,
 _I2C_READ_NBYTE_STOP_WAIT,
 _I2C_READ_NBYTE_FAULT
};
I2C_STATE
enum I2C_STATE
Enumerator
_I2C_WAIT
wait until data is available on the i2c receive buffer
_I2C_READ_BYTE
read only one byte from the I2c slave device
_I2C_READ_2BYTE
read only two bytes from the I2c slave device
_I2C_READ_NBYTE
read n bytes from the I2c slave device
_I2C_WRITE_BYTE
write only one byte to I2c slave device the
_I2C_WRIE_NBYTE
read n bytes to I2c slave device
_I2C_FAULT
Definition at line 26 of file i2c.h.
               {
 _I2C_WAIT,
 _I2C_READ_BYTE,
 _I2C_READ_2BYTE,
 _I2C_READ_NBYTE,
 _I2C_WRITE_BYTE,
 _I2C_WRIE_NBYTE,
 _I2C_FAULT
};
I2C_WR_BYTE_STATE
enum I2C_WR_BYTE_STATE
Enumerator
_I2C_WR_BYTE_WAIT_BUSY
wait until the i2c Module is not busy any more
_I2C_WR_BYTE_START_SEND
send start condition
_I2C_WR_BYTE_START_WAIT
wait start condition to complete
_I2C_WR_BYTE_SLAVE_WR
send slave address with write operation condition
_I2C_WR_BYTE_SlAVE_WR_WAIT
wait slave to AK/NAK condition to complete
_I2C_WR_BYTE_MASTER
master writes one byte to the slave
_I2C_WR_BYTE_MASTER_WAIT
master waits to AK/NAK to complete in AK case just go to stop
_I2C_WR_BYTE_STOP_SEND
send stop condition
_I2C_WR_BYTE_STOP_WAIT
wait stop condition to complete
_I2C_WR_BYTE_FAULT
Definition at line 36 of file i2c.h.
                       {
 _I2C_WR_BYTE_WAIT_BUSY,
 _I2C_WR_BYTE_START_SEND,
 _I2C_WR_BYTE_START_WAIT,
 _I2C_WR_BYTE_SLAVE_WR,
 _I2C_WR_BYTE_SlAVE_WR_WAIT,
 _I2C_WR_BYTE_MASTER,
 _I2C_WR_BYTE_MASTER_WAIT,
 _I2C_WR_BYTE_STOP_SEND,
 _I2C_WR_BYTE_STOP_WAIT,
 _I2C_WR_BYTE_FAULT
};
I2C_WRITE_BYTE_STATE
enum I2C_WRITE_BYTE_STATE
Enumerator
_I2C_WRITE_BYTE_WAIT_BUSY
wait until the i2c Module is not busy any more
_I2C_WRITE_BYTE_START_SEND
send start condition
_I2C_WRITE_BYTE_START_WAIT
wait start condition to complete
_I2C_WRITE_BYTE_SLAVE_WR
send slave address with write operation condition
_I2C_WRITE_BYTE_SlAVE_WR_WAIT
wait slave to AK/NAK condition to complete
_I2C_WRITE_BYTE_REG_AR
send base register address to slave define
_I2C_WRITE_BYTE_REG_AR_WAIT
wait slave to AK/NAK condition to complete
_I2C_WRITE_BYTE_MASTER
master write one byte from the slave with NAK condition
_I2C_WRITE_BYTE_MASTER_WAIT
wait master read operation finish NAK condition to complete
_I2C_WRITE_BYTE_STOP_SEND
send stop condition
_I2C_WRITE_BYTE_STOP_WAIT
wait stop condition to complete
_I2C_WRITE_BYTE_FAULT
Definition at line 48 of file i2c.h.
{
 _I2C_WRITE_BYTE_WAIT_BUSY,
 _I2C_WRITE_BYTE_START_SEND,
 _I2C_WRITE_BYTE_START_WAIT,
 _I2C_WRITE_BYTE_SLAVE_WR,
 _I2C_WRITE_BYTE_SlAVE_WR_WAIT,
 _I2C_WRITE_BYTE_REG_AR,
 _I2C_WRITE_BYTE_REG_AR_WAIT,
 _I2C_WRITE_BYTE_MASTER,
 _I2C_WRITE_BYTE_MASTER_WAIT,
 _I2C_WRITE_BYTE_STOP_SEND,
 _I2C_WRITE_BYTE_STOP_WAIT,
 _I2C_WRITE_BYTE_FAULT
};
I2C_WRITE_NBYTE_STATE
enum I2C_WRITE_NBYTE_STATE
Enumerator
_I2C_WRITE_NBYTE_WAIT_BUSY
wait until the i2c Module is not busy any more
_I2C_WRITE_NBYTE_START_SEND
send start condition
_I2C_WRITE_NBYTE_START_WAIT
wait start condition to complete
_I2C_WRITE_NBYTE_SLAVE_WR
send slave address with write operation condition
_I2C_WRITE_NBYTE_SlAVE_WR_WAIT
wait slave to AK/NAK condition to complete
_I2C_WRITE_NBYTE_REG_AR
send base register address to slave define
_I2C_WRITE_NBYTE_REG_AR_WAIT
wait slave to AK/NAK condition to complete
_I2C_WRITE_NBYTE_MASTER
master writes n bytes to the slave and wait after each byte AK
_I2C_WRITE_NBYTE_MASTER_WAIT
master waits slave to AK/NAK condition to complete
_I2C_WRITE_NBYTE_STOP_SEND
send stop condition
_I2C_WRITE_NBYTE_STOP_WAIT
wait stop condition to complete
_I2C_WRITE_NBYTE_FAULT
Definition at line 63 of file i2c.h.
{
 _I2C_WRITE_NBYTE_WAIT_BUSY,
 _I2C_WRITE_NBYTE_START_SEND,
 _I2C_WRITE_NBYTE_START_WAIT,
 _I2C_WRITE_NBYTE_SLAVE_WR,
 _I2C_WRITE_NBYTE_SlAVE_WR_WAIT,
 _I2C_WRITE_NBYTE_REG_AR,
 _I2C_WRITE_NBYTE_REG_AR_WAIT,
 _I2C_WRITE_NBYTE_MASTER,
 _I2C_WRITE_NBYTE_MASTER_WAIT,
 _I2C_WRITE_NBYTE_STOP_SEND,
 _I2C_WRITE_NBYTE_STOP_WAIT,
 _I2C_WRITE_NBYTE_FAULT
};
Function Documentation
i2_stop()
uint8_t i2_stop ()
initiate start condition
initiate start condition
Returns
uint8_t
Definition at line 284 of file i2c.c.
{
    return 0;
}
i2c1_init()
void i2c1_init (uint32_t clock_speed, uint16_t ownaddress)
i2c_init()
void i2c_init ()
Definition at line 59 of file i2c.c.
{
  /* 1. Enable the Clock for the peripheral module AFIO/GPIO modules using */
  /* 2. Configure the pins required by the Module (AFIO_OUT or INPUT, ANALOG...) & remap incase of requirement */
  /* 3. Configure the peripheral hardware interrupt @ level of  NVIC  link to IRQ and set priority */
  /* 4.  the peripheral hardware  of the I2C */
  /* 5. Configure the peripheral interrupt @ level of the peripheral or DMA */
  /* 6. Enable the peripheral Module */
  /* 1. Enable the Clock for AFIO/GPIO modules then the peripheral module using  either
      registers :  RCC_APB1ENR |RCC_APB2ENR | RCC_AHBENR  or
      methods periphstdlib  :  RCC_APBxPeriphClockCmd or using
  */
  // disable the i2c
  myi2c.ptr->CR1.PE=0;
/* 1. Enable the Clock for the  AFIO/GPIO modules and the I2c peripheral module */
  //RCC->APB2ENR|=RCC_APB2ENR_AFIOEN;
   reg_sbits(myi2c.RCC_APBxENR_AFIO.reg,myi2c.RCC_APBxENR_AFIO.bits);
 //*(myi2c.RCC_APBxENR_AFIO_reg)|=myi2c.RCC_APBxENR_AFIOEN_val;
 // sbits(*myi2c.RCC_APBxENR_AFIO_reg,myi2c.RCC_APBxENR_AFIOEN_val);
 //RCC->APB2ENR|=RCC_APB2ENR_IOPBEN;
  reg_sbits(myi2c.RCC_APBxENR_IOP.reg,myi2c.RCC_APBxENR_IOP.bits);
  reg_cbits(myi2c.AFIO_MAPR_I2C.reg,myi2c.AFIO_MAPR_I2C.bits);
//*(myi2c.RCC_APBxENR_IOP_reg)|=myi2c.RCC_APBxENR_IOPEN_val;
//  sbits(*myi2c.RCC_APBxENR_IOP_reg,myi2c.RCC_APBxENR_IOPEN_val);
 //RCC->APB1ENR|=RCC_APB1ENR_I2C1EN;
 reg_sbits(myi2c.RCC_APBxENR_I2C.reg,myi2c.RCC_APBxENR_I2C.bits);
  //*(myi2c.RCC_APBxENR_I2C_reg)|=myi2c.RCC_APBxENR_I2CEN_reg;
  //  sbits(*myi2c.RCC_APBxENR_I2C_reg,myi2c.RCC_APBxENR_I2CEN_val);
/* 2. Configure the pins required by the Module (AFIO_OUT or INPUT, ANALOG...) & remap incase of requirement */
  gpio_pin_mode(myi2c.scl,GPIO_MODE_AF_OD_50MHZ);
  gpio_pin_mode(myi2c.sda,GPIO_MODE_AF_OD_50MHZ);
  /* 3. Configure the peripheral hardware interrupt @ level of  NVIC  link to IRQ and set priority */
  /* 4.  the peripheral hardware  of the I2C */
  /* 5. Configure the peripheral interrupt @ level of the peripheral or DMA */
  /* 6. Enable the peripheral Module */
myi2c.ptr->CR1.PE=1; //AFIO_MAPR_I2C1_REMAP;
/*  if(i2c==(I2C_TypeDef_t *) I2C1_BASE)
  {
   RCC->APB1ENR|=RCC_APB1ENR_I2C1EN;
   RCC->APB1RSTR|=RCC_APB1RSTR_I2C1RST;
   RCC->APB1RSTR&=~RCC_APB1RSTR_I2C1RST;
  }
  else
  {
  }
  */
}
References i2c_t::AFIO_MAPR_I2C, reg_t::bits, I2C_TypeDef_t::CR1, GPIO_MODE_AF_OD_50MHZ, gpio_pin_mode(), myi2c, I2C_CR1_t::PE, i2c_t::ptr, i2c_t::RCC_APBxENR_AFIO, i2c_t::RCC_APBxENR_I2C, i2c_t::RCC_APBxENR_IOP, reg_t::reg, reg_cbits(), reg_sbits(), i2c_t::scl, and i2c_t::sda.
i2c_read_data()
uint8_t i2c_read_data (uint8_t * data, uint8_t ack)
write data
Definition at line 333 of file i2c.c.
{
 return 0;
}
i2c_send_byte()
uint8_t i2c_send_byte (uint8_t data)
initiate stop condition
initiate stop condition
Parameters
data
Returns
uint8_t
Definition at line 295 of file i2c.c.
{
    return 0;
}
i2c_send_sla_rd()
uint8_t i2c_send_sla_rd (uint8_t SLA_R)
send a slave with write operation via TWI bus
send a slave with write operation via TWI bus
Parameters
SLA_R
Returns
uint8_t
Definition at line 317 of file i2c.c.
{
 return 0;
}
i2c_send_sla_wr()
uint8_t i2c_send_sla_wr (uint8_t SLA_W)
send a byte via TWI bus
send a byte via TWI bus
Parameters
SLA_W
Returns
uint8_t
Definition at line 306 of file i2c.c.
{
  return 0;
}
i2c_start()
uint8_t i2c_start ()
initiate start condition
Returns
uint8_t
Definition at line 273 of file i2c.c.
 {
    return 0;
 }
i2c_uart_print()
void i2c_uart_print (USART_TypeDef * uart)
Definition at line 123 of file i2c.c.
{
  WORD_BYTES t;
   RCC_ClocksTypeDef  rcc_clocks;
   uint32_t pclk1 =0;
    RCC_GetClocksFreq(&rcc_clocks);
    pclk1 = rcc_clocks.PCLK1_Frequency;
    uart_print(uart,"\t pclk1:");
  uart_print_integer(uart,pclk1,10);
  t.word= i2cx->CR2.FREQ;//I2C1->CR2 & 0x003f;// i2cx->CR2.FREQ
    uart_print(uart,"\t frq:");
  uart_print_integer(uart,t.word,10);
  t.word=I2C1->CCR & 0x0FFF ;//i2cx->CCR.CCR;
  uart_print(uart,"\t CCR:");
  uart_print_integer(uart,t.word,10);
  uart_print(uart,"\t");
 // t.word=i2cx->CCR.CCR & 0x0FFF ;
 // uart_print(uart,"\t CCRx:");
 // uart_print_integer(uart,t.word,10);
 // uart_print(uart,"\t");
  t.word=I2C1->TRISE& 0x003f;
  uart_print(uart,"\t tris:");
  uart_print_integer(uart,t.word,10);
  uart_print(uart,"\t\r\n");
  //t.word=i2cx->TRISE.val & 0x003f;//I2C1->TRISE& 0x003f;//i2cx->TRISE.val;
  //uart_print(uart,"\t trisx:");
  //uart_print_integer(uart,t.word,10);
  //uart_print(uart,"\r\n");
//I2C1
//  I2C1->CR1=0x3456;
  t.word=I2C1->CR1;
  uart_print(uart,"\t I2C1_CR1:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
 // I2C1->CR2=0x1239;
  t.word=I2C1->CR2;
  uart_print(uart,"\t I2C1_CR2:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
 // I2C1->OAR1;
  t.word=I2C1->OAR1;
  uart_print(uart,"\t I2C1_OAR1:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
 // I2C1->OAR2=0x342e;
  t.word=I2C1->OAR2;
  uart_print(uart,"\t I2C1_OAR2:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\r\n");
  //I2C1->SR1=0x4444;
  t.word=I2C1->SR1;
  uart_print(uart,"\t I2C1_SR1:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
  //I2C1->SR2=0x8888;
  t.word=I2C1->SR2;
  uart_print(uart,"\t I2C1_SR2:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
 // I2C1->CCR=0x3024;
  t.word=I2C1->CCR;
  uart_print(uart,"\t I2C1_CCR:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
 // I2C1->TRISE=0x0040;
  t.word=I2C1->TRISE;
  uart_print(uart,"\t I2C1_TRISE:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
  //I2C1->DR=0x6734;
  t.word=I2C1->DR;
  uart_print(uart,"\t I2C1_DR:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\r\n");
//I2Cx
/*
  t.word=i2cx->CR1.val;
  uart_print(uart,"\t I2Cx_CR1:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
  t.word=i2cx->CR2.val;
  uart_print(uart,"\t I2Cx_CR2:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
  t.word=i2cx->OAR1.val;
  uart_print(uart,"\t I2Cx_OAR1:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
  t.word=i2cx->OAR2.val;
  uart_print(uart,"\t I2Cx_OAR2:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\r\n");
  t.word=i2cx->SR1.val;
  uart_print(uart,"\t I2Cx_SR1:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
  t.word=i2cx->SR2.val;
  uart_print(uart,"\t I2Cx_SR2:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
  t.word=i2cx->CCR.val;
  uart_print(uart,"\t I2Cx_CCR:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
  t.word=i2cx->TRISE.val;
  uart_print(uart,"\t I2Cx_TRISE:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\t");
  t.word=i2cx->DR.val;
  uart_print(uart,"\t I2Cx_DR:");
  uart_print_integer(uart,t.word,16);
  uart_print(uart,"\r\n");
 */
}
References I2C_TypeDef_t::CR2, I2C_CR2_t::FREQ, i2cx, uart_print(), uart_print_integer(), and WORD_BYTES::word.
Referenced by mpu6050_set_hpf(), mpu6050_set_lpf(), and mpu6050_task().
i2c_write_data()
uint8_t i2c_write_data (uint8_t data)
send a slave with read operation via TWI bus
send a slave with read operation via TWI bus
Parameters
data
Returns
uint8_t
Definition at line 328 of file i2c.c.
{
 return 0;
}
Variable Documentation
i2cx
I2C_TypeDef_t* i2cx extern
i2c.c
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Definition at line 27 of file i2c.c.
Referenced by i2c_uart_print().
myi2c
i2c_t myi2c extern
Definition at line 32 of file i2c.c.
Referenced by i2c_init().