STM32F103_IMU6050App: init/init.h File Reference
init.h File Reference
#include "stm32f10x.h"
#include "stm32f10x_conf.h"
#include "stm32f10x_it.h"
#include "basic.h"
#include "init-macro.h"
#include "TIM.h"
#include "uart.h"
#include "i2c.h"
#include "mpu6050.h"
#include "lcd.h"
#include "keypad.h"
#include "system-task.h"
#include "system.h"
Functions
void blink_init (void)
void blink (void)
void pilot_init (void)
void pilot_write (uint8_t val)
void rly_init (void)
void rly_write (uint8_t val)
void disable_buffer ()
void _delay_us (uint32_t val)
void _delay_ms (uint32_t val)
Variables
uint32_t TimingDelay
init.h
uint32_t BlinkTimingDelay
uint8_t lcd_update
uint8_t blink_update
pilot_t pilots
rly_t relays
gpio_t blink_led
gpio_t pilot_en
gpio_t pilot_db [8]
gpio_t rly [6]
Function Documentation
_delay_ms()
void _delay_ms (uint32_t val)
Definition at line 232 of file init.c.
{
  //uint32_t time=mTime*SystemCoreClock/5000;
  //for (uint32_t i=0;i<time;i++)
  //    asm("nop");
     TimingDelay=mTime*1000;
   while(TimingDelay!=0);
}
References TimingDelay.
Referenced by blink(), lcd_clear(), and mpu6050_reset().
_delay_us()
void _delay_us (uint32_t val)
Definition at line 222 of file init.c.
{
    TimingDelay=mTime;
    while(TimingDelay!=0);
    //uint32_t time=mTime*SystemCoreClock/1000000;
    //for (uint32_t i=0;i<time;i++)
    //  asm("nop");
}
References TimingDelay.
Referenced by keypad_read(), lcd_read_byte(), lcd_write_byte(), lcd_write_cmd(), and lcd_write_data().
blink()
void blink (void)
Definition at line 173 of file init.c.
{
    // write Hi to PC13
    GPIO_SetBits(GPIOC,GPIO_Pin_13);
    //GPIO_SetBits(blink_led.port,(uint32_t)(1<<blink_led.pin));
    //gpio_set(blink_led);
    _delay_ms(500);
    // write LOW to PC13
    GPIO_ResetBits(GPIOC,GPIO_Pin_13);
    //GPIO_ResetBits(blink_led.port,(uint32_t)(1<<blink_led.pin));
    //gpio_clear(blink_led);
    _delay_ms(500);
}
References _delay_ms().
Referenced by lcd_set_display_cursor().
blink_init()
void blink_init (void)
Configure the blink led using the stander peripheral library
a full details steps is used to configure it as a digital output with push-pull and low speed 2MHz
a number of methods to write data to gpio pin or pins or port
void GPIO_SetBits(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin) void GPIO_ResetBits(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin) void GPIO_WriteBit(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, BitAction BitVal) void GPIO_Write(GPIO_TypeDef* GPIOx, uint16_t PortVal)
a number of methods to read data from IDR (input data register) as pins or port ODR (output data register) as pins or port uint8_t GPIO_ReadInputDataBit(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
uint8_t GPIO_ReadOutputDataBit(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
uint16_t GPIO_ReadInputData(GPIO_TypeDef* GPIOx) uint16_t GPIO_ReadOutputData(GPIO_TypeDef* GPIOx)
Configure the blink led using the stander peripheral library
a full detailed steps in one function gpio_init in which it defines the mode and speed as parameters as a digital output with push-pull and low speed 2MHz
Configure the blink led using the stander peripheral library
short detailed steps in one function gpio_pinmode in which it defines the mode and speed as parameters and pass a gpio_t as a digital output with push-pull and low speed 2MHz
Configure the blink led using the stander peripheral library
short detailed steps in one function gpio_pinmode in which it defines the mode and speed as parameters and pass a gpio_t as a digital output with push-pull and low speed 2MHz
Definition at line 94 of file init.c.
{
    GPIO_InitTypeDef gpio;
    GPIO_StructInit((GPIO_InitTypeDef *)&gpio);
    gpio.GPIO_Speed=GPIO_Speed_2MHz;
    gpio.GPIO_Pin=GPIO_Pin_13;
    GPIO_Init(GPIOC,&gpio);
     GPIO_SetBits(GPIOC,GPIO_Pin_13);
     //GPIO_ResetBits(GPIOC,GPIO_Pin_13);
     //GPIO_WriteBit(GPIOC,GPIO_Pin_13,Bit_RESET);
     //GPIO_WriteBit(GPIOC,GPIO_Pin_13,Bit_SET);
     //GPIO_Write(GPIOC,0b1110111111111111);
   uint8_t in_bit_val=0, out_bit_val=0;
   uint16_t in_port_val=0,out_port_val=0;
   in_bit_val=GPIO_ReadInputDataBit(GPIOC,GPIO_Pin_13);    // read IDR bit
   out_bit_val=GPIO_ReadOutputDataBit(GPIOC,GPIO_Pin_13); // read ODR  bit
   in_port_val=GPIO_ReadInputData(GPIOC);                // read IDR for port C
   out_port_val=GPIO_ReadOutputData(GPIOC);               // read IDR for port C
  gpio_init(blink_led.port,blink_led.pin,GPIO_Mode_Out_PP,GPIO_Speed_2MHz);
  GPIO_SetBits(blink_led.port,(uint32_t)(1<<blink_led.pin));
  GPIO_WriteBit(blink_led.port,(uint32_t)(1<<blink_led.pin),Bit_RESET);
   gpio_pinmode(blink_led,GPIO_Mode_Out_PP,GPIO_Speed_2MHz);
   GPIO_SetBits(blink_led.port,(uint32_t)(1<<blink_led.pin));
   GPIO_WriteBit(blink_led.port,(uint32_t)(1<<blink_led.pin),Bit_RESET);
// Configure the blink led using the
    gpio_pin_mode(blink_led,GPIO_MODE_OUT_PP_2MHZ);
    gpio_clear(blink_led);
}
References blink_led, gpio_clear(), gpio_init(), GPIO_MODE_OUT_PP_2MHZ, gpio_pin_mode(), gpio_pinmode(), gpio_t::pin, and gpio_t::port.
Referenced by system_init().
disable_buffer()
void disable_buffer ()
Definition at line 190 of file init.c.
{
    // set pin mode of output latch as an output
      gpio_pin_mode(pilot_en,GPIO_MODE_OUT_PP_2MHZ);
    // disable output latch
    gpio_set(pilot_en);
    // set pin mode of lcd_en as an output
      gpio_pin_mode(lcd_en,GPIO_MODE_OUT_PP_2MHZ);
    // disable lcd
    gpio_set(lcd_en);
    // set pin mode of keypad as an output
      gpio_pin_mode(keypad_en,GPIO_MODE_OUT_PP_2MHZ);
    // disable keypad
    gpio_set(keypad_en);
  //set pin mode of keypad port as an input
  // which is shared with lcd and output latch
   keypad_port_input_pullup();
}
References GPIO_MODE_OUT_PP_2MHZ, gpio_pin_mode(), gpio_set(), keypad_en, keypad_port_input_pullup(), lcd_en, and pilot_en.
Referenced by keypad_scan().
pilot_init()
void pilot_init (void)
Definition at line 52 of file init.c.
{
    for(uint8_t i=0;i<8;i++)
    gpio_pin_mode(pilot_db[i],GPIO_MODE_OUT_PP_2MHZ);
    gpio_pin_mode(pilot_en,GPIO_MODE_OUT_PP_2MHZ);
}
References GPIO_MODE_OUT_PP_2MHZ, gpio_pin_mode(), pilot_db, and pilot_en.
Referenced by system_init().
pilot_write()
void pilot_write (uint8_t val)
Definition at line 66 of file init.c.
{
    gpio_set(pilot_en);
   for(uint8_t i=0;i<8;i++)
   if(bit_is_set(val,i))
     gpio_set(pilot_db[i]);
   else
     gpio_clear(pilot_db[i]);
    gpio_clear(pilot_en);
        asm("nop");
        asm("nop");
        asm("nop");
        asm("nop");
    gpio_set(pilot_en);
}
References bit_is_set, gpio_clear(), gpio_set(), pilot_db, and pilot_en.
Referenced by system_init(), and system_rtc().
rly_init()
void rly_init (void)
Definition at line 60 of file init.c.
{
  for(uint8_t i=0;i<6;i++)
   gpio_pin_mode(rly[i],GPIO_MODE_OUT_PP_2MHZ);
}
References GPIO_MODE_OUT_PP_2MHZ, gpio_pin_mode(), and rly.
Referenced by system_init().
rly_write()
void rly_write (uint8_t val)
Definition at line 84 of file init.c.
{
   for(uint8_t i=0;i<6;i++)
   if(bit_is_set(val,i))
     gpio_set(rly[i]);
   else
     gpio_clear(rly[i]);
}
References bit_is_set, gpio_clear(), gpio_set(), and rly.
Referenced by system_init(), and TIM3_IRQHandler().
Variable Documentation
blink_led
gpio_t blink_led extern
Definition at line 27 of file init.c.
Referenced by blink_init(), and rtc_task().
blink_update
uint8_t blink_update
Definition at line 47 of file init.h.
BlinkTimingDelay
uint32_t BlinkTimingDelay
Definition at line 46 of file init.h.
lcd_update
uint8_t lcd_update extern
Definition at line 22 of file init.c.
Referenced by lcd_task(), system_init(), and TIM3_IRQHandler().
pilot_db
gpio_t pilot_db[8] extern
Definition at line 29 of file init.c.
Referenced by pilot_init(), and pilot_write().
pilot_en
gpio_t pilot_en extern
Definition at line 28 of file init.c.
Referenced by disable_buffer(), pilot_init(), and pilot_write().
pilots
pilot_t pilots extern
Definition at line 24 of file init.c.
Referenced by keypad_down_key_handle(), keypad_esc_key_handle(), keypad_info_key_handle(), keypad_set_key_handle(), keypad_shft_key_handle(), keypad_up_key_handle(), system_init(), and system_rtc().
relays
rly_t relays extern
Definition at line 25 of file init.c.
Referenced by lcd_task(), system_init(), TIM3_IRQHandler(), and uart_receive().
rly
gpio_t rly[6] extern
Definition at line 39 of file init.c.
Referenced by rly_init(), and rly_write().
TimingDelay
uint32_t TimingDelay extern
init.h
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
init.h
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Definition at line 21 of file init.c.
Referenced by _delay_ms(), _delay_us(), and system_init().