STM32F103_IMU6050App: keypad/keypad.c File Reference
keypad.c File Reference
#include "init.h"
Functions
static uint8_t keypad_port_get_input_data (void)
keypad.c
static uint8_t keypad_read (void)
static void keypad_handle (void)
void keypad_port_input_pullup (void)
void keypad_init (uint8_t unpressed_mask)
uint8_t keypad_scan (void)
void keypad_process (void)
uint8_t keypad_is_pressed (void)
void keypad_up_key_handle (void)
void keypad_down_key_handle (void)
void keypad_set_key_handle (void)
void keypad_esc_key_handle (void)
void keypad_shft_key_handle (void)
void keypad_info_key_handle (void)
Variables
Keypad_btn_t key_val
uint8_t keypad_unpressed_mask =0
gpio_t keypad_en ={GPIOC,14}
gpio_t keypad_port [8]
Function Documentation
keypad_down_key_handle()
void keypad_down_key_handle (void)
Definition at line 165 of file keypad.c.
{
   lcd_print_xy(0,1,"down key pressed...");
   pilots.pilot_6=~pilots.pilot_6;
  TIM_Cmd(TIM2,ENABLE);
}
References lcd_print_xy(), pilot_t::pilot_6, and pilots.
Referenced by keypad_handle().
keypad_esc_key_handle()
void keypad_esc_key_handle (void)
Definition at line 179 of file keypad.c.
{
  lcd_print_xy(0,1,"esc key pressed...");
  pilots.pilot_4=~pilots.pilot_4;
  TIM_Cmd(TIM3,ENABLE);
}
References lcd_print_xy(), pilot_t::pilot_4, and pilots.
Referenced by keypad_handle().
keypad_handle()
void keypad_handle (void) static
Definition at line 100 of file keypad.c.
{
//my_gnc.usb.printf("key_val:0x%02x",key_val.val);
  //my_gnc.usb.println();
  switch(key_val.val)
  {
    case 0x7c:keypad_up_key_handle();         break;
    case 0xbc:keypad_down_key_handle();   break;
    case 0xdc:keypad_set_key_handle();    break;
    case 0xec:keypad_esc_key_handle();      break;
    case 0xf4:keypad_shft_key_handle();   break;
  }
}
References key_val, keypad_down_key_handle(), keypad_esc_key_handle(), keypad_set_key_handle(), keypad_shft_key_handle(), keypad_up_key_handle(), and Keypad_btn_t::val.
Referenced by keypad_process().
keypad_info_key_handle()
void keypad_info_key_handle (void)
Definition at line 193 of file keypad.c.
{
   lcd_print_xy(0,1,"info key pressed...");
   pilots.pilot_2=~pilots.pilot_2;
}
References lcd_print_xy(), pilot_t::pilot_2, and pilots.
keypad_init()
void keypad_init (uint8_t unpressed_mask)
Definition at line 119 of file keypad.c.
{
 // set the unpressed value
   keypad_unpressed_mask=unpressed_mask;
// set keypad port as input with pull up resistor
   keypad_port_input_pullup();
 // set keypad enable pin as output with push-pull
   gpio_pin_mode(keypad_en,GPIO_MODE_OUT_PP_2MHZ);
 // deactivate the keypad
   gpio_set(keypad_en);
}
References GPIO_MODE_OUT_PP_2MHZ, gpio_pin_mode(), gpio_set(), keypad_en, keypad_port_input_pullup(), and keypad_unpressed_mask.
Referenced by system_init().
keypad_is_pressed()
uint8_t keypad_is_pressed (void)
Definition at line 151 of file keypad.c.
{
  if(key_val.val==keypad_unpressed_mask)
      return 0;
  return 1;
}
References key_val, keypad_unpressed_mask, and Keypad_btn_t::val.
keypad_port_get_input_data()
uint8_t keypad_port_get_input_data (void) static
keypad.c
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Definition at line 60 of file keypad.c.
{
  uint8_t val=0xff;
  for(uint8_t i=0;i<8;i++)
   if(!gpio_get(keypad_port[i]))
     cbit(val,i);
  return val ;
}
References cbit, gpio_get(), and keypad_port.
Referenced by keypad_read().
keypad_port_input_pullup()
void keypad_port_input_pullup (void)
Definition at line 53 of file keypad.c.
{
  for(uint8_t i=0;i<8;i++)
   gpio_in_pullup(keypad_port[i]);
}
References gpio_in_pullup(), and keypad_port.
Referenced by disable_buffer(), keypad_init(), and keypad_read().
keypad_process()
void keypad_process (void)
Definition at line 138 of file keypad.c.
{
 if(key_val.val!=keypad_unpressed_mask)
 {
     // the keypad is pressed therefore reset exit_timeout counter
        //App_t::menu.set_exit_cnt(0);
    logout_timeout.sec=5;
    logout_timeout.min=0;
        keypad_handle();
 }
}
References key_val, keypad_handle(), keypad_unpressed_mask, logout_timeout, minute_t::min, minute_t::sec, and Keypad_btn_t::val.
Referenced by keypad_task().
keypad_read()
uint8_t keypad_read (void) static
Definition at line 70 of file keypad.c.
{
  uint8_t val=0xff;
// set keypad port as input with pull up resistor
   keypad_port_input_pullup();
 // set keypad enable pin as output with push-pull
   gpio_pin_mode(keypad_en,GPIO_MODE_OUT_PP_2MHZ);
 // deactivate the keypad
   gpio_set(keypad_en);
    // activate the keypad
    gpio_clear(keypad_en);
  _delay_us(10);
    asm("nop");
    asm("nop");
    asm("nop");
    asm("nop");
    asm("nop");
    asm("nop");
    // read data from input port
    val=keypad_port_get_input_data();
  //lcd_print_uint8_xy(12,0,val,16);
    // deactivate the keypad
   gpio_set(keypad_en);
return val;
}
References _delay_us(), gpio_clear(), GPIO_MODE_OUT_PP_2MHZ, gpio_pin_mode(), gpio_set(), keypad_en, keypad_port_get_input_data(), and keypad_port_input_pullup().
Referenced by keypad_scan().
keypad_scan()
uint8_t keypad_scan (void)
Definition at line 131 of file keypad.c.
{
  disable_buffer();
  key_val.val= keypad_read() & keypad_unpressed_mask;
 return key_val.val;
}
References disable_buffer(), key_val, keypad_read(), keypad_unpressed_mask, and Keypad_btn_t::val.
Referenced by keypad_task().
keypad_set_key_handle()
void keypad_set_key_handle (void)
Definition at line 172 of file keypad.c.
{
    lcd_print_xy(0,1,"set key pressed...");
    pilots.pilot_5=~pilots.pilot_5;
  TIM_Cmd(TIM3,DISABLE);
}
References lcd_print_xy(), pilot_t::pilot_5, and pilots.
Referenced by keypad_handle().
keypad_shft_key_handle()
void keypad_shft_key_handle (void)
Definition at line 187 of file keypad.c.
{
    lcd_print_xy(0,1,"shft key pressed...");
    pilots.pilot_3=~pilots.pilot_3;
}
References lcd_print_xy(), pilot_t::pilot_3, and pilots.
Referenced by keypad_handle().
keypad_up_key_handle()
void keypad_up_key_handle (void)
Definition at line 158 of file keypad.c.
{
  lcd_print_xy(0,1,"up key pressed...");
  pilots.pilot_7=~pilots.pilot_7;
  TIM_Cmd(TIM2,DISABLE);
}
References lcd_print_xy(), pilot_t::pilot_7, and pilots.
Referenced by keypad_handle().
Variable Documentation
key_val
Keypad_btn_t key_val
Definition at line 30 of file keypad.c.
Referenced by keypad_handle(), keypad_is_pressed(), keypad_process(), and keypad_scan().
keypad_en
gpio_t keypad_en ={GPIOC,14}
Definition at line 36 of file keypad.c.
Referenced by disable_buffer(), keypad_init(), and keypad_read().
keypad_port
gpio_t keypad_port[8]
Initial value:
={
{GPIOA,7},
{GPIOA,6},
{GPIOA,5},
{GPIOA,4},
{GPIOA,3},
{GPIOA,2},
{GPIOA,1},
{GPIOA,0},
}
Definition at line 37 of file keypad.c.
Referenced by keypad_port_get_input_data(), and keypad_port_input_pullup().
keypad_unpressed_mask
uint8_t keypad_unpressed_mask =0
Definition at line 32 of file keypad.c.
Referenced by keypad_init(), keypad_is_pressed(), keypad_process(), and keypad_scan().