STM32F103_IMU6050App: lcd/lcd.c File Reference
lcd.c File Reference
#include "init.h"
Functions
static void lcd_port_pinmode_in (void)
static void lcd_port_pinmode_out (void)
static void lcd_port_write_byte (uint8_t b)
static uint8_t lcd_port_read_byte (void)
static void lcd_rs_pinmode_in (void)
static void lcd_rs_pinmode_out (void)
static void lcd_rs_clear (void)
static void lcd_rs_set (void)
static void lcd_en_pinmode_in (void)
static void lcd_en_pinmode_out (void)
static void lcd_en_clear (void)
static void lcd_en_set (void)
static uint8_t lcd_read_busy (void)
static uint8_t lcd_read_data (void)
static void lcd_write_data (uint8_t data)
static void lcd_write_cmd (uint8_t cmd)
static void lcd_write_byte (uint8_t byte)
static uint8_t lcd_read_byte (void)
static size_t lcd_print_as_number (unsigned long long n, uint8_t base)
static size_t lcd_print_as_Float (double n, uint8_t digits)
void lcd_clear ()
void lcd_cursor_home ()
void lcd_cursor_on ()
void lcd_cursor_off ()
void lcd_cursor_blink ()
void lcd_cursor_shift_left ()
void lcd_cursor_shift_right ()
void lcd_display_shift_left ()
void lcd_display_shift_right ()
void lcd_entery_mode_increment ()
void lcd_entery_mode_decrement ()
void lcd_set_display_cursor (uint8_t display, uint8_t cursor, uint8_t blink)
void lcd_init ()
void lcd_refresh (void)
uint8_t lcd_is_busy ()
uint8_t lcd_get_AC ()
void lcd_set_line (uint8_t index)
void lcd_clear_line (uint8_t index)
void lcd_goto_xy (uint8_t x, uint8_t y)
void lcd_write_8bit (uint8_t val)
void lcd_write_16bit (uint16_t val)
void lcd_write_bcd_8bit (uint8_t val)
void lcd_write_bcd_16bit (uint16_t val)
void lcd_init_cgram (uint8_t *pattern, uint8_t num)
void lcd_print_cgram (uint8_t x, uint8_t y, uint8_t pattern)
void lcd_write_num (uint32_t val, uint8_t base)
void lcd_write_hex (uint32_t val)
void lcd_write_octal (uint32_t val)
void lcd_write_int (uint32_t val)
void lcd_write_bin (uint32_t val)
size_t lcd_write (uint8_t b)
size_t lcd_write_array (const uint8_t *buffer, size_t size)
size_t lcd_write_str (const char *buffer, size_t size)
size_t lcd_write_cstr (const char *str)
size_t lcd_print_array (uint8_t buf[], uint8_t len)
size_t lcd_print_ch (char c)
size_t lcd_print (const char *str)
size_t lcd_print_xy (uint8_t x, uint8_t y, const char *str)
void lcd_printf (const char *fmt,...)
void lcd_printf_xy (uint8_t x, uint8_t y, const char *fmt,...)
size_t lcd_print_uint8 (uint8_t n, int base)
size_t lcd_print_uint8_xy (uint8_t x, uint8_t y, uint8_t n, int base)
size_t lcd_print_uint8_str (const char *str, uint8_t n, int base)
size_t lcd_print_uint8_xy_str (uint8_t x, uint8_t y, const char *str, uint8_t n, int base)
size_t lcd_print_int8_t (int8_t n, int base)
size_t lcd_print_int8_xy (uint8_t x, uint8_t y, int8_t n, int base)
size_t lcd_print_int8_str (const char *str, int8_t n, int base)
size_t lcd_print_int8_xy_str (uint8_t x, uint8_t y, const char *str, int8_t n, int base)
size_t lcd_print_uint16 (uint16_t n, int base)
size_t lcd_print_uint16_xy (uint8_t x, uint8_t y, uint16_t n, int base)
size_t lcd_print_uint16_str (const char *str, uint16_t n, int base)
size_t lcd_print_uint16_xy_str (uint8_t x, uint8_t y, const char *str, uint16_t n, int base)
size_t lcd_print_int16 (int16_t n, int base)
size_t lcd_print_int16_xy (uint8_t x, uint8_t y, int16_t n, int base)
size_t lcd_print_int16_str (const char *str, int16_t n, int base)
size_t lcd_print_int16_xy_str (uint8_t x, uint8_t y, const char *str, int16_t n, int base)
size_t lcd_print_uint32 (uint32_t n, int base)
size_t lcd_print_uint32_xy (uint8_t x, uint8_t y, uint32_t n, int base)
size_t lcd_print_uint32_str (const char *str, uint32_t n, int base)
size_t lcd_print_uint32_xy_str (uint8_t x, uint8_t y, const char *str, uint32_t n, int base)
size_t lcd_print_int32 (int32_t n, int base)
size_t lcd_print_int32_xy (uint8_t x, uint8_t y, int32_t n, int base)
size_t lcd_print_int32_str (const char *str, int32_t n, int base)
size_t lcd_print_int32_xy_str (uint8_t x, uint8_t y, const char *str, int32_t n, int base)
size_t lcd_print_uint64 (uint64_t n, int base)
size_t lcd_print_uint64_xy (uint8_t x, uint8_t y, uint64_t n, int base)
size_t lcd_print_uint64_str (const char *str, uint64_t n, int base)
size_t lcd_print_uint64_xy_str (uint8_t x, uint8_t y, const char *str, uint64_t n, int base)
size_t lcd_print_int64 (int64_t n, int base)
size_t lcd_print_int64_xy (uint8_t x, uint8_t y, int64_t n, int base)
size_t lcd_print_int64_str (const char *str, int64_t n, int base)
size_t lcd_print_int64_xy_str (uint8_t x, uint8_t y, const char *str, int64_t n, int base)
size_t lcd_print_double (double n, int digits)
size_t lcd_print_double_xy (uint8_t x, uint8_t y, double n, int digits)
size_t lcd_print_double_str (const char *str, double n, int digits)
size_t lcd_print_double_xy_str (uint8_t x, uint8_t y, const char *str, double n, int digits)
void lcd_print_real (real_t t)
void lcd_print_real_str (const char *buf, real_t t)
void lcd_print_real_xy (uint8_t x, uint8_t y, real_t t)
void lcd_print_real_xy_str (uint8_t x, uint8_t y, const char *buf, real_t t)
void lcd_print_ureal (ureal_t t)
void lcd_print_ureal_str (const char *buf, ureal_t t)
void lcd_print_ureal_xy (uint8_t x, uint8_t y, ureal_t t)
void lcd_print_ureal_xy_str (uint8_t x, uint8_t y, const char *buf, ureal_t t)
void lcd_print_minute (minute_t p)
void lcd_print_minute_xy (uint8_t x, uint8_t y, minute_t p)
void lcd_print_minute_str (const char *buf, minute_t p)
void lcd_print_minute_xy_str (uint8_t x, uint8_t y, const char *buf, minute_t p)
void lcd_print_hour (hour_t p)
void lcd_print_hour_xy (uint8_t x, uint8_t y, hour_t p)
void lcd_print_hour_str (const char *buf, hour_t p)
void lcd_print_hour_xy_str (uint8_t x, uint8_t y, const char *buf, hour_t p)
void lcd_print_period (period_t p)
void lcd_print_period_xy (uint8_t x, uint8_t y, period_t p)
void lcd_print_period_str (const char *buf, period_t p)
void lcd_print_period_xy_str (uint8_t x, uint8_t y, const char *buf, period_t p)
void lcd_print_ext_period (ext_period_t p)
void lcd_print_ext_period_xy (uint8_t x, uint8_t y, ext_period_t p)
void lcd_print_ext_period_str (const char *buf, ext_period_t p)
void lcd_print_ext_period_xy_str (uint8_t x, uint8_t y, const char *buf, ext_period_t p)
void lcd_print_time (_time_t p)
void lcd_print_time_xy (uint8_t x, uint8_t y, _time_t p)
void lcd_print_time_str (const char *buf, _time_t p)
void lcd_print_time_xy_str (uint8_t x, uint8_t y, const char *buf, _time_t p)
void lcd_print_date (date_t p)
void lcd_print_date_xy (uint8_t x, uint8_t y, date_t p)
void lcd_print_date_str (const char *buf, date_t p)
void lcd_print_date_xy_str (uint8_t x, uint8_t y, const char *buf, date_t p)
void lcd_print_datetime (datetime_t p)
void lcd_print_datetime_xy (uint8_t x, uint8_t y, datetime_t p)
void lcd_print_datetime_str (const char *buf, datetime_t p)
void lcd_print_datetime_xy_str (uint8_t x, uint8_t y, const char *buf, datetime_t p)
void lcd_blank_line (uint8_t steps)
Variables
const unsigned char bcd_tbl [] ="0123456789ABCDEF"
lcd.c
const uint8_t lcd_line_cnt_max =4
const uint8_t lcd_col_cnt_max =16
uint8_t lcd_line_cnt
uint8_t lcd_col_cnt
coordinate_t lcd_coord
lcd_options_t lcd_options
GLCD_FLAG_t lcd_flag
volatile uint8_t lcd_buf [2][16] ={0}
gpio_t lcd_db [8]
gpio_t lcd_rs ={GPIOB,9}
gpio_t lcd_en ={GPIOB,8}
Function Documentation
lcd_blank_line()
void lcd_blank_line (uint8_t steps)
Definition at line 1233 of file lcd.c.
{
    uint8_t i=0;
    uint8_t cnt= lcd_col_cnt;//lcd_get_colums_cnt();
    uint8_t stop=lcd_coord.x+steps;
    if(stop>cnt)
     stop=cnt;
for (i=0;i<stop;i++)
    lcd_print(" ");
}
References lcd_col_cnt, lcd_coord, lcd_print(), and coordinate_t::x.
lcd_clear()
void lcd_clear ()
Definition at line 299 of file lcd.c.
{
    lcd_write_cmd(CMD_CLR);
    _delay_ms(3);
}
References _delay_ms(), CMD_CLR, and lcd_write_cmd().
Referenced by lcd_init().
lcd_clear_line()
void lcd_clear_line (uint8_t index)
Definition at line 442 of file lcd.c.
{
}
lcd_cursor_blink()
void lcd_cursor_blink ()
Definition at line 320 of file lcd.c.
{
   lcd_write_cmd(display_on_cursor_on_blink_on);
}
References display_on_cursor_on_blink_on, and lcd_write_cmd().
lcd_cursor_home()
void lcd_cursor_home ()
Definition at line 305 of file lcd.c.
{
    lcd_write_cmd(CMD_HOME);
}
References CMD_HOME, and lcd_write_cmd().
lcd_cursor_off()
void lcd_cursor_off ()
Definition at line 315 of file lcd.c.
{
  lcd_write_cmd(display_on_cursor_off_blink_off);
}
References display_on_cursor_off_blink_off, and lcd_write_cmd().
lcd_cursor_on()
void lcd_cursor_on ()
Definition at line 310 of file lcd.c.
{
    lcd_write_cmd(display_on_cursor_on_blink_off);
}
References display_on_cursor_on_blink_off, and lcd_write_cmd().
lcd_cursor_shift_left()
void lcd_cursor_shift_left ()
Definition at line 325 of file lcd.c.
{
    lcd_write_cmd(CUR_SHL);
}
References CUR_SHL, and lcd_write_cmd().
lcd_cursor_shift_right()
void lcd_cursor_shift_right ()
Definition at line 330 of file lcd.c.
{
    lcd_write_cmd(CUR_SHR);
}
References CUR_SHR, and lcd_write_cmd().
lcd_display_shift_left()
void lcd_display_shift_left ()
Definition at line 335 of file lcd.c.
{
    lcd_write_cmd(DISP_SHL);
}
References DISP_SHL, and lcd_write_cmd().
lcd_display_shift_right()
void lcd_display_shift_right ()
Definition at line 340 of file lcd.c.
{
    lcd_write_cmd(DISP_SHR);
}
References DISP_SHR, and lcd_write_cmd().
lcd_en_clear()
void lcd_en_clear (void) static
Definition at line 183 of file lcd.c.
{
   gpio_clear(lcd_en); //GPIO_ResetBits(lcd_en.port,(uint32_t)(1<<lcd_en.pin));
}
References gpio_clear(), and lcd_en.
Referenced by lcd_read_byte(), and lcd_write_byte().
lcd_en_pinmode_in()
void lcd_en_pinmode_in (void) static
Definition at line 171 of file lcd.c.
{
   //gpio_pinmode(lcd_en,GPIO_Mode_IPU,0);
   gpio_in_pullup(lcd_en);
}
References gpio_in_pullup(), and lcd_en.
lcd_en_pinmode_out()
void lcd_en_pinmode_out (void) static
Definition at line 177 of file lcd.c.
{
  //gpio_pinmode(lcd_en,GPIO_Mode_Out_PP,GPIO_Speed_2MHz);
  gpio_pin_mode(lcd_en,GPIO_MODE_OUT_PP_2MHZ);
}
References GPIO_MODE_OUT_PP_2MHZ, gpio_pin_mode(), and lcd_en.
Referenced by lcd_refresh().
lcd_en_set()
void lcd_en_set (void) static
Definition at line 188 of file lcd.c.
{
  gpio_set(lcd_en);  //GPIO_SetBits(lcd_en.port,(uint32_t)(1<<lcd_en.pin));
}
References gpio_set(), and lcd_en.
Referenced by lcd_read_byte(), and lcd_write_byte().
lcd_entery_mode_decrement()
void lcd_entery_mode_decrement ()
Definition at line 350 of file lcd.c.
{
    lcd_write_cmd(entry_mode_dec);
}
References entry_mode_dec, and lcd_write_cmd().
lcd_entery_mode_increment()
void lcd_entery_mode_increment ()
Definition at line 345 of file lcd.c.
{
    lcd_write_cmd(entry_mode_inc);
}
References entry_mode_inc, and lcd_write_cmd().
lcd_get_AC()
uint8_t lcd_get_AC ()
Definition at line 424 of file lcd.c.
 {
   uint8_t val=0;
  // read busy flag and address counter
    val=lcd_read_busy() &0x7f;
   return val;
 }
References lcd_read_busy().
lcd_goto_xy()
void lcd_goto_xy (uint8_t x, uint8_t y)
Definition at line 447 of file lcd.c.
{
 uint8_t cmd=0;
 lcd_coord.y=y%lcd_line_cnt;
 switch(lcd_coord.y)
 {
     case 0: cmd=ROW0;  break;
     case 1: cmd=ROW1;  break;
     case 2: cmd=ROW2;  break;
     case 3: cmd=ROW3;  break;
 }
 lcd_coord.x=x%lcd_col_cnt;
 cmd+=lcd_coord.x;
 lcd_write_cmd(cmd);
}
References lcd_col_cnt, lcd_coord, lcd_line_cnt, lcd_write_cmd(), ROW0, ROW1, ROW2, ROW3, coordinate_t::x, and coordinate_t::y.
Referenced by lcd_init(), lcd_print_cgram(), lcd_print_date_xy(), lcd_print_datetime_xy(), lcd_print_double_xy(), lcd_print_double_xy_str(), lcd_print_ext_period_xy(), lcd_print_hour_xy(), lcd_print_int64_xy(), lcd_print_int64_xy_str(), lcd_print_minute_xy(), lcd_print_period_xy(), lcd_print_real_xy(), lcd_print_time_xy(), lcd_print_uint64_xy(), lcd_print_uint64_xy_str(), lcd_print_ureal_xy(), lcd_print_xy(), and lcd_write().
lcd_init()
void lcd_init (void)
Definition at line 373 of file lcd.c.
{
    // initiate coordinates
    lcd_coord.x=0;
    lcd_coord.y=0;
    lcd_line_cnt=2;
    lcd_col_cnt=16;
    // lcd refresh
    lcd_refresh();
    // clear lcd
    lcd_clear();
    lcd_goto_xy(0,0);
}
References lcd_clear(), lcd_col_cnt, lcd_coord, lcd_goto_xy(), lcd_line_cnt, lcd_refresh(), coordinate_t::x, and coordinate_t::y.
Referenced by system_init().
lcd_init_cgram()
void lcd_init_cgram (uint8_t * pattern, uint8_t num)
Definition at line 520 of file lcd.c.
{
  uint8_t i=0;
  uint8_t address=CG_RAM|((num<<3)&0xf8);
  lcd_write_cmd(address);
  for(i=0;i<8;i++)
    lcd_write_data(pattern[i]);
}
References CG_RAM, lcd_write_cmd(), and lcd_write_data().
lcd_is_busy()
uint8_t lcd_is_busy ()
Definition at line 415 of file lcd.c.
 {
  // read busy flag and address counter
  lcd_read_busy();
  if(lcd_flag.BF)
     return 1;
  return 0;
 }
References GLCD_FLAG_t::BF, lcd_flag, and lcd_read_busy().
lcd_port_pinmode_in()
void lcd_port_pinmode_in (void) static
Definition at line 97 of file lcd.c.
{
    for (uint8_t i=0;i<8;i++)
    {
        //gpio_pinmode(lcd_db[i],GPIO_Mode_IPU,0);             //db[i].pinmode(GPIO_Mode_IPU);
        //lcd_db[i].port->ODR|= (uint16_t)(1<<lcd_db[i].pin);  //db[i].pull_up();
        //gpio_pin_mode(lcd_db[i],GPIO_MODE_IN_PUPD);
        gpio_in_pullup(lcd_db[i]);
    }
}
References gpio_in_pullup(), and lcd_db.
Referenced by lcd_read_byte().
lcd_port_pinmode_out()
void lcd_port_pinmode_out (void) static
Definition at line 112 of file lcd.c.
{
    // Make GLCD Port as a Digital Output
    for(uint8_t i=0;i<8;i++)
    //gpio_pinmode(lcd_db[i],GPIO_Mode_Out_PP,GPIO_Speed_2MHz);
    gpio_pin_mode(lcd_db[i],GPIO_MODE_OUT_PP_2MHZ);
}
References GPIO_MODE_OUT_PP_2MHZ, gpio_pin_mode(), and lcd_db.
Referenced by lcd_write_byte().
lcd_port_read_byte()
uint8_t lcd_port_read_byte (void) static
Definition at line 133 of file lcd.c.
{
   uint8_t val=0;
   uint8_t i=0;
    for (i=0;i<8;i++)
    {
        //GPIO_ReadInputDataBit(lcd_db[i].port,(uint32_t)(1<<lcd_db[i].pin)))
        if (gpio_get(lcd_db[i]))
        sbit(val,i);
        else
        cbit(val,i);
    }
    return val;
}
References cbit, gpio_get(), lcd_db, and sbit.
Referenced by lcd_read_byte().
lcd_port_write_byte()
void lcd_port_write_byte (uint8_t b) static
Definition at line 120 of file lcd.c.
{
 for(uint8_t i=0;i<8;i++)
 {
  if(bit_is_set(val,i))
      gpio_set(lcd_db[i]);  //GPIO_SetBits(lcd_db[i].port,(uint32_t)(1<<lcd_db[i].pin));
  else
      gpio_clear(lcd_db[i]);//GPIO_ResetBits(lcd_db[i].port,(uint32_t)(1<<lcd_db[i].pin));
  }
}
References bit_is_set, gpio_clear(), gpio_set(), and lcd_db.
Referenced by lcd_write_byte().
lcd_print()
size_t lcd_print (const char * str)
Definition at line 693 of file lcd.c.
{
    return lcd_write_cstr(str);
}
References lcd_write_cstr().
Referenced by lcd_blank_line(), lcd_print_as_Float(), lcd_print_date(), lcd_print_date_str(), lcd_print_datetime(), lcd_print_datetime_str(), lcd_print_double_str(), lcd_print_ext_period(), lcd_print_ext_period_str(), lcd_print_hour(), lcd_print_hour_str(), lcd_print_int64_str(), lcd_print_minute(), lcd_print_minute_str(), lcd_print_period(), lcd_print_period_str(), lcd_print_real(), lcd_print_real_str(), lcd_print_time(), lcd_print_time_str(), lcd_print_uint64_str(), lcd_print_ureal(), lcd_print_ureal_str(), lcd_print_xy(), lcd_printf(), lcd_task(), and lcd_write_num().
lcd_print_array()
size_t lcd_print_array (uint8_t buf[], uint8_t len)
Definition at line 612 of file lcd.c.
{
    return lcd_write_array(buf,len);
}
References lcd_write_array().
lcd_print_as_Float()
size_t lcd_print_as_Float (double n, uint8_t digits) static
Definition at line 637 of file lcd.c.
{
    size_t n = 0;
    uint8_t i=0;
    if (isnan(number)) return lcd_print("nan");
    if (isinf(number)) return lcd_print("inf");
    if (number > 4294967040.0) return lcd_print ("ovf");  // constant determined empirically
    if (number <-4294967040.0) return lcd_print ("ovf");  // constant determined empirically
    // Handle negative numbers
    if (number < 0.0)
    {
        n += lcd_print_ch('-');
        number = -number;
    }
    // Round correctly so that print(1.999, 2) prints as "2.00"
    double rounding = 0.5;
    for (i=0; i<digits; ++i)
        rounding /= 10.0;
    number += rounding;
    // Extract the integer part of the number and print it
    unsigned long int_part = (unsigned long)number;
    double remainder = number - (double)int_part;
    n += lcd_print_int64(int_part,10);
    // Print the decimal point, but only if there are digits beyond
    if (digits > 0) {
        n += lcd_print_ch('.');
    }
    // Extract digits from the remainder one at a time
    while (digits-- > 0)
    {
        remainder *= 10.0;
        unsigned int toPrint = (unsigned int)(remainder);
        n += lcd_print_uint16((uint16_t)toPrint,10);
        remainder -= toPrint;
    }
    return n;
}
References lcd_print(), lcd_print_ch(), lcd_print_int64(), and lcd_print_uint16().
Referenced by lcd_print_double().
lcd_print_as_number()
size_t lcd_print_as_number (unsigned long long n, uint8_t base) static
Definition at line 617 of file lcd.c.
{
    char buf[8 * sizeof(long long) + 1]; // Assumes 8-bit chars plus zero byte.
    char *str = &buf[sizeof(buf) - 1];
    *str = '\0';
    // prevent crash if called with base == 1
    if (base < 2) base = 10;
    do {
        char c = n % base;
        n /= base;
        *--str = c < 10 ? c + '0' : c + 'A' - 10;
    } while(n);
    return lcd_write_cstr(str);
}
References lcd_write_cstr().
Referenced by lcd_print_int64(), and lcd_print_uint64().
lcd_print_cgram()
void lcd_print_cgram (uint8_t x, uint8_t y, uint8_t pattern)
Definition at line 529 of file lcd.c.
{
 // goto to xy position
   lcd_goto_xy(x,y);
 // goto to xy position
   lcd_write_data(pattern);
}
References lcd_goto_xy(), and lcd_write_data().
lcd_print_ch()
size_t lcd_print_ch (char c)
Definition at line 688 of file lcd.c.
{
    return lcd_write(c);
}
References lcd_write().
Referenced by lcd_print_as_Float(), and lcd_print_int64().
lcd_print_date()
void lcd_print_date (date_t p)
Definition at line 1180 of file lcd.c.
{
  lcd_print_uint64((uint64_t)p.day,10);
  lcd_print("/");
  lcd_print_uint64((uint64_t)p.month,10);
  lcd_print("/");
  lcd_print_uint64((uint64_t)p.year,10);
  lcd_print(" ");
}
References date_t::day, lcd_print(), lcd_print_uint64(), date_t::month, and date_t::year.
Referenced by lcd_print_date_str(), lcd_print_date_xy(), lcd_print_date_xy_str(), and lcd_print_datetime().
lcd_print_date_str()
void lcd_print_date_str (const char * buf, date_t p)
Definition at line 1196 of file lcd.c.
{
 lcd_print(buf);
 lcd_print_date(p);
}
References lcd_print(), and lcd_print_date().
lcd_print_date_xy()
void lcd_print_date_xy (uint8_t x, uint8_t y, date_t p)
Definition at line 1190 of file lcd.c.
{
  lcd_goto_xy(x,y);
  lcd_print_date(p);
}
References lcd_goto_xy(), and lcd_print_date().
lcd_print_date_xy_str()
void lcd_print_date_xy_str (uint8_t x, uint8_t y, const char * buf, date_t p)
Definition at line 1202 of file lcd.c.
{
 lcd_print_xy(x,y,buf);
 lcd_print_date(p);
}
References lcd_print_date(), and lcd_print_xy().
lcd_print_datetime()
void lcd_print_datetime (datetime_t p)
Definition at line 1208 of file lcd.c.
{
 lcd_print_date(p.date);
 lcd_print(" ");
 lcd_print_time(p.time);
}
References datetime_t::date, lcd_print(), lcd_print_date(), lcd_print_time(), and datetime_t::time.
Referenced by lcd_print_datetime_str(), lcd_print_datetime_xy(), and lcd_print_datetime_xy_str().
lcd_print_datetime_str()
void lcd_print_datetime_str (const char * buf, datetime_t p)
Definition at line 1221 of file lcd.c.
{
  lcd_print(buf);
  lcd_print_datetime(p);
}
References lcd_print(), and lcd_print_datetime().
lcd_print_datetime_xy()
void lcd_print_datetime_xy (uint8_t x, uint8_t y, datetime_t p)
Definition at line 1215 of file lcd.c.
{
  lcd_goto_xy(x,y);
  lcd_print_datetime(p);
}
References lcd_goto_xy(), and lcd_print_datetime().
lcd_print_datetime_xy_str()
void lcd_print_datetime_xy_str (uint8_t x, uint8_t y, const char * buf, datetime_t p)
Definition at line 1227 of file lcd.c.
{
 lcd_print_xy(x,y,buf);
 lcd_print_datetime(p);
}
References lcd_print_datetime(), and lcd_print_xy().
lcd_print_double()
size_t lcd_print_double (double n, int digits)
Definition at line 953 of file lcd.c.
{
  return lcd_print_as_Float(n, digits);
}
References lcd_print_as_Float().
Referenced by lcd_print_double_str(), and lcd_print_double_xy().
lcd_print_double_str()
size_t lcd_print_double_str (const char * str, double n, int digits)
Definition at line 964 of file lcd.c.
{
 int len=lcd_print(str);
 return lcd_print_double(n, digits)+len;
}
References lcd_print(), and lcd_print_double().
Referenced by lcd_print_double_xy_str().
lcd_print_double_xy()
size_t lcd_print_double_xy (uint8_t x, uint8_t y, double n, int digits)
Definition at line 958 of file lcd.c.
{
    lcd_goto_xy(x,y);
    return lcd_print_double(n, digits);
}
References lcd_goto_xy(), and lcd_print_double().
lcd_print_double_xy_str()
size_t lcd_print_double_xy_str (uint8_t x, uint8_t y, const char * str, double n, int digits)
Definition at line 970 of file lcd.c.
{
    lcd_goto_xy(x,y);
    return lcd_print_double_str(str,n, digits);
}
References lcd_goto_xy(), and lcd_print_double_str().
lcd_print_ext_period()
void lcd_print_ext_period (ext_period_t p)
Definition at line 1119 of file lcd.c.
{
    lcd_print_uint64((uint64_t)p.hour,10);
    lcd_print(":");
    lcd_print_uint64((uint64_t)p.minute,10);
    lcd_print(":");
    lcd_print_uint64((uint64_t)p.second,10);
    lcd_print(" ");
}
References ext_period_t::hour, lcd_print(), lcd_print_uint64(), ext_period_t::minute, and ext_period_t::second.
Referenced by lcd_print_ext_period_str(), lcd_print_ext_period_xy(), and lcd_print_ext_period_xy_str().
lcd_print_ext_period_str()
void lcd_print_ext_period_str (const char * buf, ext_period_t p)
Definition at line 1135 of file lcd.c.
{
    lcd_print(buf);
    lcd_print_ext_period(p);
}
References lcd_print(), and lcd_print_ext_period().
lcd_print_ext_period_xy()
void lcd_print_ext_period_xy (uint8_t x, uint8_t y, ext_period_t p)
Definition at line 1129 of file lcd.c.
{
    lcd_goto_xy(x,y);
    lcd_print_ext_period(p);
}
References lcd_goto_xy(), and lcd_print_ext_period().
lcd_print_ext_period_xy_str()
void lcd_print_ext_period_xy_str (uint8_t x, uint8_t y, const char * buf, ext_period_t p)
Definition at line 1141 of file lcd.c.
{
    lcd_print_xy(x,y,buf);
    lcd_print_ext_period(p);
}
References lcd_print_ext_period(), and lcd_print_xy().
lcd_print_hour()
void lcd_print_hour (hour_t p)
Definition at line 1067 of file lcd.c.
{
    lcd_print_uint64((uint64_t)p.hour,10);
    lcd_print(":");
    lcd_print_uint64((uint64_t)p.minute,10);
    lcd_print(" ");
}
References hour_t::hour, lcd_print(), lcd_print_uint64(), and hour_t::minute.
Referenced by lcd_print_hour_str(), lcd_print_hour_xy(), and lcd_print_hour_xy_str().
lcd_print_hour_str()
void lcd_print_hour_str (const char * buf, hour_t p)
Definition at line 1081 of file lcd.c.
{
    lcd_print(buf);
    lcd_print_hour(p);
}
References lcd_print(), and lcd_print_hour().
lcd_print_hour_xy()
void lcd_print_hour_xy (uint8_t x, uint8_t y, hour_t p)
Definition at line 1075 of file lcd.c.
{
    lcd_goto_xy(x,y);
    lcd_print_hour(p);
}
References lcd_goto_xy(), and lcd_print_hour().
lcd_print_hour_xy_str()
void lcd_print_hour_xy_str (uint8_t x, uint8_t y, const char * buf, hour_t p)
Definition at line 1087 of file lcd.c.
{
    lcd_print_xy(x,y,buf);
    lcd_print_hour(p);
}
References lcd_print_hour(), and lcd_print_xy().
lcd_print_int16()
size_t lcd_print_int16 (int16_t n, int base)
Definition at line 816 of file lcd.c.
{
    return lcd_print_int64((int64_t) n, base);
}
References lcd_print_int64().
lcd_print_int16_str()
size_t lcd_print_int16_str (const char * str, int16_t n, int base)
Definition at line 826 of file lcd.c.
{
    return lcd_print_int64_str(str,(int64_t) n, base);
}
References lcd_print_int64_str().
lcd_print_int16_xy()
size_t lcd_print_int16_xy (uint8_t x, uint8_t y, int16_t n, int base)
Definition at line 821 of file lcd.c.
{
    return lcd_print_int64_xy(x,y,(int64_t) n, base);
}
References lcd_print_int64_xy().
lcd_print_int16_xy_str()
size_t lcd_print_int16_xy_str (uint8_t x, uint8_t y, const char * str, int16_t n, int base)
Definition at line 831 of file lcd.c.
{
  return lcd_print_int64_xy_str(x,y,str,(int64_t) n, base);
}
References lcd_print_int64_xy_str().
lcd_print_int32()
size_t lcd_print_int32 (int32_t n, int base)
Definition at line 861 of file lcd.c.
{
    return lcd_print_int64((int64_t) n, base);
}
References lcd_print_int64().
lcd_print_int32_str()
size_t lcd_print_int32_str (const char * str, int32_t n, int base)
Definition at line 871 of file lcd.c.
{
    return lcd_print_int64_str(str,(int64_t) n, base);
}
References lcd_print_int64_str().
lcd_print_int32_xy()
size_t lcd_print_int32_xy (uint8_t x, uint8_t y, int32_t n, int base)
Definition at line 866 of file lcd.c.
{
    return lcd_print_int64_xy(x,y,(int64_t) n, base);
}
References lcd_print_int64_xy().
lcd_print_int32_xy_str()
size_t lcd_print_int32_xy_str (uint8_t x, uint8_t y, const char * str, int32_t n, int base)
Definition at line 876 of file lcd.c.
{
    return lcd_print_int64_xy_str(x,y,str,(int64_t) n, base);
}
References lcd_print_int64_xy_str().
lcd_print_int64()
size_t lcd_print_int64 (int64_t n, int base)
Definition at line 913 of file lcd.c.
{
if (base == 0) return lcd_write(n);
 else if (base == 10)
 {
     if (n < 0)
     {
         int t = lcd_print_ch('-');
         n = -n;
         return lcd_print_as_number(n, 10) + t;
     }
     return lcd_print_as_number(n, 10);
 }
 else
     return lcd_print_as_number(n, 10);
}
References lcd_print_as_number(), lcd_print_ch(), and lcd_write().
Referenced by lcd_print_as_Float(), lcd_print_int16(), lcd_print_int32(), lcd_print_int64_str(), lcd_print_int64_xy(), and lcd_print_int8_t().
lcd_print_int64_str()
size_t lcd_print_int64_str (const char * str, int64_t n, int base)
Definition at line 936 of file lcd.c.
{
    int len=lcd_print(str);
    return lcd_print_int64((int64_t) n, base)+len;
}
References lcd_print(), and lcd_print_int64().
Referenced by lcd_print_int16_str(), lcd_print_int32_str(), lcd_print_int64_xy_str(), and lcd_print_int8_str().
lcd_print_int64_xy()
size_t lcd_print_int64_xy (uint8_t x, uint8_t y, int64_t n, int base)
Definition at line 930 of file lcd.c.
{
  lcd_goto_xy(x,y);
  return lcd_print_int64((int64_t) n, base);
}
References lcd_goto_xy(), and lcd_print_int64().
Referenced by lcd_print_int16_xy(), lcd_print_int32_xy(), and lcd_print_int8_xy().
lcd_print_int64_xy_str()
size_t lcd_print_int64_xy_str (uint8_t x, uint8_t y, const char * str, int64_t n, int base)
Definition at line 942 of file lcd.c.
{
    lcd_goto_xy(x,y);
    return lcd_print_int64_str(str,(int64_t) n, base);
}
References lcd_goto_xy(), and lcd_print_int64_str().
Referenced by lcd_print_int16_xy_str(), lcd_print_int32_xy_str(), and lcd_print_int8_xy_str().
lcd_print_int8_str()
size_t lcd_print_int8_str (const char * str, int8_t n, int base)
Definition at line 781 of file lcd.c.
{
    return lcd_print_int64_str(str,(int64_t) n, base);
}
References lcd_print_int64_str().
lcd_print_int8_t()
size_t lcd_print_int8_t (int8_t n, int base)
Definition at line 771 of file lcd.c.
{
    return lcd_print_int64((int64_t) n, base);
}
References lcd_print_int64().
lcd_print_int8_xy()
size_t lcd_print_int8_xy (uint8_t x, uint8_t y, int8_t n, int base)
Definition at line 776 of file lcd.c.
{
    return lcd_print_int64_xy(x,y,(int64_t) n, base);
}
References lcd_print_int64_xy().
lcd_print_int8_xy_str()
size_t lcd_print_int8_xy_str (uint8_t x, uint8_t y, const char * str, int8_t n, int base)
Definition at line 786 of file lcd.c.
{
    return lcd_print_int64_xy_str(x,y,str,(int64_t) n, base);
}
References lcd_print_int64_xy_str().
lcd_print_minute()
void lcd_print_minute (minute_t p)
Definition at line 1041 of file lcd.c.
{
    lcd_print_uint64((uint64_t)p.min,10);
    lcd_print(":");
    lcd_print_uint64((uint64_t)p.sec,10);
    lcd_print(" ");
}
References lcd_print(), lcd_print_uint64(), minute_t::min, and minute_t::sec.
Referenced by lcd_print_minute_str(), lcd_print_minute_xy(), and lcd_print_minute_xy_str().
lcd_print_minute_str()
void lcd_print_minute_str (const char * buf, minute_t p)
Definition at line 1055 of file lcd.c.
{
    lcd_print(buf);
    lcd_print_minute(p);
}
References lcd_print(), and lcd_print_minute().
lcd_print_minute_xy()
void lcd_print_minute_xy (uint8_t x, uint8_t y, minute_t p)
Definition at line 1049 of file lcd.c.
{
    lcd_goto_xy(x,y);
    lcd_print_minute(p);
}
References lcd_goto_xy(), and lcd_print_minute().
lcd_print_minute_xy_str()
void lcd_print_minute_xy_str (uint8_t x, uint8_t y, const char * buf, minute_t p)
Definition at line 1061 of file lcd.c.
{
    lcd_print_xy(x,y,buf);
    lcd_print_minute(p);
}
References lcd_print_minute(), and lcd_print_xy().
lcd_print_period()
void lcd_print_period (period_t p)
Definition at line 1093 of file lcd.c.
{
    lcd_print_uint64((uint64_t)p.hour,10);
    lcd_print(":");
    lcd_print_uint64((uint64_t)p.minute,10);
    lcd_print(" ");
}
References period_t::hour, lcd_print(), lcd_print_uint64(), and period_t::minute.
Referenced by lcd_print_period_str(), lcd_print_period_xy(), and lcd_print_period_xy_str().
lcd_print_period_str()
void lcd_print_period_str (const char * buf, period_t p)
Definition at line 1107 of file lcd.c.
{
    lcd_print(buf);
    lcd_print_period(p);
}
References lcd_print(), and lcd_print_period().
lcd_print_period_xy()
void lcd_print_period_xy (uint8_t x, uint8_t y, period_t p)
Definition at line 1101 of file lcd.c.
{
    lcd_goto_xy(x,y);
    lcd_print_period(p);
}
References lcd_goto_xy(), and lcd_print_period().
lcd_print_period_xy_str()
void lcd_print_period_xy_str (uint8_t x, uint8_t y, const char * buf, period_t p)
Definition at line 1113 of file lcd.c.
{
    lcd_print_xy(x,y,buf);
    lcd_print_period(p);
}
References lcd_print_period(), and lcd_print_xy().
lcd_print_real()
void lcd_print_real (real_t t)
Definition at line 981 of file lcd.c.
{
    if(t.sig==1)
    lcd_print("-");
    lcd_print_uint64((uint64_t)t.integer,10);
    lcd_print(".");
    lcd_print_uint64((uint64_t)t.decimal,10);
    lcd_print(" ");
}
References real_t::decimal, real_t::integer, lcd_print(), lcd_print_uint64(), and real_t::sig.
Referenced by lcd_print_real_str(), lcd_print_real_xy(), and lcd_print_real_xy_str().
lcd_print_real_str()
void lcd_print_real_str (const char * buf, real_t t)
Definition at line 991 of file lcd.c.
{
    lcd_print(buf);
    lcd_print_real(t);
}
References lcd_print(), and lcd_print_real().
lcd_print_real_xy()
void lcd_print_real_xy (uint8_t x, uint8_t y, real_t t)
Definition at line 997 of file lcd.c.
{
    lcd_goto_xy(x,y);
    lcd_print_real(t);
}
References lcd_goto_xy(), and lcd_print_real().
lcd_print_real_xy_str()
void lcd_print_real_xy_str (uint8_t x, uint8_t y, const char * buf, real_t t)
Definition at line 1003 of file lcd.c.
{
    lcd_print_xy(x,y,buf);
    lcd_print_real(t);
}
References lcd_print_real(), and lcd_print_xy().
lcd_print_time()
void lcd_print_time (_time_t p)
Definition at line 1147 of file lcd.c.
{
  lcd_print_uint64((uint64_t)p.hour,10);
  lcd_print(":");
  lcd_print_uint64((uint64_t)p.minute,10);
  lcd_print(":");
  lcd_print_uint64((uint64_t)p.sec,10);
  lcd_print(" ");
  if(p.am_pm_mode==1)
   lcd_print("AM");
 else if(p.am_pm_mode==2)
   lcd_print(" PM");
  lcd_print(" ");
}
References _time_t::am_pm_mode, _time_t::hour, lcd_print(), lcd_print_uint64(), _time_t::minute, and _time_t::sec.
Referenced by lcd_print_datetime(), lcd_print_time_str(), lcd_print_time_xy(), and lcd_print_time_xy_str().
lcd_print_time_str()
void lcd_print_time_str (const char * buf, _time_t p)
Definition at line 1168 of file lcd.c.
{
 lcd_print(buf);
 lcd_print_time(p);
}
References lcd_print(), and lcd_print_time().
lcd_print_time_xy()
void lcd_print_time_xy (uint8_t x, uint8_t y, _time_t p)
Definition at line 1162 of file lcd.c.
{
  lcd_goto_xy(x,y);
  lcd_print_time(p);
}
References lcd_goto_xy(), and lcd_print_time().
lcd_print_time_xy_str()
void lcd_print_time_xy_str (uint8_t x, uint8_t y, const char * buf, _time_t p)
Definition at line 1174 of file lcd.c.
{
  lcd_print_xy(x,y,buf);
  lcd_print_time(p);
}
References lcd_print_time(), and lcd_print_xy().
lcd_print_uint16()
size_t lcd_print_uint16 (uint16_t n, int base)
Definition at line 796 of file lcd.c.
{
    return lcd_print_uint64((uint64_t) n, base);
}
References lcd_print_uint64().
Referenced by lcd_print_as_Float().
lcd_print_uint16_str()
size_t lcd_print_uint16_str (const char * str, uint16_t n, int base)
Definition at line 806 of file lcd.c.
{
    return lcd_print_uint64_str(str,(uint64_t) n, base);
}
References lcd_print_uint64_str().
lcd_print_uint16_xy()
size_t lcd_print_uint16_xy (uint8_t x, uint8_t y, uint16_t n, int base)
Definition at line 801 of file lcd.c.
{
    return lcd_print_uint64_xy(x,y,(uint64_t) n, base);
}
References lcd_print_uint64_xy().
lcd_print_uint16_xy_str()
size_t lcd_print_uint16_xy_str (uint8_t x, uint8_t y, const char * str, uint16_t n, int base)
Definition at line 811 of file lcd.c.
{
    return lcd_print_uint64_xy_str(x,y,str,(uint64_t) n, base);
}
References lcd_print_uint64_xy_str().
lcd_print_uint32()
size_t lcd_print_uint32 (uint32_t n, int base)
Definition at line 841 of file lcd.c.
{
  return lcd_print_uint64((uint64_t) n, base);
}
References lcd_print_uint64().
lcd_print_uint32_str()
size_t lcd_print_uint32_str (const char * str, uint32_t n, int base)
Definition at line 851 of file lcd.c.
{
    return lcd_print_uint64_str(str,(uint64_t) n, base);
}
References lcd_print_uint64_str().
lcd_print_uint32_xy()
size_t lcd_print_uint32_xy (uint8_t x, uint8_t y, uint32_t n, int base)
Definition at line 846 of file lcd.c.
{
  return lcd_print_uint64_xy(x,y,(uint64_t) n, base);
}
References lcd_print_uint64_xy().
lcd_print_uint32_xy_str()
size_t lcd_print_uint32_xy_str (uint8_t x, uint8_t y, const char * str, uint32_t n, int base)
Definition at line 856 of file lcd.c.
{
    return lcd_print_uint64_xy_str(x,y,str,(uint64_t) n, base);
}
References lcd_print_uint64_xy_str().
lcd_print_uint64()
size_t lcd_print_uint64 (uint64_t n, int base)
Definition at line 886 of file lcd.c.
{
   if (base == 0)
     return lcd_write(n);
   else
     return lcd_print_as_number(n,base);
}
References lcd_print_as_number(), and lcd_write().
Referenced by lcd_print_date(), lcd_print_ext_period(), lcd_print_hour(), lcd_print_minute(), lcd_print_period(), lcd_print_real(), lcd_print_time(), lcd_print_uint16(), lcd_print_uint32(), lcd_print_uint64_str(), lcd_print_uint64_xy(), lcd_print_uint8(), and lcd_print_ureal().
lcd_print_uint64_str()
size_t lcd_print_uint64_str (const char * str, uint64_t n, int base)
Definition at line 900 of file lcd.c.
{
    int len=0;
    len=lcd_print(str);
    return lcd_print_uint64((uint64_t) n, base)+len;
}
References lcd_print(), and lcd_print_uint64().
Referenced by lcd_print_uint16_str(), lcd_print_uint32_str(), lcd_print_uint64_xy_str(), and lcd_print_uint8_str().
lcd_print_uint64_xy()
size_t lcd_print_uint64_xy (uint8_t x, uint8_t y, uint64_t n, int base)
Definition at line 894 of file lcd.c.
{
  lcd_goto_xy(x,y);
  return lcd_print_uint64((uint64_t) n, base);
}
References lcd_goto_xy(), and lcd_print_uint64().
Referenced by lcd_print_uint16_xy(), lcd_print_uint32_xy(), and lcd_print_uint8_xy().
lcd_print_uint64_xy_str()
size_t lcd_print_uint64_xy_str (uint8_t x, uint8_t y, const char * str, uint64_t n, int base)
Definition at line 907 of file lcd.c.
{
    lcd_goto_xy(x,y);
    return lcd_print_uint64_str(str,(uint64_t) n, base);
}
References lcd_goto_xy(), and lcd_print_uint64_str().
Referenced by lcd_print_uint16_xy_str(), lcd_print_uint32_xy_str(), and lcd_print_uint8_xy_str().
lcd_print_uint8()
size_t lcd_print_uint8 (uint8_t n, int base)
Definition at line 751 of file lcd.c.
{
    return lcd_print_uint64((uint64_t) n, base);
}
References lcd_print_uint64().
Referenced by lcd_task().
lcd_print_uint8_str()
size_t lcd_print_uint8_str (const char * str, uint8_t n, int base)
Definition at line 761 of file lcd.c.
{
    return lcd_print_uint64_str(str,(uint64_t) n, base);
}
References lcd_print_uint64_str().
lcd_print_uint8_xy()
size_t lcd_print_uint8_xy (uint8_t x, uint8_t y, uint8_t n, int base)
Definition at line 756 of file lcd.c.
{
    return lcd_print_uint64_xy(x,y,(uint64_t) n, base);
}
References lcd_print_uint64_xy().
lcd_print_uint8_xy_str()
size_t lcd_print_uint8_xy_str (uint8_t x, uint8_t y, const char * str, uint8_t n, int base)
Definition at line 766 of file lcd.c.
{
    return lcd_print_uint64_xy_str(x,y,str,(uint64_t) n, base);
}
References lcd_print_uint64_xy_str().
lcd_print_ureal()
void lcd_print_ureal (ureal_t t)
Definition at line 1009 of file lcd.c.
{
    lcd_print_uint64((uint64_t)t.integer,10);
    lcd_print(".");
    lcd_print_uint64((uint64_t)t.decimal,10);
    lcd_print(" ");
}
References ureal_t::decimal, ureal_t::integer, lcd_print(), and lcd_print_uint64().
Referenced by lcd_print_ureal_str(), lcd_print_ureal_xy(), and lcd_print_ureal_xy_str().
lcd_print_ureal_str()
void lcd_print_ureal_str (const char * buf, ureal_t t)
Definition at line 1017 of file lcd.c.
{
    lcd_print(buf);
    lcd_print_ureal(t);
}
References lcd_print(), and lcd_print_ureal().
lcd_print_ureal_xy()
void lcd_print_ureal_xy (uint8_t x, uint8_t y, ureal_t t)
Definition at line 1023 of file lcd.c.
{
    lcd_goto_xy(x,y);
    lcd_print_ureal(t);
}
References lcd_goto_xy(), and lcd_print_ureal().
lcd_print_ureal_xy_str()
void lcd_print_ureal_xy_str (uint8_t x, uint8_t y, const char * buf, ureal_t t)
Definition at line 1029 of file lcd.c.
{
    lcd_print_xy(x,y,buf);
    lcd_print_ureal(t);
}
References lcd_print_ureal(), and lcd_print_xy().
lcd_print_xy()
size_t lcd_print_xy (uint8_t x, uint8_t y, const char * str)
Definition at line 698 of file lcd.c.
{
    // goto to xy position
    lcd_goto_xy(x,y);
    //write lcd text buffer
    return lcd_print(str);
}
References lcd_goto_xy(), and lcd_print().
Referenced by keypad_down_key_handle(), keypad_esc_key_handle(), keypad_info_key_handle(), keypad_set_key_handle(), keypad_shft_key_handle(), keypad_up_key_handle(), lcd_print_date_xy_str(), lcd_print_datetime_xy_str(), lcd_print_ext_period_xy_str(), lcd_print_hour_xy_str(), lcd_print_minute_xy_str(), lcd_print_period_xy_str(), lcd_print_real_xy_str(), lcd_print_time_xy_str(), lcd_print_ureal_xy_str(), lcd_printf_xy(), lcd_task(), and system_init().
lcd_printf()
void lcd_printf (const char * fmt, ...)
Definition at line 711 of file lcd.c.
{
    char buf[16]="";
    va_list ptr;
    va_start(ptr,fmt);
    vsprintf(buf,fmt,ptr);
    va_end(ptr);
    lcd_print(buf);
}
References lcd_print().
lcd_printf_xy()
void lcd_printf_xy (uint8_t x, uint8_t y, const char * fmt, ...)
Definition at line 721 of file lcd.c.
{
    char buf[16]="";
    va_list ptr;
    va_start(ptr,fmt);
    vsprintf(buf,fmt,ptr);
    va_end(ptr);
    lcd_print_xy(x,y,buf);
}
References lcd_print_xy().
lcd_read_busy()
uint8_t lcd_read_busy (void) static
Definition at line 193 of file lcd.c.
{
 // instruction mode
    lcd_rs_clear();     // rs.clear();
 // read a byte from control register
  lcd_flag.val= lcd_read_byte();
 return lcd_flag.val;
}
References lcd_flag, lcd_read_byte(), lcd_rs_clear(), and GLCD_FLAG_t::val.
Referenced by lcd_get_AC(), and lcd_is_busy().
lcd_read_byte()
uint8_t lcd_read_byte (void) static
Definition at line 216 of file lcd.c.
{
  uint8_t val=0;
 //set LCD port as an input port
  lcd_port_pinmode_in();
  // select read operation on GLCD
    //rw.set();
  //enable lcd to read
   lcd_en_set();    //en.set();
   // wait dummy cycles before read
    asm("nop");
    asm("nop");
    asm("nop");
    asm("nop");
    _delay_us(1);
    // Read a value to GLCD Port
      val=lcd_port_read_byte();
    // end glcd to read operation
     lcd_en_clear(); //en.clear();
    return val;
}
References _delay_us(), lcd_en_clear(), lcd_en_set(), lcd_port_pinmode_in(), and lcd_port_read_byte().
Referenced by lcd_read_busy(), and lcd_read_data().
lcd_read_data()
uint8_t lcd_read_data (void) static
Definition at line 202 of file lcd.c.
{
  uint8_t val=0;
 // select Data mode
   lcd_rs_set(); // #rs.set();
 // read Dummy byte
  lcd_read_byte();
 // select Data mode
  lcd_rs_set(); // #rs.set();
 // read a data byte
  val= lcd_read_byte();
 return val;
}
References lcd_read_byte(), and lcd_rs_set().
lcd_refresh()
void lcd_refresh (void)
Definition at line 389 of file lcd.c.
{
 // PORTs initiate Direction
 //rw.pinmode(PIN_OUTPUT);
 lcd_rs_pinmode_out();       //rs.pinmode(GPIO_Mode_Out_PP,GPIO_Speed_2MHz);
 lcd_en_pinmode_out();       //en.pinmode(GPIO_Mode_Out_PP,GPIO_Speed_2MHz);
 // 8-bit operation and basic instruction set
 lcd_write_cmd(func8_2_10);
 //_delay_us(100);
 // 8-bit operation and basic instruction set
 lcd_write_cmd(func8_2_10);
 //_delay_us(200);
 // display on , cursor off, blink off
  lcd_write_cmd(display_on_cursor_off_blink_off);
 // _delay_us(100);
 // entry mode increment and no display shift
  lcd_write_cmd(entry_mode_inc);
 // _delay_us(100);
 // 8-bit operation and basic instruction set
  lcd_write_cmd(func8_2_10);
}
References display_on_cursor_off_blink_off, entry_mode_inc, func8_2_10, lcd_en_pinmode_out(), lcd_rs_pinmode_out(), and lcd_write_cmd().
Referenced by lcd_init(), and system_init().
lcd_rs_clear()
void lcd_rs_clear (void) static
Definition at line 161 of file lcd.c.
{
   gpio_clear(lcd_rs);//GPIO_ResetBits(lcd_rs.port,(uint32_t)(1<<lcd_rs.pin));
}
References gpio_clear(), and lcd_rs.
Referenced by lcd_read_busy(), and lcd_write_cmd().
lcd_rs_pinmode_in()
void lcd_rs_pinmode_in (void) static
Definition at line 149 of file lcd.c.
{
    //gpio_pinmode(lcd_rs,GPIO_Mode_IPU,0);
    gpio_in_pullup(lcd_rs);
}
References gpio_in_pullup(), and lcd_rs.
lcd_rs_pinmode_out()
void lcd_rs_pinmode_out (void) static
Definition at line 155 of file lcd.c.
{
   //gpio_pinmode(lcd_rs,GPIO_Mode_Out_PP,GPIO_Speed_2MHz);
   gpio_pin_mode(lcd_rs,GPIO_MODE_OUT_PP_2MHZ);
}
References GPIO_MODE_OUT_PP_2MHZ, gpio_pin_mode(), and lcd_rs.
Referenced by lcd_refresh().
lcd_rs_set()
void lcd_rs_set (void) static
Definition at line 166 of file lcd.c.
{
    gpio_set(lcd_rs);//GPIO_SetBits(lcd_rs.port,(uint32_t)(1<<lcd_rs.pin));
}
References gpio_set(), and lcd_rs.
Referenced by lcd_read_data(), and lcd_write_data().
lcd_set_display_cursor()
void lcd_set_display_cursor (uint8_t display, uint8_t cursor, uint8_t blink)
Definition at line 355 of file lcd.c.
{
    BYTE_BITS cmd;
    cmd.byte=CMD_DISP;
    if(display)
    cmd.bit2=1;
    if(cursor)
    cmd.bit1=1;
    if(blink)
    cmd.bit0=1;
    lcd_write_cmd(cmd.byte);
}
References BYTE_BITS::bit0, BYTE_BITS::bit1, BYTE_BITS::bit2, blink(), BYTE_BITS::byte, CMD_DISP, and lcd_write_cmd().
lcd_set_line()
void lcd_set_line (uint8_t index)
Definition at line 437 of file lcd.c.
{
}
lcd_write()
size_t lcd_write (uint8_t b)
Definition at line 574 of file lcd.c.
{
 switch(b)
 {
    case '\n':lcd_goto_xy(0,lcd_coord.y+1);         break; // new line
    case '\t':lcd_goto_xy(lcd_coord.x+2,lcd_coord.y);   break; // new tab
    case '\r':lcd_goto_xy(0,lcd_coord.y);           break; // cursor home
    default: lcd_write_data(b);                 break;
  }
    return 1;
}
References lcd_coord, lcd_goto_xy(), lcd_write_data(), coordinate_t::x, and coordinate_t::y.
Referenced by lcd_print_ch(), lcd_print_int64(), lcd_print_uint64(), and lcd_write_array().
lcd_write_16bit()
void lcd_write_16bit (uint16_t val)
Definition at line 472 of file lcd.c.
{
  //write high nibble of val
    lcd_write_8bit(val>>8);
 //write low nibble of val
    lcd_write_8bit(val);
}
References lcd_write_8bit().
lcd_write_8bit()
void lcd_write_8bit (uint8_t val)
Definition at line 463 of file lcd.c.
{
    uint8_t temp=val>>4;
    temp&=0x0f;
    lcd_write_data(bcd_tbl[temp]);
    temp=val&0x0f;
    lcd_write_data(bcd_tbl[temp]);
}
References bcd_tbl, and lcd_write_data().
Referenced by lcd_write_16bit().
lcd_write_array()
size_t lcd_write_array (const uint8_t * buffer, size_t size)
Definition at line 586 of file lcd.c.
{
    size_t n = 0;
    while (size--) {
    if (lcd_write(*buffer++)) n++;
    else break;
    }
    return n;
}
References lcd_write().
Referenced by lcd_print_array(), lcd_write_cstr(), and lcd_write_str().
lcd_write_bcd_16bit()
void lcd_write_bcd_16bit (uint16_t val)
Definition at line 497 of file lcd.c.
{
    uint8_t i=0;
    uint8_t Dig[5]={0};
    for(i=0;i<5;i++)
    {
        Dig[i]=val%10;
        val/=10;
    }
    if(Dig[4]!=0)
      lcd_write_data(bcd_tbl[Dig[4]]);
    if(Dig[4]!=0 ||Dig[3]!=0)
      lcd_write_data(bcd_tbl[Dig[3]]);
    if(Dig[4]!=0 ||Dig[3]!=0|| Dig[2]!=0)
      lcd_write_data(bcd_tbl[Dig[2]]);
    if(Dig[4]!=0 ||Dig[3]!=0|| Dig[2]!=0||Dig[1]!=0)
      lcd_write_data(bcd_tbl[Dig[1]]);
      lcd_write_data(bcd_tbl[Dig[0]]);
}
References bcd_tbl, and lcd_write_data().
lcd_write_bcd_8bit()
void lcd_write_bcd_8bit (uint8_t val)
Definition at line 480 of file lcd.c.
{
  uint8_t i=0;
  uint8_t Dig[3]={0};
  for(i=0;i<3;i++)
  {
    Dig[i]=val%10;
    val/=10;
  }
if(Dig[2]!=0)
 lcd_write_data(bcd_tbl[Dig[2]]);
if(Dig[2]!=0 ||Dig[1]!=0)
 lcd_write_data(bcd_tbl[Dig[1]]);
 lcd_write_data(bcd_tbl[Dig[0]]);
}
References bcd_tbl, and lcd_write_data().
lcd_write_bin()
void lcd_write_bin (uint32_t val)
Definition at line 559 of file lcd.c.
{
    uint8_t i=0;
    for(i=0;i<8;i++)
    if(bit_is_clear(val,(7-i)))
        lcd_write_data('0');
    else
        lcd_write_data('1');
}
References bit_is_clear, and lcd_write_data().
lcd_write_byte()
void lcd_write_byte (uint8_t byte) static
Definition at line 270 of file lcd.c.
{
 // Make LCD Port as a Digital Output
    lcd_port_pinmode_out();
 // select write operation on GLCD
    // rw.clear();
// Put value to GLCD Port
    lcd_port_write_byte(val);
 // enable glcd to write
    lcd_en_set(); //en.set();
    _delay_us(1);
    asm("nop");
    asm("nop");
    asm("nop");
    asm("nop");
    // end glcd  write operation
    lcd_en_clear(); //en.clear();
}
References _delay_us(), lcd_en_clear(), lcd_en_set(), lcd_port_pinmode_out(), and lcd_port_write_byte().
Referenced by lcd_write_cmd(), and lcd_write_data().
lcd_write_cmd()
void lcd_write_cmd (uint8_t cmd) static
Definition at line 246 of file lcd.c.
{
    //while(is_busy());
    // command register select
    lcd_rs_clear(); //rs.clear();
    // write a command byte
    lcd_write_byte(cmd);
    _delay_us(100);
    //osalThreadDelayMilliseconds(2); //_delay_ms(2);
}
References _delay_us(), lcd_rs_clear(), and lcd_write_byte().
Referenced by lcd_clear(), lcd_cursor_blink(), lcd_cursor_home(), lcd_cursor_off(), lcd_cursor_on(), lcd_cursor_shift_left(), lcd_cursor_shift_right(), lcd_display_shift_left(), lcd_display_shift_right(), lcd_entery_mode_decrement(), lcd_entery_mode_increment(), lcd_goto_xy(), lcd_init_cgram(), lcd_refresh(), and lcd_set_display_cursor().
lcd_write_cstr()
size_t lcd_write_cstr (const char * str)
Definition at line 601 of file lcd.c.
 {
   if (str == NULL) return 0;
    return lcd_write_array((const uint8_t *)str, strlen(str));
 }
References lcd_write_array().
Referenced by lcd_print(), and lcd_print_as_number().
lcd_write_data()
void lcd_write_data (uint8_t data) static
Definition at line 257 of file lcd.c.
{
 //while(is_busy());
 // Data Select register
  lcd_rs_set(); //rs.set();
 // write a data byte
  lcd_write_byte(data);
 _delay_us(100);
  lcd_coord.x++;
  lcd_coord.x=lcd_coord.x%lcd_col_cnt;
}
References _delay_us(), lcd_col_cnt, lcd_coord, lcd_rs_set(), lcd_write_byte(), and coordinate_t::x.
Referenced by lcd_init_cgram(), lcd_print_cgram(), lcd_write(), lcd_write_8bit(), lcd_write_bcd_16bit(), lcd_write_bcd_8bit(), and lcd_write_bin().
lcd_write_hex()
void lcd_write_hex (uint32_t val)
Definition at line 544 of file lcd.c.
{
  lcd_write_num(val,16);
}
References lcd_write_num().
lcd_write_int()
void lcd_write_int (uint32_t val)
Definition at line 554 of file lcd.c.
{
    lcd_write_num(val,10);
}
References lcd_write_num().
lcd_write_num()
void lcd_write_num (uint32_t val, uint8_t base)
Definition at line 537 of file lcd.c.
{
    char buf[16]="";
    itoa(val,buf,base);
    lcd_print(buf);
}
References lcd_print().
Referenced by lcd_write_hex(), lcd_write_int(), and lcd_write_octal().
lcd_write_octal()
void lcd_write_octal (uint32_t val)
Definition at line 549 of file lcd.c.
{
    lcd_write_num(val,8);
}
References lcd_write_num().
lcd_write_str()
size_t lcd_write_str (const char * buffer, size_t size)
Definition at line 596 of file lcd.c.
 {
     return lcd_write_array((const uint8_t *)buffer, size);
 }
References lcd_write_array().
Variable Documentation
bcd_tbl
const unsigned char bcd_tbl[] ="0123456789ABCDEF"
lcd.c
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Definition at line 22 of file lcd.c.
Referenced by lcd_write_8bit(), lcd_write_bcd_16bit(), and lcd_write_bcd_8bit().
lcd_buf
volatile uint8_t lcd_buf[2][16] ={0}
Definition at line 33 of file lcd.c.
lcd_col_cnt
uint8_t lcd_col_cnt
Definition at line 28 of file lcd.c.
Referenced by lcd_blank_line(), lcd_goto_xy(), lcd_init(), and lcd_write_data().
lcd_col_cnt_max
const uint8_t lcd_col_cnt_max =16
Definition at line 25 of file lcd.c.
lcd_coord
coordinate_t lcd_coord
Definition at line 29 of file lcd.c.
Referenced by lcd_blank_line(), lcd_goto_xy(), lcd_init(), lcd_write(), and lcd_write_data().
lcd_db
gpio_t lcd_db[8]
Initial value:
={
{GPIOA,0},
{GPIOA,1},
{GPIOA,2},
{GPIOA,3},
{GPIOA,4},
{GPIOA,5},
{GPIOA,6},
{GPIOA,7},
 }
Definition at line 40 of file lcd.c.
Referenced by lcd_port_pinmode_in(), lcd_port_pinmode_out(), lcd_port_read_byte(), and lcd_port_write_byte().
lcd_en
gpio_t lcd_en ={GPIOB,8}
Definition at line 51 of file lcd.c.
Referenced by disable_buffer(), lcd_en_clear(), lcd_en_pinmode_in(), lcd_en_pinmode_out(), and lcd_en_set().
lcd_flag
GLCD_FLAG_t lcd_flag
Definition at line 31 of file lcd.c.
Referenced by lcd_is_busy(), and lcd_read_busy().
lcd_line_cnt
uint8_t lcd_line_cnt
Definition at line 27 of file lcd.c.
Referenced by lcd_goto_xy(), and lcd_init().
lcd_line_cnt_max
const uint8_t lcd_line_cnt_max =4
Definition at line 24 of file lcd.c.
lcd_options
lcd_options_t lcd_options
Definition at line 30 of file lcd.c.
lcd_rs
gpio_t lcd_rs ={GPIOB,9}
Definition at line 50 of file lcd.c.
Referenced by lcd_rs_clear(), lcd_rs_pinmode_in(), lcd_rs_pinmode_out(), and lcd_rs_set().