STM32F103_IMU6050App: basic/queue.c File Reference
queue.c File Reference
#include "init.h"
Functions
uint8_t queue_is_empty_printable (queue_t *q)
queue.c
uint16_t queue_get_length_printable (queue_t *q)
returns the length of printable data to read
uint8_t queue_getch_printable (queue_t *q, uint8_t *val)
reads a byte value of the queue
void queue_init (queue_t *q, uint8_t *buf, uint16_t len)
initialize the queue buffer
void queue_reset (queue_t *q)
resets the queue and its intrnal pointers
uint8_t queue_is_full (queue_t *q)
checks if the queue is full
uint8_t queue_is_empty (queue_t *q)
checks if the queue is empty
uint16_t queue_get_length (queue_t *q)
returns the length of data to read
uint16_t queue_get_capacity (queue_t *q)
returns the capacity of the queue
uint8_t queue_write (queue_t *q, uint8_t val)
add a byte value to the queue
uint8_t queue_read (queue_t *q, uint8_t *val)
reads a byte value of the queue
uint8_t * queue_Array (queue_t *q)
returns an array for the internal queue buffer
char * queue_toCharArray (queue_t *q)
returns a character pointer as if it is a linear buffer
Function Documentation
queue_Array()
uint8_t * queue_Array (queue_t * q)
returns an array for the internal queue buffer
returns a pointer to the whole buffer as if it a linear buffer
Parameters
q
Returns
uint8_t*
Definition at line 276 of file queue.c.
{
  return q->buf;
}
References queue_t::buf.
queue_get_capacity()
uint16_t queue_get_capacity (queue_t * q)
returns the capacity of the queue
returns the total capacity of the buffer
Parameters
q a pointer to the queue
Returns
uint16_t
Definition at line 215 of file queue.c.
{
    return q->capacity;
}
References queue_t::capacity.
queue_get_length()
uint16_t queue_get_length (queue_t * q)
returns the length of data to read
returns the relative length of data in the buffer
returns the actual readable data after considering the overlap condition, this method to read a block of data instead of reading data block sequentially(i.e. bytes by byte per read operation)
Parameters
q a pointer to the queue
Returns
uint16_t
Definition at line 202 of file queue.c.
{
   uint16_t len=0;
    len=(q->pWR >= q->pRD )? (q->pWR - q->pRD): q->capacity-q->pRD+q->pWR;
   return len;
}
References queue_t::capacity, queue_t::pRD, and queue_t::pWR.
queue_get_length_printable()
uint16_t queue_get_length_printable (queue_t * q)
returns the length of printable data to read
printable methods deals with printable portion of the queue helps to indeicate a task to print on uart or screen without affecting data processing of the queue
returns the actual printable data after considering the overlap condition, this method is used to read a block of data instead of reading data block sequentially(i.e. bytes by byte per read operation)
notice : this method has no effect on the writing/reading data within the ring buffer it just helps to implement an asynchrouns retriavl method for received data to allow printing it outside the receive interrupt
Parameters
q a pointer to the queue
Returns
uint16_t
Definition at line 81 of file queue.c.
{
   uint16_t len=0;
    len=(q->pWR >= q->pTR )? (q->pWR - q->pTR): q->capacity - q->pTR + q->pWR;
   return len;
}
References queue_t::capacity, queue_t::pTR, and queue_t::pWR.
queue_getch_printable()
uint8_t queue_getch_printable (queue_t * q, uint8_t * val)
reads a byte value of the queue
read a value from the queue the next to print to print
reads byte data from the queue and after reading this byte it proceeds the terminal pointer "index of the printing" does not free any space in the queue buffer notice : this method has no effect on the writing/reading data within the ring buffer it just helps to implement an asynchrouns retriavl method for received data to allow printing it outside the receive interrupt
Parameters
q a pointer to a queue to add data to
val the data to be read
Returns
uint8_t
Return values
0 failed to read data from the queue, it is empty
1 succeeded to read data from the queue
Definition at line 104 of file queue.c.
{
  // no data available just exit
  if(queue_is_empty_printable(q))
        return 0;
  else
  {
    // read data from the current terminal pointer position "terminal"
     *val=q->buf[q->pTR];
    // increase the terminal pointer but also considers overlapping condition
     q->pTR=((q->pTR+1)==q->capacity)?0:q->pTR+1;
  }
  return 1;
}
References queue_t::buf, queue_t::capacity, queue_t::pTR, and queue_is_empty_printable().
queue_init()
void queue_init (queue_t * q, uint8_t * buf, uint16_t len)
initialize the queue buffer
used to initialize the queue buffer
Parameters
q a pointer to the queue
buf a physical static array of bytes perfoms as the queue data container
len the actual size of the array
Definition at line 132 of file queue.c.
{
    q->buf=buf;
    q->capacity=len;
    queue_reset(q);
}
References queue_t::buf, queue_t::capacity, and queue_reset().
queue_is_empty()
uint8_t queue_is_empty (queue_t * q)
checks if the queue is empty
checks if the buffer is empty
checks if the queue is empty, it is used before reading from the queue
Parameters
q a pointer to the queue
Returns
uint8_t
Return values
0 the queue is not empty
1 the queue is empty
Definition at line 184 of file queue.c.
 {
  if(q->pWR==q->pRD)
     return 1;
    return 0;
 }
References queue_t::pRD, and queue_t::pWR.
Referenced by queue_read().
queue_is_empty_printable()
uint8_t queue_is_empty_printable (queue_t * q)
queue.c
checks if the buffer is empty from data to print
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
checks if the queue is empty from printable data
checks if the queue is empty from printable data, it is used before reading from the queue a printable data notice : this method has no effect on the writing/reading data within the ring buffer it just helps to implement an asynchrouns retriavl method for received data to allow printing it outside the receive interrupt
Parameters
q a pointer to the queue
Returns
uint8_t
Return values
0 the queue is not empty, contains printable data
1 the queue is empty
Definition at line 59 of file queue.c.
 {
  if(q->pWR==q->pTR)
     return 1;
    return 0;
 }
References queue_t::pTR, and queue_t::pWR.
Referenced by queue_getch_printable().
queue_is_full()
uint8_t queue_is_full (queue_t * q)
checks if the queue is full
checks if the buffer is full and no space to add data
checks if the queue is full
by means no more space is available for new data this method is very important in case
Parameters
q a pointer to the queue
Returns
uint8_t
Return values
0 the queue is not full
1 the queue is full
Definition at line 167 of file queue.c.
{
  if( ((q->pWR+1)%q->capacity)==q->pRD)
     return 1;
    return 0;
}
References queue_t::capacity, queue_t::pRD, and queue_t::pWR.
Referenced by queue_write().
queue_read()
uint8_t queue_read (queue_t * q, uint8_t * val)
reads a byte value of the queue
read a byte value of the queue
reads byte data from the queue and after reading this byte it proceeds the read pointer "the head" this empty a one space in the queue buffer
Parameters
q a pointer to a queue to add data to
data the data to be read
Returns
uint8_t
Return values
0 failed to read data from the queue, it is empty
1 succeeded to read data from the queue
Definition at line 258 of file queue.c.
{
  // no data available just exit
  if(queue_is_empty(q))
    return 0;
   // read data from the current read pointer position "head"
    *val=q->buf[q->pRD];
  // increase the head but consider overlap condition
     q->pRD=((q->pRD+1)==q->capacity)?0:q->pRD+1;
  return 1;
}
References queue_t::buf, queue_t::capacity, queue_t::pRD, and queue_is_empty().
queue_reset()
void queue_reset (queue_t * q)
resets the queue and its intrnal pointers
used to initialize the queue buffer
set zero value to all internal array elements and resets the read/write/ terminal pointers
Parameters
q a pointer to the queue
Definition at line 146 of file queue.c.
{
  q->pWR=0; // resets the write pointer "tail"
  q->pRD=0; // resets the read  pointer "head"
  q->pTR=0; // resets the print pointer "terminal"
  // clear the value of memory
  memset(q->buf,0,q->capacity);
}
References queue_t::buf, queue_t::capacity, queue_t::pRD, queue_t::pTR, and queue_t::pWR.
Referenced by queue_init().
queue_toCharArray()
char * queue_toCharArray (queue_t * q)
returns a character pointer as if it is a linear buffer
Parameters
q
Returns
char*
Definition at line 287 of file queue.c.
{
  return (char*)q->buf;
}
References queue_t::buf.
queue_write()
uint8_t queue_write (queue_t * q, uint8_t val)
add a byte value to the queue
read & write methods affects both read/write pointers by means read a value free its space and writing a value allocate a data space
it tries to add a byte value to the queue first it checks if the queue is full then it returns 0 otherwise it is succeeded
Parameters
q a pointer to the queue to add data to
val the data to be added
Returns
uint16_t
Return values
0 failed to add/ append data to the queue
1 succeeded to add/ append data to the queue
Definition at line 232 of file queue.c.
{
    if(queue_is_full(q))
        return 0;
    else
    {
        // add data to the current write pointer position "tail "
        q->buf[q->pWR]=val;
        // increase the tail but consider overlap condition
        q->pWR=((q->pWR+1)==q->capacity)?0:q->pWR+1;
    }
    return 1;
}
References queue_t::buf, queue_t::capacity, queue_t::pWR, and queue_is_full().