STM32F103_IMU6050App: basic/structs.h File Reference
structs.h File Reference
Classes
union BYTE_BITS
Little-endian format for one byte (8bits)
union WORD_BYTES
Little-endian format for one word (16bits)
union DWORD_BYTES
Little-endian format for one double word (32-bits)
union QWORD_BYTES
Little-endian format for one quadrable word (64-bits)
union Big_BYTE_BITS
Big-Endian format for one byte (8-bits)
union Big_WORD_BYTES
Big-Endian format for one word (16-bits)
union Big_DWORD_BYTES
Big-Endian format for double word (32-bits)
union Big_QWORD_BYTES
Big-Endian format for quadrable word (64-bits)
union bcd_t
bcd format for one byte
union real_t
signed real format
union ureal_t
unsigned real format (small size 8bit)
union usreal_t
unsigned real format (small size 8bit)
Macros
#define BYTE 0
structs.c
#define WORD 1
#define DWORD 2
#define REAL 3
#define UREAL 4
#define SECOND 5
#define MINUTE 6
#define HOUR 7
#define PERIOD 8
#define TIME 9
#define DATE 10
#define PASSWORD 11
#define ID 12
#define INDP 13
Functions
uint16_t clc_sum_16bit (uint16_t *ptmp, uint8_t len)
< calculates the sum of array of 16bit
uint16_t clc_avg_16bit (uint16_t *ptmp, uint8_t len)
calculates the average method on 32bit result for array of 32bit
uint32_t clc_avg_32bit (uint32_t *ptmp, uint8_t len)
calculates the average of an array of double words
real_t avg_real (real_t a, real_t b)
< calclautes the avareage of two real methods
uint8_t cmp_real (real_t a, real_t b)
adds two real numbers
real_t add_real (real_t a, real_t b)
substracts two real numbers
real_t sub_real (real_t, real_t)
increments a real number
void inc_real (real_t *ptr)
decrements a real number
void dec_real (real_t *ptr)
converts float number to real
real_t float_to_real (float val, uint8_t digits)
converts real number to float
float real_to_float (real_t val, uint8_t digits)
converts an real_t number to a float number
uint8_t reverse_byte (uint8_t val)
< reverses byte data from big to little endigan or vice versa
uint16_t reverse_word (uint16_t val)
reverses double word data from big to little endigan or vice versa
uint32_t reverse_dword (uint32_t val)
converts from bcd to binary
uint16_t bcd_to_bin (uint8_t bcd)
converts from binary to bcd
uint8_t bin_to_bcd (uint16_t bin_val)
converts a binary number to a bcd number
Macro Definition Documentation
BYTE
#define BYTE 0
structs.c
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Definition at line 14 of file structs.h.
DATE
#define DATE 10
Definition at line 24 of file structs.h.
DWORD
#define DWORD 2
Definition at line 16 of file structs.h.
HOUR
#define HOUR 7
Definition at line 21 of file structs.h.
ID
#define ID 12
Definition at line 26 of file structs.h.
INDP
#define INDP 13
Definition at line 27 of file structs.h.
MINUTE
#define MINUTE 6
Definition at line 20 of file structs.h.
PASSWORD
#define PASSWORD 11
Definition at line 25 of file structs.h.
PERIOD
#define PERIOD 8
Definition at line 22 of file structs.h.
REAL
#define REAL 3
Definition at line 17 of file structs.h.
SECOND
#define SECOND 5
Definition at line 19 of file structs.h.
TIME
#define TIME 9
Definition at line 23 of file structs.h.
UREAL
#define UREAL 4
Definition at line 18 of file structs.h.
WORD
#define WORD 1
Definition at line 15 of file structs.h.
Function Documentation
add_real()
real_t add_real (real_t a, real_t b)
substracts two real numbers
substracts two real numbers
this method allow to add two real_t numbers instead of using float type more convenient solution for low-performance old avr microcontrollers
Parameters
a first real number
b second real number
Returns
real_t
Definition at line 150 of file structs.c.
{
    real_t c;
    c.val=0;
    int16_t d1=0,d2=0,d3=0;
    d1=a.integer*10+a.decimal;
    d2=b.integer*10+b.decimal;
    d1=(a.sig==1)?-d1:d1;
    d2=(b.sig==1)?-d2:d2;
    d3=d1+d2;
    c.sig=0;
    if(d3<0)
    {
     c.sig=1;
     d3*=-1;
    }
    c.integer=d3/10;
    c.decimal=d3%10;
    return c;
}
References real_t::decimal, real_t::integer, real_t::sig, and real_t::val.
Referenced by inc_real(), and sub_real().
avg_real()
real_t avg_real (real_t a, real_t b)
< calclautes the avareage of two real methods
compares between two real numbers
< calclautes the avareage of two real methods
this method allow to get the average of two real_t numbers instead of using float type more convenient solution for low-performance old avr microcontrollers
Parameters
a first real number
b second real number
Returns
real_t
Definition at line 94 of file structs.c.
{
    real_t c;
    int16_t d1=0,d2=0,d3=0;
    c.val=0;
    d1=a.integer*10+a.decimal;
    d2=b.integer*10+b.decimal;
    d1=(a.sig==1)?-d1:d1;
    d2=(b.sig==1)?-d2:d2;
    d3=d1+d2;
    c.sig=0;
    if(d3<0)
    {
     c.sig=1;
     d3*=-1;
    }
    c.integer=d3/20;
    c.decimal=(d3-c.integer*20)/2;
   return c;
}
References real_t::decimal, real_t::integer, real_t::sig, and real_t::val.
bcd_to_bin()
uint16_t bcd_to_bin (uint8_t bcd)
converts from binary to bcd
converts from binary to bcd
converts a bcd number to a binary number very powerful method for displaying data on BCD
Parameters
bcd the byte data to be reversed
Returns
uint16_t
Definition at line 330 of file structs.c.
{
    bcd_t bcd_val;
    uint16_t bin_val=0;
    bcd_val.byte=bcd;
    bin_val=bcd_val.high_nibble*10;
    bin_val+=bcd_val.low_nibble;
    return bin_val;
}
References bcd_t::byte, bcd_t::high_nibble, and bcd_t::low_nibble.
bin_to_bcd()
uint8_t bin_to_bcd (uint16_t bin_val)
converts a binary number to a bcd number
converts a binary number to a bcd number very powerful method for displaying data on BCD
Parameters
bcd the byte data to be reversed
Returns
uint16_t
Definition at line 348 of file structs.c.
{
    bcd_t bcd_val;
    bcd_val.high_nibble=bin_val/10;
    bcd_val.low_nibble=bin_val%10;
    return bcd_val.byte;
}
References bcd_t::byte, bcd_t::high_nibble, and bcd_t::low_nibble.
clc_avg_16bit()
uint16_t clc_avg_16bit (uint16_t * ptmp, uint8_t len)
calculates the average method on 32bit result for array of 32bit
calculates the average method on 32bit result for array of 32bit
this method returns the average of an array of words which is very useful in get the average result for a set of aquired data from adc
Parameters
ptmp pointer to the array of words
len length of the array
Returns
uint16_t
Definition at line 54 of file structs.c.
{
    uint32_t sum=0;
    uint8_t i=0;
    for(i=0;i<len;i++)
    sum+=ptmp[i];
    return sum/len;
}
clc_avg_32bit()
uint32_t clc_avg_32bit (uint32_t * ptmp, uint8_t len)
calculates the average of an array of double words
this method returns the average of an array of words
Parameters
ptmp pointer to the array of words
len length of the array
Returns
uint32_t
Definition at line 70 of file structs.c.
{
    uint32_t sum=0;
    uint8_t i=0;
    for(i=0;i<len;i++)
    sum+=ptmp[i];
    return sum/len;
}
clc_sum_16bit()
uint16_t clc_sum_16bit (uint16_t * ptmp, uint8_t len)
< calculates the sum of array of 16bit
calculates the average method on 16bit result for array of 16bit
< calculates the sum of array of 16bit
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
calculates the sum of array of 16bit
this method the sum of an array of words which it is used in handling aquired data from adc
Parameters
ptmp pointer to the array of words
len length of the array
Returns
uint16_t
Definition at line 36 of file structs.c.
{
    uint16_t sum=0;
    uint8_t i=0;
    for(i=0;i<len;i++)
    sum+=ptmp[i];
    return sum;
}
cmp_real()
uint8_t cmp_real (real_t a, real_t b)
adds two real numbers
adds two real numbers
this method allow to compare two real_t numbers instead of using float type more convenient solution for low-performance old avr microcontrollers
Parameters
a first real number
b second real number
Return values
0 a == b
1 a > b
2 a < b
Returns
real_t
Definition at line 126 of file structs.c.
{
int16_t d1=0,d2=0;
d1=a.integer*10+a.decimal;
d2=b.integer*10+b.decimal;
d1=(a.sig==1)?-d1:d1;
d2=(b.sig==1)?-d2:d2;
 if(d1>d2)
  return 1;
 if(d1<d2)
  return 2;
 return 0;
}
References real_t::decimal, real_t::integer, and real_t::sig.
dec_real()
void dec_real (real_t * ptr)
converts float number to real
converts float number to real
this method allows to decrement an real_t number instead of using float type more convenient solution for low-performance old avr microcontrollers
Parameters
ptr a pointer to real number (pass by reference)
Returns
real_t
Definition at line 210 of file structs.c.
{
real_t a;
a.val=0;
a.decimal=1;
*ptr=sub_real((real_t)*ptr,a);
}
References real_t::decimal, sub_real(), and real_t::val.
float_to_real()
real_t float_to_real (float number, uint8_t digits)
converts real number to float
converts real number to float
this methods help to converts a float number to real_t number which is very uesfull for display on LCD Display or to send/receive on a bus network
Parameters
number a float number
digits number of decimal digits (resolution)
Returns
real_t
Definition at line 365 of file structs.c.
{
    real_t r;
    r.val=0;
    if(number<0)
     {
         r.sig=1;
         number=-number;
     }
    // Round correctly so that print(1.999, 2) prints as "2.00"
    double rounding = 0.5;
    for (uint8_t i=0; i<digits; ++i)
    rounding /= 10.0;
    number += rounding;//number += 0.05f;
    // Extract the integer part of the number and print it
    unsigned long int_part = (unsigned long)number;
    float reminder = number - (double)int_part;
    // Extract digits from the remainder one at a time
    while (digits-- > 0)
       reminder *=10.0f;
    r.integer=int_part;
    r.decimal=(uint8_t) reminder;
    return r;
}
References real_t::decimal, real_t::integer, real_t::sig, and real_t::val.
Referenced by uart_print_float().
inc_real()
void inc_real (real_t * ptr)
decrements a real number
decrements a real number
this method allows to increment an real_t number instead of using float type more convenient solution for low-performance old avr microcontrollers
Parameters
ptr a pointer to real number (pass by reference)
Returns
real_t
Definition at line 193 of file structs.c.
{
    real_t a;
    a.val=0;
    a.decimal=1;
    *ptr=add_real((real_t)*ptr,a);
}
References add_real(), real_t::decimal, and real_t::val.
real_to_float()
float real_to_float (real_t r, uint8_t digits)
converts an real_t number to a float number
this methods help to converts a received reat_l numbers to float number which is very uesfull for display on LCD Display or to send/receive on a bus network
Parameters
number a float number
digits number of decimal digits (resolution)
Returns
real_t
Definition at line 404 of file structs.c.
{
    float number=0,reminder=0;
    number=r.integer;
    reminder = (float)r.decimal;
    for (uint8_t i=0; i<digits; ++i)
        reminder /= 10.0;
    number+=reminder;
    if(r.sig==1)
    number=-number;
    return number;
}
References real_t::decimal, real_t::integer, and real_t::sig.
reverse_byte()
uint8_t reverse_byte (uint8_t val)
< reverses byte data from big to little endigan or vice versa
reverses word data from big to little endigan or vice versa
< reverses byte data from big to little endigan or vice versa
reverses a data of byte size length from big endigan to little endigan or vice versa
Parameters
val the byte data to be reversed
Returns
uint8_t
Definition at line 229 of file structs.c.
{
    BYTE_BITS byt;
    Big_BYTE_BITS rv_byt;
    byt.byte=val;
    rv_byt.bit0=byt.bit0;
    rv_byt.bit1=byt.bit1;
    rv_byt.bit2=byt.bit2;
    rv_byt.bit3=byt.bit3;
    rv_byt.bit4=byt.bit4;
    rv_byt.bit5=byt.bit5;
    rv_byt.bit6=byt.bit6;
    rv_byt.bit7=byt.bit7;
    return rv_byt.byte;
}
References BYTE_BITS::bit0, Big_BYTE_BITS::bit0, BYTE_BITS::bit1, Big_BYTE_BITS::bit1, BYTE_BITS::bit2, Big_BYTE_BITS::bit2, BYTE_BITS::bit3, Big_BYTE_BITS::bit3, BYTE_BITS::bit4, Big_BYTE_BITS::bit4, BYTE_BITS::bit5, Big_BYTE_BITS::bit5, BYTE_BITS::bit6, Big_BYTE_BITS::bit6, BYTE_BITS::bit7, Big_BYTE_BITS::bit7, BYTE_BITS::byte, and Big_BYTE_BITS::byte.
reverse_dword()
uint32_t reverse_dword (uint32_t val)
converts from bcd to binary
converts from bcd to binary
reverses a data of double word-size length from big endigan to little endigan or vice versa
Parameters
val the byte data to be reversed
Returns
uint8_t
Definition at line 282 of file structs.c.
{
    DWORD_BYTES byt;
    Big_DWORD_BYTES rv_byt;
    byt.dword=val;
    rv_byt.bits.bit0=byt.bits.bit0;
    rv_byt.bits.bit1=byt.bits.bit1;
    rv_byt.bits.bit2=byt.bits.bit2;
    rv_byt.bits.bit3=byt.bits.bit3;
    rv_byt.bits.bit4=byt.bits.bit4;
    rv_byt.bits.bit5=byt.bits.bit5;
    rv_byt.bits.bit6=byt.bits.bit6;
    rv_byt.bits.bit7=byt.bits.bit7;
    rv_byt.bits.bit8=byt.bits.bit8;
    rv_byt.bits.bit9=byt.bits.bit9;
    rv_byt.bits.bit10=byt.bits.bit10;
    rv_byt.bits.bit11=byt.bits.bit11;
    rv_byt.bits.bit12=byt.bits.bit12;
    rv_byt.bits.bit13=byt.bits.bit13;
    rv_byt.bits.bit14=byt.bits.bit14;
    rv_byt.bits.bit15=byt.bits.bit15;
    rv_byt.bits.bit16=byt.bits.bit16;
    rv_byt.bits.bit17=byt.bits.bit17;
    rv_byt.bits.bit18=byt.bits.bit18;
    rv_byt.bits.bit19=byt.bits.bit19;
    rv_byt.bits.bit20=byt.bits.bit20;
    rv_byt.bits.bit21=byt.bits.bit21;
    rv_byt.bits.bit22=byt.bits.bit22;
    rv_byt.bits.bit23=byt.bits.bit23;
    rv_byt.bits.bit24=byt.bits.bit24;
    rv_byt.bits.bit25=byt.bits.bit25;
    rv_byt.bits.bit26=byt.bits.bit26;
    rv_byt.bits.bit27=byt.bits.bit27;
    rv_byt.bits.bit28=byt.bits.bit28;
    rv_byt.bits.bit29=byt.bits.bit29;
    rv_byt.bits.bit30=byt.bits.bit30;
    rv_byt.bits.bit31=byt.bits.bit31;
    return rv_byt.dword;
}
References DWORD_BYTES::bit0, Big_DWORD_BYTES::bit0, DWORD_BYTES::bit1, Big_DWORD_BYTES::bit1, DWORD_BYTES::bit10, Big_DWORD_BYTES::bit10, DWORD_BYTES::bit11, Big_DWORD_BYTES::bit11, DWORD_BYTES::bit12, Big_DWORD_BYTES::bit12, DWORD_BYTES::bit13, Big_DWORD_BYTES::bit13, DWORD_BYTES::bit14, Big_DWORD_BYTES::bit14, DWORD_BYTES::bit15, Big_DWORD_BYTES::bit15, DWORD_BYTES::bit16, Big_DWORD_BYTES::bit16, DWORD_BYTES::bit17, Big_DWORD_BYTES::bit17, DWORD_BYTES::bit18, Big_DWORD_BYTES::bit18, DWORD_BYTES::bit19, Big_DWORD_BYTES::bit19, DWORD_BYTES::bit2, Big_DWORD_BYTES::bit2, DWORD_BYTES::bit20, Big_DWORD_BYTES::bit20, DWORD_BYTES::bit21, Big_DWORD_BYTES::bit21, DWORD_BYTES::bit22, Big_DWORD_BYTES::bit22, DWORD_BYTES::bit23, Big_DWORD_BYTES::bit23, DWORD_BYTES::bit24, Big_DWORD_BYTES::bit24, DWORD_BYTES::bit25, Big_DWORD_BYTES::bit25, DWORD_BYTES::bit26, Big_DWORD_BYTES::bit26, DWORD_BYTES::bit27, Big_DWORD_BYTES::bit27, DWORD_BYTES::bit28, Big_DWORD_BYTES::bit28, DWORD_BYTES::bit29, Big_DWORD_BYTES::bit29, DWORD_BYTES::bit3, Big_DWORD_BYTES::bit3, DWORD_BYTES::bit30, Big_DWORD_BYTES::bit30, DWORD_BYTES::bit31, Big_DWORD_BYTES::bit31, DWORD_BYTES::bit4, Big_DWORD_BYTES::bit4, DWORD_BYTES::bit5, Big_DWORD_BYTES::bit5, DWORD_BYTES::bit6, Big_DWORD_BYTES::bit6, DWORD_BYTES::bit7, Big_DWORD_BYTES::bit7, DWORD_BYTES::bit8, Big_DWORD_BYTES::bit8, DWORD_BYTES::bit9, Big_DWORD_BYTES::bit9, DWORD_BYTES::bits, Big_DWORD_BYTES::bits, DWORD_BYTES::dword, and Big_DWORD_BYTES::dword.
Referenced by crc32a_calc().
reverse_word()
uint16_t reverse_word (uint16_t val)
reverses double word data from big to little endigan or vice versa
reverses double word data from big to little endigan or vice versa
reverses a data of word size length from big endigan to little endigan or vice versa
Parameters
val the byte data to be reversed
Returns
uint8_t
Definition at line 251 of file structs.c.
{
    WORD_BYTES byt;
    Big_WORD_BYTES rv_byt;
    byt.word=val;
    rv_byt.bits.bit0=byt.bits.bit0;
    rv_byt.bits.bit1=byt.bits.bit1;
    rv_byt.bits.bit2=byt.bits.bit2;
    rv_byt.bits.bit3=byt.bits.bit3;
    rv_byt.bits.bit4=byt.bits.bit4;
    rv_byt.bits.bit5=byt.bits.bit5;
    rv_byt.bits.bit6=byt.bits.bit6;
    rv_byt.bits.bit7=byt.bits.bit7;
    rv_byt.bits.bit8=byt.bits.bit8;
    rv_byt.bits.bit9=byt.bits.bit9;
    rv_byt.bits.bit10=byt.bits.bit10;
    rv_byt.bits.bit11=byt.bits.bit11;
    rv_byt.bits.bit12=byt.bits.bit12;
    rv_byt.bits.bit13=byt.bits.bit13;
    rv_byt.bits.bit14=byt.bits.bit14;
    rv_byt.bits.bit15=byt.bits.bit15;
    return rv_byt.word;
}
References WORD_BYTES::bit0, Big_WORD_BYTES::bit0, WORD_BYTES::bit1, Big_WORD_BYTES::bit1, WORD_BYTES::bit10, Big_WORD_BYTES::bit10, WORD_BYTES::bit11, Big_WORD_BYTES::bit11, WORD_BYTES::bit12, Big_WORD_BYTES::bit12, WORD_BYTES::bit13, Big_WORD_BYTES::bit13, WORD_BYTES::bit14, Big_WORD_BYTES::bit14, WORD_BYTES::bit15, Big_WORD_BYTES::bit15, WORD_BYTES::bit2, Big_WORD_BYTES::bit2, WORD_BYTES::bit3, Big_WORD_BYTES::bit3, WORD_BYTES::bit4, Big_WORD_BYTES::bit4, WORD_BYTES::bit5, Big_WORD_BYTES::bit5, WORD_BYTES::bit6, Big_WORD_BYTES::bit6, WORD_BYTES::bit7, Big_WORD_BYTES::bit7, WORD_BYTES::bit8, Big_WORD_BYTES::bit8, WORD_BYTES::bit9, Big_WORD_BYTES::bit9, WORD_BYTES::bits, Big_WORD_BYTES::bits, WORD_BYTES::word, and Big_WORD_BYTES::word.
sub_real()
real_t sub_real (real_t a, real_t b)
increments a real number
increments a real number
this method allows to substract two real_t numbers instead of using float type more convenient solution for low-performance old avr microcontrollers
Parameters
a first real number
b second real number
Returns
real_t
Definition at line 179 of file structs.c.
{
    //b.integer=0-b.integer;
    b.sig=1;
    return add_real(a,b);
}
References add_real(), and real_t::sig.
Referenced by dec_real().