STM32F103_IMU6050App: system/system.h File Reference
system.h File Reference
Classes
union pilot_t
system.h
union rly_t
Functions
void system_init (void)
void system_run (void)
void system_ticks (void)
void system_rtc (void)
void system_tasks_init (void)
Variables
uint32_t systemticks
system.c
uint8_t is_tick
minute_t logout_timeout
uint8_t src_address
uint8_t dst_address
uint8_t me_address
Function Documentation
system_init()
void system_init (void)
Definition at line 33 of file system.c.
{
//********************************************************************************************
//
//  NVIC Global Interrupts Priority Group
//
//********************************************************************************************
  NVIC_PriorityGroupConfig(NVIC_PriorityGroup_0);
//********************************************************************************************
//
//  Configure SysTick  and  other clock module
//
//
//********************************************************************************************
    //Configure SysTick Timer interrupt for 100 uS micro second
    if(SysTick_Config(SystemCoreClock/100000)) while(1);
    systemticks=0;
    is_tick=0;
    logout_timeout.sec=5;
    logout_timeout.min=0;
//********************************************************************************************
//
//  Configure RCC clock  for other peripherals module
//  mainly for GPIOx and AFIO
//
//********************************************************************************************
    // Enable peripheral clocks
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA,ENABLE);
      RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOB,ENABLE);
      RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOC,ENABLE);
      RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOD,ENABLE);
     RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO,ENABLE);
     TimingDelay=0;
//********************************************************************************************
//
//  the GPIO Module Initialize
//
//********************************************************************************************
   blink_init();
   pilot_init();
   rly_init();
   pilots.val=0xff;
   relays.val=0;
   pilot_write(pilots.val);
   rly_write(relays.val);
   blink_update=0;
//********************************************************************************************
//
//  Keypad Module Initialize
//
//********************************************************************************************
    keypad_init(0xfc);
//********************************************************************************************
//
//  character lcd module
//
//********************************************************************************************
    lcd_init();
      lcd_refresh();
    lcd_print_xy(0,0,"stm32f10x  ");
    lcd_update=0;
//********************************************************************************************
//
//  Configure Timer module
//
//********************************************************************************************
    //TIM2_init();
    TIM3_init();
//********************************************************************************************
//
//  Configure USART module
//
//********************************************************************************************
    //USART1_init();
    uart_init();
//********************************************************************************************
//
//  Configure I2c module
//
//********************************************************************************************
    /* Initialize I2C */
  i2c_init_std(MPU6050_I2C,MPU6050_I2C_CLOCK,0x20);
//********************************************************************************************
//
//  Configure  module
//
//********************************************************************************************
  system_tasks_init();
   is_tick=1;
}
References blink_init(), blink_update, i2c_init_std(), is_tick, keypad_init(), lcd_init(), lcd_print_xy(), lcd_refresh(), lcd_update, logout_timeout, minute_t::min, MPU6050_I2C, MPU6050_I2C_CLOCK, pilot_init(), pilot_write(), pilots, relays, rly_init(), rly_write(), minute_t::sec, system_tasks_init(), systemticks, TIM3_init(), TimingDelay, uart_init(), pilot_t::val, and rly_t::val.
Referenced by main().
system_rtc()
void system_rtc (void)
Definition at line 197 of file system.c.
{
    pilot_write(pilots.val);
    //lcd_refresh();
    //lcd_print_double_xy_str(0,0,"t1:",t1,2);
    //lcd_print_double_xy_str(0,1,"t2:",t2,2);
    //lcd_print_uint32_xy(10,0,systemticks,10);
    //lcd.print(0,1,SystemCoreClock);
}
References pilot_write(), pilots, and pilot_t::val.
Referenced by rtc_task().
system_run()
void system_run (void)
Definition at line 133 of file system.c.
{
 // Task1 to read  external analog voltage
  //adc_task();
  // Task2 to scan keypad
  keypad_task();
// Task3 to read input buffer
  //inbuf_task();
// Task3 to read MPU
  mpu6050_task();
 // Task4 to read usb buffer
  //uart_task();
  lcd_task();
// Task5 to real time clock to refresh the whole system
   rtc_task();
}
References keypad_task(), lcd_task(), mpu6050_task(), and rtc_task().
Referenced by main().
system_tasks_init()
void system_tasks_init (void)
Definition at line 177 of file system.c.
{
  keypad_state=0;
  keypad_ticks=0;
  keypad_debounce_cnt=0;
  mpu_state=0;
  mpu_ticks=0;
  mpu_init_sucess=0;
  lcd_state=0;
  lcd_ticks=0;
  pilot_state=0;
  pilot_ticks=0;
  rtc_state=0;
  rtc_ticks=0;
}
References keypad_debounce_cnt, keypad_state, keypad_ticks, lcd_state, lcd_ticks, mpu_init_sucess, mpu_state, mpu_ticks, pilot_state, pilot_ticks, rtc_state, and rtc_ticks.
Referenced by system_init().
system_ticks()
void system_ticks (void)
Definition at line 157 of file system.c.
{
// keypad task tick
  if(keypad_state==KEYPAD_WAIT)
     keypad_ticks++;
// mpu task tick
  if(mpu_state==MPU_WAIT)
      mpu_ticks++;
// keypad debounce tick
  if(keypad_state==KEYPAD_DEBOUNCE)
      keypad_debounce_cnt++;
// rtc task tick
  if(rtc_state==RTC_WAIT)
     rtc_ticks++;
}
References KEYPAD_DEBOUNCE, keypad_debounce_cnt, keypad_state, keypad_ticks, KEYPAD_WAIT, mpu_state, mpu_ticks, MPU_WAIT, rtc_state, rtc_ticks, and RTC_WAIT.
Variable Documentation
dst_address
uint8_t dst_address extern
Definition at line 27 of file system.c.
is_tick
uint8_t is_tick extern
Definition at line 22 of file system.c.
Referenced by system_init().
logout_timeout
minute_t logout_timeout extern
Definition at line 23 of file system.c.
Referenced by keypad_process(), and system_init().
me_address
uint8_t me_address extern
Definition at line 25 of file system.c.
src_address
uint8_t src_address extern
Definition at line 26 of file system.c.
systemticks
uint32_t systemticks extern
system.c
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Definition at line 21 of file system.c.
Referenced by rtc_task(), and system_init().