STM32F103_IMU6050App: basic/time.h File Reference
time.h File Reference
Classes
union minute_t
union hour_t
union ext_period_t
union period_t
union _time_t
union date_t
union datetime_t
Macros
#define MIN_LEN 2
#define HOUR_LEN 2
#define EXTENDED_PERIOD_LEN 3
#define PERIOD_LEN 2
#define TIME_LEN 4
#define DATE_LEN 4
#define DATETIME_LEN 8
Typedefs
typedef uint8_t second_t
time.c
Functions
void _decrment (uint8_t *p, uint8_t len)
void minute_dec (minute_t *p)
void hour_dec (period_t *p)
void period_dec (period_t *p)
void ext_period_dec (ext_period_t *p)
void time_dec (_time_t *p)
uint8_t _timeout (uint8_t *p, uint8_t len)
time.c
uint8_t minute_timeout (minute_t *p)
uint8_t period_timeout (period_t *p)
uint8_t ext_period_timeout (ext_period_t *p)
uint8_t time_timeout (_time_t *p)
Macro Definition Documentation
DATE_LEN
#define DATE_LEN 4
Definition at line 80 of file time.h.
DATETIME_LEN
#define DATETIME_LEN 8
Definition at line 93 of file time.h.
EXTENDED_PERIOD_LEN
#define EXTENDED_PERIOD_LEN 3
Definition at line 41 of file time.h.
HOUR_LEN
#define HOUR_LEN 2
Definition at line 29 of file time.h.
MIN_LEN
#define MIN_LEN 2
Definition at line 17 of file time.h.
PERIOD_LEN
#define PERIOD_LEN 2
Definition at line 54 of file time.h.
TIME_LEN
#define TIME_LEN 4
Definition at line 66 of file time.h.
Typedef Documentation
second_t
typedef uint8_t second_t
time.c
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Definition at line 15 of file time.h.
Function Documentation
_decrment()
void _decrment (uint8_t * p, uint8_t len)
Definition at line 38 of file time.cpp.
{
static uint8_t index=0,i=0;
if(p[index]!=0) p[index]--;
else{
    index++;
    if(index==len)return;
    if(p[index]!=0)
    {
        p[index]--;
        for(i=0;i<index;i++)
            p[i]=59;
        index--;
    }
    else{
    _decrment(p,len);
    index=0;
    }
 }
}
References _decrment().
Referenced by _decrment(), ext_period_dec(), minute_dec(), period_dec(), and time_dec().
_timeout()
uint8_t _timeout (uint8_t * p, uint8_t len)
time.c
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Definition at line 25 of file time.cpp.
 {
  uint8_t flg=1;
 for(uint8_t i=0; i<len;i++)
    if(p[i]!=0)
    {
        flg=0;
        break;
    }
   return flg;
 }
ext_period_dec()
void ext_period_dec (ext_period_t * p)
Definition at line 117 of file time.cpp.
{
    _decrment(p->Array,sizeof(ext_period_t));
}
References _decrment(), and ext_period_t::Array.
ext_period_timeout()
uint8_t ext_period_timeout (ext_period_t * p)
Definition at line 88 of file time.cpp.
{
  if(p->hour==0 && p->minute==0 && p->second==0)
    return 1;
  return 0;
}
References ext_period_t::hour, ext_period_t::minute, and ext_period_t::second.
hour_dec()
void hour_dec (period_t * p)
minute_dec()
void minute_dec (minute_t * p)
Definition at line 102 of file time.cpp.
{
 _decrment(p->Array,sizeof(minute_t));
}
References _decrment(), and minute_t::Array.
minute_timeout()
uint8_t minute_timeout (minute_t * p)
Definition at line 67 of file time.cpp.
{
    if(p->val==0)
     return 1;
    return 0;
}
References minute_t::val.
period_dec()
void period_dec (period_t * p)
Definition at line 112 of file time.cpp.
{
    _decrment(p->Array,sizeof(period_t));
}
References _decrment(), and period_t::Array.
period_timeout()
uint8_t period_timeout (period_t * p)
Definition at line 81 of file time.cpp.
{
    if(p->val==0)
    return 1;
    return 0;
}
References period_t::val.
time_dec()
void time_dec (_time_t * p)
Definition at line 122 of file time.cpp.
{
    _decrment(p->Array,sizeof(_time_t));
}
References _decrment(), and _time_t::Array.
time_timeout()
uint8_t time_timeout (_time_t * p)
Definition at line 95 of file time.cpp.
{
   if(p->val==0)
    return 1;
   return 0;
}
References _time_t::val.