STM32F103_IMU6050App: uart/uart.h File Reference
uart.h File Reference
Macros
#define UART_DELIMITER_SIZE 4
uart.h
#define UART_HEADER_SIZE 4
#define UART_BUFFER_SIZE 64
#define UART_BUFFER_MASK (UART_BUFFER_SIZE - 1)
#define RASPNET_MAX_RX_QUEUE_LEN 120
#define RASPNET_MAX_TX_QUEUE_LEN 120
#define RASPNET_MAX_FRAME_LEN 40
#define RASPNET_MAX_PAYLOAD_LEN (RASPNET_MAX_FRAME_LEN-RASPNET_LINK_HEADER_LEN)
#define RASPNET_PACKET_P 0x06
#define RASPNET_PAYLOAD_P 0x08
#define UART_WAIT_TIMEOUT 20000
Enumerations
enum CMD_TYPES {
_SPD =0 , _INC =1 , _DEC =2 , _INFO =3 ,
_CRC =4 , _TX =5 , _RX =6
}
commands types theat can be send on the uart
enum UART_STATE { UART_WAIT , UART_READ }
Functions
void USART1_init (void)
uart-common.c
void USART2_init (void)
void USART3_init (void)
uint8_t uart_put_char (USART_TypeDef *usartx, uint8_t data)
uint8_t uart_get_char (USART_TypeDef *usartx)
void uart_init (void)
initialiaze the usart module
void uart_reset (void)
resets the received buffer
uint8_t uart_receive (USART_TypeDef *usartx)
performs areceive operation of one byte on uart
void uart_receive_start (void)
initializes the uart to operate in the receive mode
uint8_t uart_islistening (void)
checks if the uart in the receive mode and listens
uint8_t uart_data_is_available (void)
checks if the data on the uart is available
void uart_handle_frame (void)
handles the whole message as if it is a correct command structure
void uart_handle_cmd (uint8_t *cmd, size_t cmd_len, uint8_t *data, size_t data_len)
uint8_t uart_send_byte (USART_TypeDef *usartx, uint8_t byte)
sends one byte on the uart
void uart_send_buffer (USART_TypeDef *usartx, uint8_t *buf, uint16_t buf_size)
sends an array of bytes on the uart
void uart_send_message (USART_TypeDef *usartx, uint8_t *buff, uint16_t length)
sends a message on the uart
void uart_println (USART_TypeDef *usartx, char *str)
a generic println message on the uart
void uart_print (USART_TypeDef *usartx, char *str)
a generic print message on the uart
void uart_print_integer (USART_TypeDef *usartx, uint32_t dword, uint8_t base)
void uart_print_float (USART_TypeDef *usartx, float val, uint8_t digits)
void uart_print_Array (USART_TypeDef *usartx, uint8_t *data, uint8_t len)
a generic print message as hexadecimal format on the uart
void uart_println_Array (USART_TypeDef *usartx, uint8_t *data, uint8_t len)
a generic println message as hexadecimal format on the uart
void uart_info_cmd_handle ()
info command: returns the current speed delay time for the blinking led
void uart_blk_cmd_handle ()
blink command: just activates blinking task
void uart_hlt_cmd_handle ()
halt command: just deactivates blinking task
void uart_rst_cmd_handle ()
reset command: reset raspnet tx/rx buffers
void uart_tx_queue_cmd_handle ()
void uart_rx_queue_cmd_handle ()
void uart_spd_cmd_handle (uint8_t *data, size_t data_len)
speed command: changes the speed delay time for the blinking led
void uart_inc_cmd_handle (uint8_t *data, size_t data_len)
increase command: increases the speed delay time for the blinking led
void uart_dec_cmd_handle (uint8_t *data, size_t data_len)
decrease command: decreases the speed delay time for the blinking led
void uart_crc_cmd_handle (uint8_t *data, size_t data_len)
increase command: increases the speed delay time for the blinking led
void uart_crc_cmd_handle_type (uint8_t *data, size_t data_len, uint8_t type)
void uart_tx_cmd_handle (uint8_t *data, size_t data_len)
void uart_rx_cmd_handle (uint8_t *data, size_t data_len)
void uart_id_cmd_handle (uint8_t *data, size_t data_len)
void uart_task (void)
a generic task to handle uart task
Variables
queue_t raspnet_rx_queue
defines the Raspnet Frame structure
queue_t raspnet_tx_queue
a gloabl variale define the raspnet transmit Ring Queue
uint8_t raspnet_tx_buffer [RASPNET_MAX_TX_QUEUE_LEN]
a gloabl variale define the raspnet receive buffer (Ring Queue)
uint8_t raspnet_rx_buffer [RASPNET_MAX_RX_QUEUE_LEN]
a gloabl variale define the raspnet receive buffer (Ring Queue)
volatile uint8_t uart_state
uart.c
volatile uint32_t uart_ticks
volatile uint16_t rx_index
uint8_t rx_buffer [UART_BUFFER_SIZE]
volatile uint8_t rx_buffer_length
volatile uint8_t buffer_overflow
gpio_t uart_tx
gpio_t uart_rx
Macro Definition Documentation
RASPNET_MAX_FRAME_LEN
#define RASPNET_MAX_FRAME_LEN 40
Definition at line 38 of file uart.h.
RASPNET_MAX_PAYLOAD_LEN
#define RASPNET_MAX_PAYLOAD_LEN (RASPNET_MAX_FRAME_LEN-RASPNET_LINK_HEADER_LEN)
Definition at line 39 of file uart.h.
RASPNET_MAX_RX_QUEUE_LEN
#define RASPNET_MAX_RX_QUEUE_LEN 120
Definition at line 35 of file uart.h.
RASPNET_MAX_TX_QUEUE_LEN
#define RASPNET_MAX_TX_QUEUE_LEN 120
Definition at line 36 of file uart.h.
RASPNET_PACKET_P
#define RASPNET_PACKET_P 0x06
Definition at line 41 of file uart.h.
RASPNET_PAYLOAD_P
#define RASPNET_PAYLOAD_P 0x08
Definition at line 42 of file uart.h.
UART_BUFFER_MASK
#define UART_BUFFER_MASK (UART_BUFFER_SIZE - 1)
Definition at line 28 of file uart.h.
UART_BUFFER_SIZE
#define UART_BUFFER_SIZE 64
Definition at line 27 of file uart.h.
UART_DELIMITER_SIZE
#define UART_DELIMITER_SIZE 4
uart.h
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
Definition at line 25 of file uart.h.
UART_HEADER_SIZE
#define UART_HEADER_SIZE 4
Definition at line 26 of file uart.h.
UART_WAIT_TIMEOUT
#define UART_WAIT_TIMEOUT 20000
Definition at line 134 of file uart.h.
Enumeration Type Documentation
CMD_TYPES
enum CMD_TYPES
commands types theat can be send on the uart
list an enumerated numbers for some of supperted commands to check/debug the functionality of the raspnet project @ Atmega
Parameters
_SPD =0 changes the speed of blinking leds
_INC =1 increases the speed delay of the blinking leds
_DEC =2 decreases the speed delay of the blinking leds
_INFO =3 returns information about the value of speed delay
_CRC =4 returns the crc32 for a sequnce of bytes to debug crc32 function operation
_TX =5 sends a message through uart from rasperpi to atmega to be sent as raspnet message
_RX =6 reserved to receive a message for future usage
Enumerator
_SPD
changes the speed of blinking leds
_INC
increases the speed delay of the blinking leds
_DEC
decreases the speed de,lay of the blinking leds
_INFO
returns information about the value of speed delay
_CRC
returns the crc32 for a sequnce of bytes to debug crc32 function operation
_TX
sends a message through uart from rasperpi to atmega to be sent as raspnet message
_RX
reserved to receive a message for future usage
Definition at line 112 of file uart.h.
{
  _SPD=0,
  _INC=1,
  _DEC=2,
  _INFO=3,
  _CRC=4,
  _TX=5,
  _RX=6
};
UART_STATE
enum UART_STATE
Enumerator
UART_WAIT
wait until data is available on the uart receive buffer
UART_READ
read the available data in the received
Definition at line 136 of file uart.h.
                {
 UART_WAIT,
 UART_READ
};
Function Documentation
uart_blk_cmd_handle()
void uart_blk_cmd_handle ()
blink command: just activates blinking task
uart_crc_cmd_handle()
void uart_crc_cmd_handle (uint8_t * data, size_t data_len)
increase command: increases the speed delay time for the blinking led
uart_crc_cmd_handle_type()
void uart_crc_cmd_handle_type (uint8_t * data, size_t data_len, uint8_t type)
uart_data_is_available()
uint8_t uart_data_is_available (void)
checks if the data on the uart is available
checks if the data on the uart is available
it checks if a complete command message has received note that each command message should ends witha space and ; == " ;"
Returns
uint8_t
Definition at line 642 of file uart.c.
{
 char * delim=" ;";
 if(rx_buffer_length!=0)
 {
    const uint8_t * tmp=0;//(uint8_t *) memmem((uint8_t *)rx_buffer,rx_buffer_length,(uint8_t *)delim,sizeof(delim));
   if(tmp!=NULL)
     return 1;
 }
 return 0;
}
References rx_buffer_length.
Referenced by uart_task().
uart_dec_cmd_handle()
void uart_dec_cmd_handle (uint8_t * data, size_t data_len)
decrease command: decreases the speed delay time for the blinking led
uart_get_char()
uint8_t uart_get_char (USART_TypeDef * usartx)
Definition at line 383 of file uart_com.c.
{
  while(USART_GetFlagStatus(usartx,USART_FLAG_RXNE)==RESET);
  return usartx->DR & (uint16_t) 0x00ff;
}
uart_handle_cmd()
void uart_handle_cmd (uint8_t * cmd, size_t cmd_len, uint8_t * data, size_t data_len)
uart_handle_frame()
void uart_handle_frame (void)
handles the whole message as if it is a correct command structure
Referenced by uart_task().
uart_hlt_cmd_handle()
void uart_hlt_cmd_handle ()
halt command: just deactivates blinking task
uart_id_cmd_handle()
void uart_id_cmd_handle (uint8_t * data, size_t data_len)
uart_inc_cmd_handle()
void uart_inc_cmd_handle (uint8_t * data, size_t data_len)
increase command: increases the speed delay time for the blinking led
uart_info_cmd_handle()
void uart_info_cmd_handle ()
info command: returns the current speed delay time for the blinking led
uart_init()
void uart_init (void)
initialiaze the usart module
initialiaze the usart module
initializes the uart module and configure the buad rate and the message format such as start bit, parity , stop bit and the charactersize , it also resets the receive buffer size of the uart
Returns
void
Definition at line 539 of file uart.c.
{
  USART1_init();
// pins initialization
//  uart_CNTA_DIR.tx=1;   // set as output pin
//  uart_CNTA_DIR.rx=0;   // set as an input pin
//  uart_CNTA_PORT.tx=1;  // set to High State
//  uart_CNTA_PORT.rx=1;  // Enable Weak up resistor
//to change uart configuration such buad rate,data frame length ,stop bits,  parity
// based on the static options provided at the top of this file
 //    uart_configure();
 // Reset USART buffer
    uart_reset();
 }
References uart_reset(), and USART1_init().
Referenced by system_init().
uart_islistening()
uint8_t uart_islistening (void)
checks if the uart in the receive mode and listens
checks if the uart in the receive mode and the receive complete interrupt mask bit has been activated
Returns
uint8_t
Definition at line 363 of file uart.c.
{
 //if(bit_is_set(UCSR0B,RXEN0) && bit_is_set(UCSR0B,RXCIE0))
// if (uart_control_reg.rx_enable && uart_control_reg.receive_complete_ie)
//   return 1;
 return 0;
}
uart_print()
void uart_print (USART_TypeDef * usartx, char * str)
a generic print message on the uart
similar to uart_send_buffer, except it handles characters as an ASCII data
Parameters
str a pointer to character string
Definition at line 433 of file uart.c.
{
    uart_send_buffer(usartx ,(uint8_t*)str,strlen(str));
}
References uart_send_buffer().
Referenced by i2c_uart_print(), mpu6050_init(), mpu6050_set_hpf(), mpu6050_set_lpf(), mpu6050_task(), mpu6050_uart_print_Accelometer(), mpu6050_uart_print_Gyroscope(), mpu6050_uart_print_raw_Accelometer(), mpu6050_uart_print_raw_Array(), mpu6050_uart_print_raw_Gyroscope(), mpu6050_uart_print_raw_Temperature(), mpu6050_uart_print_Temperature(), uart_print_Array(), uart_print_float(), uart_print_integer(), uart_println_Array(), and uart_task().
uart_print_Array()
void uart_print_Array (USART_TypeDef * usartx, uint8_t * data, uint8_t len)
a generic print message as hexadecimal format on the uart
a generic print message as hexadecimal format on the uart
similar to uart_send_buffer, except it converrs ASCII data to hexadecimal format
Parameters
data a pointer to start of message buffer
len the length of the buffer message
Definition at line 495 of file uart.c.
{
    char buf[16]="";
    uint8_t val=0;
   for(uint8_t i=0;i<len;i++)
   {
      val=data[i];
       uart_print(usartx ," 0x");
       itoa(val,buf,16);
       uart_print(usartx ,buf);
       if (i%5==0)
        uart_println(usartx," ");
  }
}
References uart_print(), and uart_println().
uart_print_float()
void uart_print_float (USART_TypeDef * usartx, float val, uint8_t digits)
Definition at line 473 of file uart.c.
{
char buf[16]="";
    real_t r;
    r=float_to_real(val,digits);
    if(r.sig==1)
    uart_print(usartx,"-");
    itoa(r.integer,buf,10);
    uart_print(usartx,buf);
        uart_print(usartx,".");
    itoa(r.decimal,buf,10);
    uart_print(usartx,buf);
}
References real_t::decimal, float_to_real(), real_t::integer, real_t::sig, and uart_print().
Referenced by mpu6050_uart_print_Temperature().
uart_print_integer()
void uart_print_integer (USART_TypeDef * usartx, uint32_t dword, uint8_t base)
Parameters
usartx
dword
Definition at line 459 of file uart.c.
{
    char buf[16]="";
    switch(base)
    {
      case 16:  uart_print(usartx,"0x"); break;
      case 2:   uart_print(usartx,"0b"); break;
      default:  uart_print(usartx," ");  break;
    }
    itoa(dword,buf,base);
    uart_print(usartx,buf);
}
References uart_print().
Referenced by i2c_uart_print(), mpu6050_init(), mpu6050_set_hpf(), mpu6050_set_lpf(), mpu6050_task(), mpu6050_uart_print_Accelometer(), mpu6050_uart_print_Gyroscope(), mpu6050_uart_print_raw_Accelometer(), mpu6050_uart_print_raw_Array(), mpu6050_uart_print_raw_Gyroscope(), and mpu6050_uart_print_raw_Temperature().
uart_println()
void uart_println (USART_TypeDef * usartx, char * str)
a generic println message on the uart
similar to uart_send_buffer, except it handles characters as an ASCII data with \newline \r
Parameters
str a pointer to character string
Definition at line 446 of file uart.c.
{
    uart_send_buffer(usartx ,(uint8_t*)str,strlen(str));
    uart_send_byte(usartx,'\r');
    uart_send_byte(usartx,'\n');
}
References uart_send_buffer(), and uart_send_byte().
Referenced by uart_print_Array(), uart_println_Array(), and uart_task().
uart_println_Array()
void uart_println_Array (USART_TypeDef * usartx, uint8_t * data, uint8_t len)
a generic println message as hexadecimal format on the uart
a generic println message as hexadecimal format on the uart
similar to uart_send_buffer, except it converrs ASCII data to hexadecimal format
Parameters
data a pointer to start of message buffer
len the length of the buffer message
Definition at line 518 of file uart.c.
{
    char buf[16]="";
    uint8_t val=0;
   for(uint8_t i=0;i<len;i++)
   {
      val=data[i];
       uart_print(usartx,"0x");
       itoa(val,buf,16);
       uart_println(usartx,buf);
  }
}
References uart_print(), and uart_println().
uart_put_char()
uint8_t uart_put_char (USART_TypeDef * usartx, uint8_t data)
Definition at line 375 of file uart_com.c.
{
  while(USART_GetFlagStatus(usartx,USART_FLAG_TXE)==RESET);
  usartx->DR=(data & (uint16_t) 0x00ff);
  return 0;
}
Referenced by uart_receive().
uart_receive()
uint8_t uart_receive (USART_TypeDef * usartx)
performs areceive operation of one byte on uart
receives one byte on uart at the trigger of the receive complete interrupt and appends this received byte to the receive buffer this method is called in the uart receive complete interrupt service routine
Returns
the received byte on the uart rx module
uint8_t
USART_FLAG_ORE: OverRun Error flag
USART_FLAG_NE: Noise Error flag
USART_FLAG_FE: Framing Error flag
USART_FLAG_PE: Parity Error flag
PE (Parity error) , FE (Framing error), NE (Noise error),
ORE (OverRun error) and IDLE (Idle line detected) flags are cleared by software sequence:
a read operation to USART_SR register (USART_GetFlagStatus())
followed by a read operation to USART_DR register (USART_ReceiveData()).
RXNE flag can be also cleared by a read to the USART_DR register (USART_ReceiveData()).
Definition at line 569 of file uart.c.
{
  //uint8_t data=0;
  //uart_status_t status;
 // read data byte received from the rx buffer as soon as possible
   //data= uart_data_reg.val;
  // get the status of the uart
   //status.val=uart_status_reg.val;
   //uart_status_reg.val=0;
  // check no error in the received byte
   //if(!status.data_over_run &&
//     !status.frame_error   &&
//     !status.parity_error)
    // clear the Interrupt
     //USART_ClearITPendingBit(USART1,USART_IT_RXNE);
      volatile uint8_t data=0;
      volatile uint16_t status=0;
      status=usartx->SR;
      // read the received data from the usart receive buffer
      data=usartx->DR & 0x00ff;    // onlu 8_bit
     // reset the receive interrupt flag by software optional, reading data  reset IT_RXNE by hardware
     //RXNE flag can be also cleared by a read to the USART_DR register (USART_ReceiveData()).
     //USART_GetFlagStatus(USART1,USART_IT_TXE);
     //USART_ClearITPendingBit(USART1,USART_IT_RXNE);
     // push it to the receive queue
    uart_put_char(USART1,data);
    if(data==';')
        relays.val=0;
    if(USART_GetFlagStatus(USART1,USART_FLAG_PE | USART_FLAG_FE |
                           USART_FLAG_NE | USART_FLAG_ORE)==RESET)
    {
       //
      // here try to append the data to the received buffer
        if(!uart_rx_buffer_add(data))
        {
          // it is failed to add a new data as buffer is full
            uart_reset();
            buffer_overflow=1;
        }
    }
  return data;
}
References buffer_overflow, relays, uart_put_char(), uart_reset(), uart_rx_buffer_add(), and rly_t::val.
Referenced by USART1_IRQHandler().
uart_receive_start()
void uart_receive_start (void)
initializes the uart to operate in the receive mode
initializes the uart to operate in the receive mode
initializes the uart to operate in the receive mode and resets the receive buffer
Returns
void
Definition at line 321 of file uart.c.
{
 // define the data direction of tx,rx pins
 /*  uart_CNTA_DIR.tx=1;   // set as output pin        //sbit(DDRD,PD1) DDRD |=(1<<PD1)
   uart_CNTA_DIR.rx=0;   // set as an input pin      //sbit(DDRD,PD0) DDRD &=~(1<<PD1)
   uart_CNTA_PORT.tx=1;  // set to High State        //sbit(PORT,PD1) PORTD|=(1<<PD1)
   uart_CNTA_PORT.rx=1;  // Enable Weak up resistor  //sbit(PORT,PD0) PORTD|=(1<<PD1)
   //UCSR0A=0x00;
   uart_status_reg.val=0;
  //UCSR0B=(1<<RXEN0)|(1<<RXCIE0);
   uart_control_reg.val=0;
   uart_control_reg.rx_enable=1;
   uart_control_reg.receive_complete_ie=1;
   */
   //reset the uart buffer
    uart_reset();
}
References uart_reset().
uart_reset()
void uart_reset (void)
resets the received buffer
resets the received buffer by setting each member a zero value
Returns
void
Definition at line 238 of file uart.c.
{
    rx_buffer_length=0;
    for(uint8_t i=0;i<UART_BUFFER_SIZE;i++)
      rx_buffer[i]=0;
}
References rx_buffer, rx_buffer_length, and UART_BUFFER_SIZE.
Referenced by uart_init(), uart_receive(), uart_receive_start(), uart_receive_stop(), and uart_task().
uart_rst_cmd_handle()
void uart_rst_cmd_handle ()
reset command: reset raspnet tx/rx buffers
uart_rx_cmd_handle()
void uart_rx_cmd_handle (uint8_t * data, size_t data_len)
uart_rx_queue_cmd_handle()
void uart_rx_queue_cmd_handle ()
uart_send_buffer()
void uart_send_buffer (USART_TypeDef * usartx, uint8_t * buf, uint16_t buf_size)
sends an array of bytes on the uart
it is an extension to uart_send_byte, hence it sends an array of data bytes on the uart
Parameters
buf a pointer to array of bytes
buf_size the length of data array/buffer
Definition at line 397 of file uart.c.
{
    // send payload
    uart_reg_write_buffer(usartx,buf,buf_size);
}
References uart_reg_write_buffer().
Referenced by uart_print(), uart_println(), and uart_send_message().
uart_send_byte()
uint8_t uart_send_byte (USART_TypeDef * usartx, uint8_t byte)
sends one byte on the uart
it first change the uart mode to work in the transmist mode then sends the byte by first configure the TX IO pin , then write to the uart data register. finally returns the module to the receive mode to avoid losing any received data on the RX Input pin
Parameters
byte
Returns
uint8_t
Definition at line 381 of file uart.c.
{
    // send payload
    uart_reg_write_byte(usartx,byte);
    return 1;
}
References uart_reg_write_byte().
Referenced by uart_println().
uart_send_message()
void uart_send_message (USART_TypeDef * usartx, uint8_t * buff, uint16_t length)
sends a message on the uart
it is an extension to uart_send_buffer, hence, it may builds a header or a delimiter to the information data portion
on the uart
Parameters
buf a pointer to data array of bytes
buf_size the length of data array/buffer
Definition at line 415 of file uart.c.
{
// Send header - a start of the message :
 // send payload
 uart_send_buffer(usartx,buff,length);
 // Send delimiter- a end of the message :
}
References uart_send_buffer().
uart_spd_cmd_handle()
void uart_spd_cmd_handle (uint8_t * data, size_t data_len)
speed command: changes the speed delay time for the blinking led
uart_task()
void uart_task (void)
a generic task to handle uart task
this a uart task in which the system handle all send and receive data on this module it sleeps most of the time when a data is available it simply wakes up and handles the received message (i.e a message command) it may send a response on the uart, perfom some reactions like changing the speed delay or just pass the message to raspnet stack
Definition at line 63 of file system-task.c.
{
    char buf[16]="";
    switch(uart_state)
    {
        case UART_WAIT:
            //my_gnc.usb_ticks++;
            //if(uart_ticks> UART_WAIT_TIMEOUT)// || uart_data_is_available())
            if(uart_data_is_available())
                uart_state=UART_READ;
         break;
        case UART_READ:
             uart_print(USART1,"\nrx_buf-len:");
             utoa(rx_buffer_length,buf,10);
             uart_println(USART1,buf);
             uart_print(USART1,"rx_buf:");
             uart_println(USART1,(char*) rx_buffer);
             uart_handle_frame();
             uart_reset();
            uart_ticks=0;
            uart_state=UART_WAIT;
        break;
    }
}
References rx_buffer, rx_buffer_length, uart_data_is_available(), uart_handle_frame(), uart_print(), uart_println(), UART_READ, uart_reset(), uart_state, uart_ticks, and UART_WAIT.
uart_tx_cmd_handle()
void uart_tx_cmd_handle (uint8_t * data, size_t data_len)
uart_tx_queue_cmd_handle()
void uart_tx_queue_cmd_handle ()
USART1_init()
void USART1_init (void)
uart-common.c
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
To Configure any Pripheral Module you have to follow the following:
Enable the Clock of peripheral Module (RCC_APBXPeriphClockCmd or RCC_AHBPeriphClockCmd)
Configure the pins required by the Module (AFIO_OUT or INPUT, ANALOG ...) & remap incase of requirement
Configure the peripheral hardware interrupt @ level of NVIC link to IRQ and set priority
Configure the peripheral hardware
Configure the peripheral interrupt @ level of the peripheral or DMA
Enable the peripheral Module
Implement the the IRQ_handler a function
in stm32f1038ct6 USART2 is shared with ADC define in the following pins
Parameters
PA9 — TX1 /SCL1/T4C2
PA10 — RX1 /SDA1/T4C1
PA11 — CTS1 /USB-/CANRX
PA12 — RTS1 /USB+/CANTX
Definition at line 54 of file uart_com.c.
{
  //1. Enable the Clock of peripheral USART1/AFIO/GPIOA Modules using RCC_APB2PeriphClockCmd
    //RCC_APB2PeriphClockCmd(RCC_APB2Periph_USART1,ENABLE);
    //RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO|
    //                       RCC_APB2Periph_GPIOA,ENABLE);
   RCC->APB2ENR|=RCC_APB2ENR_AFIOEN|RCC_APB2ENR_IOPAEN|RCC_APB2ENR_USART1EN;
  /* 2. Configure the pins required by the Module (AFIO_OUT or INPUT, ANALOG...)
      & remap incase of requirement */
      gpio_pin_mode(uart_tx,GPIO_MODE_AF_PP_50MHZ);
      /*GPIO_InitTypeDef _gpio_init_struct;
      GPIO_StructInit((GPIO_InitTypeDef*)& _gpio_init_struct);
      // init TX1=PA9
      _gpio_init_struct.GPIO_Pin=GPIO_Pin_9;
      _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
      _gpio_init_struct.GPIO_Mode=GPIO_Mode_AF_PP;
      GPIO_Init(GPIOA,&_gpio_init_struct);
      */
    // PA9 as a AFIO_PP_50MHZ MODE2[1:0]=11,CNF2[1:0]=10
    // GPIOA->CRH& =~(GPIO_CRH_MODE9|GPIO_CRH_CNF9); // at register level
    // GPIOA->CRH|=GPIO_CRH_MODE9 | GPIO_CRH_CNF9_1;
      // init RX1=PA10
      gpio_pin_mode(uart_rx,GPIO_MODE_IN_FLOATING);
    /*
      _gpio_init_struct.GPIO_Pin=GPIO_Pin_10;
      _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
      _gpio_init_struct.GPIO_Mode=GPIO_Mode_IN_FLOATING;
      GPIO_Init(GPIOA,&_gpio_init_struct);
      //GPIOA->ODR|=GPIO_ODR_ODR10;
    */
    // PA10 as a floating input MODE10[1:0]=00,CNF10[1:0]=01
    // GPIOA->CRH & =~(GPIO_CRH_MODE10|GPIO_CRH_CNF10);
    // GPIOA->CRH | =  GPIO_CRH_CNF10_0;
  /* 3. Configure the peripheral hardware interrupt @ level of  NVIC  link to IRQ and set priority */
     NVIC_InitTypeDef NVIC_InitStruct;
     NVIC_InitStruct.NVIC_IRQChannel=USART1_IRQn;
     NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority=0;
     NVIC_InitStruct.NVIC_IRQChannelSubPriority=8;
     NVIC_InitStruct.NVIC_IRQChannelCmd=ENABLE;
     NVIC_Init((NVIC_InitTypeDef*) &NVIC_InitStruct);
  /* 4. Configure the peripheral hardware  of the USART3 */
    USART_InitTypeDef _usart_init_struct;
    USART_StructInit((USART_InitTypeDef *)& _usart_init_struct);
    _usart_init_struct.USART_BaudRate=115200;
    _usart_init_struct.USART_Mode=USART_Mode_Rx | USART_Mode_Tx ;
    _usart_init_struct.USART_Parity=USART_Parity_No;
    _usart_init_struct.USART_StopBits=USART_StopBits_1;
    _usart_init_struct.USART_WordLength=USART_WordLength_8b;
    _usart_init_struct.USART_HardwareFlowControl=USART_HardwareFlowControl_None;
    USART_Init((USART_TypeDef*)USART1,(USART_InitTypeDef *)& _usart_init_struct);
/* 5. Configure the peripheral interrupt @ level of the peripheral or DMA */
  USART_ITConfig(USART1,USART_IT_RXNE,ENABLE);
/* 6. Enable the peripheral Module */
  USART_Cmd(USART1,ENABLE);
}
References GPIO_MODE_AF_PP_50MHZ, GPIO_MODE_IN_FLOATING, gpio_pin_mode(), uart_rx, and uart_tx.
Referenced by uart_init().
USART2_init()
void USART2_init (void)
in stm32f1038ct6 USART2 is shared with ADC define in the following pins
Parameters
PA3 — RX2 /ADC3
PA2 — TX2 /ADC2
PA1 — RTS2 /ADC1
PA0 — CTS2 /ADC0
Definition at line 120 of file uart_com.c.
{
  // 1. Enable the Clock of peripheral USART2 Module using RCC_APB1PeriphClockCmd
    RCC->APB1ENR |=RCC_APB1Periph_USART2;  //RCC_APB1PeriphClockCmd(RCC_APB1Periph_USART2,ENABLE);
    RCC->APB2ENR |=RCC_APB2Periph_AFIO | RCC_APB2Periph_GPIOA;
  /* 2. Configure the pins required by the Module (AFIO_OUT or INPUT, ANALOG...)
      & remap incase of requirement */
      GPIO_InitTypeDef _gpio_init_struct;
      GPIO_StructInit((GPIO_InitTypeDef*)& _gpio_init_struct);
      // init TX2=PA2
      _gpio_init_struct.GPIO_Pin=GPIO_Pin_2;
      _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
      _gpio_init_struct.GPIO_Mode=GPIO_Mode_AF_PP;
      GPIO_Init(GPIOA,&_gpio_init_struct);
   // PA2 as a AFIO_PP_50MHZ MODE2[1:0]=11,CNF2[1:0]=10
    // GPIOA->CRL& =~(GPIO_CRL_MODE2|GPIO_CRL_CNF2); // at register level
    // GPIOA->CRL|=GPIO_CRL_MODE2 | GPIO_CRL_CNF2_1;
      // init RX2=PA3
      _gpio_init_struct.GPIO_Pin=GPIO_Pin_3;
      _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
      _gpio_init_struct.GPIO_Mode=GPIO_Mode_IN_FLOATING;
      GPIO_Init(GPIOA,&_gpio_init_struct);
  // PA3 as a floating input MODE3[1:0]=00,CNF3[1:0]=01
    // GPIOA->CRL& =~(GPIO_CRL_MODE3|GPIO_CRL_CNF3);
    // GPIOA->CRL| =  GPIO_CRL_CNF3_0;
  /* 3. Configure the peripheral hardware interrupt @ level of  NVIC  link to IRQ and set priority */
     NVIC_InitTypeDef NVIC_InitStruct;
     NVIC_InitStruct.NVIC_IRQChannel=USART2_IRQn;
     NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority=0;
     NVIC_InitStruct.NVIC_IRQChannelSubPriority=8;
     NVIC_InitStruct.NVIC_IRQChannelCmd=ENABLE;
     NVIC_Init((NVIC_InitTypeDef*) &NVIC_InitStruct);
/* 4. Configure the peripheral hardware  of the USART2 */
    USART_InitTypeDef _usart_init_struct;
    USART_StructInit((USART_InitTypeDef*)& _usart_init_struct);
    _usart_init_struct.USART_BaudRate=115200;
    _usart_init_struct.USART_Mode=USART_Mode_Rx | USART_Mode_Tx ;
    _usart_init_struct.USART_Parity=USART_Parity_No;
    _usart_init_struct.USART_StopBits=USART_StopBits_1;
    _usart_init_struct.USART_WordLength=USART_WordLength_8b;
    _usart_init_struct.USART_HardwareFlowControl=USART_HardwareFlowControl_None;
    USART_Init(USART2,&_usart_init_struct);
/* 5. Configure the peripheral interrupt @ level of the peripheral or DMA */
    USART_ITConfig(USART2,USART_IT_RXNE | USART_IT_TXE,ENABLE);
/* 6. Enable the peripheral Module */
    USART_Cmd(USART2,ENABLE);
}
USART3_init()
void USART3_init (void)
in stm32f1038ct6 USART3 is shared with I2c2 define in the following pins
Parameters
PB11 — RX3/SDA2
PB10 — TX3/SCL2
Definition at line 187 of file uart_com.c.
{
  //1. Enable the Clock of peripheral USART3 Module using RCC_APB1PeriphClockCmd
    RCC_APB1PeriphClockCmd(RCC_APB1Periph_USART3,ENABLE);
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO|
                           RCC_APB2Periph_GPIOB,ENABLE);
  /* 2. Configure the pins required by the Module (AFIO_OUT or INPUT, ANALOG...)
      & remap incase of requirement */
      GPIO_InitTypeDef _gpio_init_struct;
      GPIO_StructInit((GPIO_InitTypeDef*)& _gpio_init_struct);
      // init TX3=PB10
      _gpio_init_struct.GPIO_Pin=GPIO_Pin_10;
      _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
      _gpio_init_struct.GPIO_Mode=GPIO_Mode_AF_PP;
      GPIO_Init(GPIOB,&_gpio_init_struct);
      // init RX3=PB11
      _gpio_init_struct.GPIO_Pin=GPIO_Pin_11;
      _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
      _gpio_init_struct.GPIO_Mode=GPIO_Mode_IN_FLOATING;
      GPIO_Init(GPIOB,&_gpio_init_struct);
  /* 3. Configure the peripheral hardware interrupt @ level of  NVIC  link to IRQ and set priority */
     NVIC_InitTypeDef NVIC_InitStruct;
     NVIC_InitStruct.NVIC_IRQChannel=USART3_IRQn;
     NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority=0;
     NVIC_InitStruct.NVIC_IRQChannelSubPriority=8;
     NVIC_InitStruct.NVIC_IRQChannelCmd=ENABLE;
     NVIC_Init((NVIC_InitTypeDef*) &NVIC_InitStruct);
  /* 4. Configure the peripheral hardware  of the USART3 */
    USART_InitTypeDef _usart_init_struct;
    USART_StructInit((USART_InitTypeDef *)& _usart_init_struct);
    _usart_init_struct.USART_BaudRate=115200;
    _usart_init_struct.USART_Mode=USART_Mode_Rx | USART_Mode_Tx ;
    _usart_init_struct.USART_Parity=USART_Parity_No;
    _usart_init_struct.USART_StopBits=USART_StopBits_1;
    _usart_init_struct.USART_WordLength=USART_WordLength_8b;
    _usart_init_struct.USART_HardwareFlowControl=USART_HardwareFlowControl_None;
    USART_Init((USART_TypeDef*)USART3,(USART_InitTypeDef *)& _usart_init_struct);
/* 5. Configure the peripheral interrupt @ level of the peripheral or DMA */
    USART_ITConfig(USART3,USART_IT_RXNE|USART_IT_TXE,ENABLE);
/* 6. Enable the peripheral Module */
    USART_Cmd(USART3,ENABLE);
}
Variable Documentation
buffer_overflow
volatile uint8_t buffer_overflow extern
Definition at line 28 of file uart.c.
Referenced by uart_receive().
raspnet_rx_buffer
uint8_t raspnet_rx_buffer[RASPNET_MAX_RX_QUEUE_LEN] extern
a gloabl variale define the raspnet receive buffer (Ring Queue)
raspnet_rx_queue
queue_t raspnet_rx_queue extern
defines the Raspnet Frame structure
this define the Raspnet Frame structure
it consists of the folowing parts
Parameters
header a 6-byte length that defines the header part of the raspnet frame
data an array of bytes that defines the payload of raspnet frame a gloabl variale define the transmit frame buffer a gloabl variale define the receive frame buffer a gloabl variale define the raspnet receive Ring Queue
raspnet_tx_buffer
uint8_t raspnet_tx_buffer[RASPNET_MAX_TX_QUEUE_LEN] extern
a gloabl variale define the raspnet receive buffer (Ring Queue)
raspnet_tx_queue
queue_t raspnet_tx_queue extern
a gloabl variale define the raspnet transmit Ring Queue
rx_buffer
uint8_t rx_buffer[UART_BUFFER_SIZE] extern
Definition at line 26 of file uart.c.
Referenced by uart_reset(), uart_rx_buffer_add(), and uart_task().
rx_buffer_length
volatile uint8_t rx_buffer_length extern
Definition at line 27 of file uart.c.
Referenced by uart_data_is_available(), uart_reset(), uart_rx_buffer_add(), and uart_task().
rx_index
volatile uint16_t rx_index extern
Definition at line 25 of file uart.c.
uart_rx
gpio_t uart_rx extern
Definition at line 31 of file uart.c.
Referenced by USART1_init().
uart_state
volatile uint8_t uart_state extern
uart.c
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering) uart state variable it defines thes state in the FSM (Finite state machine)
Definition at line 22 of file uart.c.
Referenced by uart_task().
uart_ticks
volatile uint32_t uart_ticks extern
Definition at line 23 of file uart.c.
Referenced by uart_task().
uart_tx
gpio_t uart_tx extern
Definition at line 30 of file uart.c.
Referenced by USART1_init().