STM32F103_IMU6050App: uart/uart.c File Reference
uart.c File Reference
#include "init.h"
Functions
uint8_t uart_reg_read_byte (USART_TypeDef *usartx)
read a byte to the uart data register
void uart_reg_write_byte (USART_TypeDef *usartx, uint8_t val)
write a byte to the uart data register
void uart_reg_write_buffer (USART_TypeDef *usartx, uint8_t *buff, uint16_t length)
write an array of data to the uart transmit buffer
static uint8_t endswith_delimiter (volatile uint8_t *buffer, uint8_t Buffer_length, uint8_t *delimiter)
configures the uart module
void uart_reset (void)
resets the received buffer
uint8_t uart_rx_buffer_add (uint8_t val)
append the new received byte to the receive buffer
uint8_t startswith_header (uint8_t *buffer, uint8_t Buffer_length, uint8_t *header)
checks how the received message on the uart begins with
void uart_receive_start (void)
puts the uart in the receive mode
void uart_receive_stop (void)
stop the current receiving message
uint8_t uart_islistening ()
checks if the uart in the receive mode and listens
uint8_t uart_send_byte (USART_TypeDef *usartx, uint8_t byte)
sends one byte on the uart
void uart_send_buffer (USART_TypeDef *usartx, uint8_t *buf, uint16_t buf_size)
sends an array of bytes on the uart
void uart_send_message (USART_TypeDef *usartx, uint8_t *buff, uint16_t length)
sends a message on the uart
void uart_print (USART_TypeDef *usartx, char *str)
a generic print message on the uart
void uart_println (USART_TypeDef *usartx, char *str)
a generic println message on the uart
void uart_print_integer (USART_TypeDef *usartx, uint32_t dword, uint8_t base)
void uart_print_float (USART_TypeDef *usartx, float val, uint8_t digits)
void uart_print_Array (USART_TypeDef *usartx, uint8_t *data, uint8_t len)
a generic print message on the uart in hexadecimal format
void uart_println_Array (USART_TypeDef *usartx, uint8_t *data, uint8_t len)
a generic println message on the uart in hexadecimal format
void uart_init ()
initializes the uart module
uint8_t uart_receive (USART_TypeDef *usartx)
performs areceive operation of one byte on uart
uint8_t uart_data_is_available (void)
checks if data is available
Variables
volatile uint8_t uart_state =UART_WAIT
uart.c
volatile uint32_t uart_ticks =0
volatile uint16_t rx_index =0
uint8_t rx_buffer [UART_BUFFER_SIZE] ={0}
volatile uint8_t rx_buffer_length =0
volatile uint8_t buffer_overflow =0
gpio_t uart_tx ={GPIOA,9}
gpio_t uart_rx ={GPIOA,10}
static uint8_t uart_delimiter [UART_DELIMITER_SIZE] ={0x55,0xaa,0x55,0xaa}
Function Documentation
endswith_delimiter()
uint8_t endswith_delimiter (volatile uint8_t * buffer, uint8_t Buffer_length, uint8_t * delimiter) static
configures the uart module
checks how the received message on the uart ends with
initialize the receive mask interrupt uart reset
checks if the delimiter of received message on the uart has received and matches with predefined delimiter
Parameters
buffer array of bytes i.e. data message received on the
Buffer_length the length of the message array of bytes
delimiter a pointer to predefined delimiter for the command message
Returns
uint8_t
Return values
0 neither delimiter has received yet nor a correct delimiter received
1 a correct delimiter has received
Definition at line 299 of file uart.c.
{
    if(Buffer_length<UART_DELIMITER_SIZE)
     return 0;
    for(uint8_t i=1;i<=UART_DELIMITER_SIZE;i++)
     if(buffer[Buffer_length-i]!=delimiter[UART_DELIMITER_SIZE-i])
      return 0;
 return 1;
}
References UART_DELIMITER_SIZE.
startswith_header()
uint8_t startswith_header (uint8_t * buffer, uint8_t Buffer_length, uint8_t * header)
checks how the received message on the uart begins with
checks if the header of received message on the uart is greater than the minimum command legth then it compare the first part with a predefined header
Parameters
buffer array of bytes i.e. data message received on the
Buffer_length the length of the message array of bytes
header a pointer to predefined header for the command message
Returns
uint8_t
Definition at line 276 of file uart.c.
{
    if(Buffer_length<UART_HEADER_SIZE)
     return 0;
    for(uint8_t i=1;i<=UART_HEADER_SIZE;i++)
     if(buffer[i]!=header[i])
      return 0;
 return 1;
}
References UART_HEADER_SIZE.
uart_data_is_available()
uint8_t uart_data_is_available (void)
checks if data is available
checks if the data on the uart is available
it checks if a complete command message has received note that each command message should ends witha space and ; == " ;"
Returns
uint8_t
Definition at line 642 of file uart.c.
{
 char * delim=" ;";
 if(rx_buffer_length!=0)
 {
    const uint8_t * tmp=0;//(uint8_t *) memmem((uint8_t *)rx_buffer,rx_buffer_length,(uint8_t *)delim,sizeof(delim));
   if(tmp!=NULL)
     return 1;
 }
 return 0;
}
References rx_buffer_length.
Referenced by uart_task().
uart_init()
void uart_init (void)
initializes the uart module
initialiaze the usart module
initializes the uart module and configure the buad rate and the message format such as start bit, parity , stop bit and the charactersize , it also resets the receive buffer size of the uart
Returns
void
Definition at line 539 of file uart.c.
{
  USART1_init();
// pins initialization
//  uart_CNTA_DIR.tx=1;   // set as output pin
//  uart_CNTA_DIR.rx=0;   // set as an input pin
//  uart_CNTA_PORT.tx=1;  // set to High State
//  uart_CNTA_PORT.rx=1;  // Enable Weak up resistor
//to change uart configuration such buad rate,data frame length ,stop bits,  parity
// based on the static options provided at the top of this file
 //    uart_configure();
 // Reset USART buffer
    uart_reset();
 }
References uart_reset(), and USART1_init().
Referenced by system_init().
uart_islistening()
uint8_t uart_islistening (void)
checks if the uart in the receive mode and listens
checks if the uart in the receive mode and the receive complete interrupt mask bit has been activated
Returns
uint8_t
Definition at line 363 of file uart.c.
{
 //if(bit_is_set(UCSR0B,RXEN0) && bit_is_set(UCSR0B,RXCIE0))
// if (uart_control_reg.rx_enable && uart_control_reg.receive_complete_ie)
//   return 1;
 return 0;
}
uart_print()
void uart_print (USART_TypeDef * usartx, char * str)
a generic print message on the uart
similar to uart_send_buffer, except it handles characters as an ASCII data
Parameters
str a pointer to character string
Definition at line 433 of file uart.c.
{
    uart_send_buffer(usartx ,(uint8_t*)str,strlen(str));
}
References uart_send_buffer().
Referenced by i2c_uart_print(), mpu6050_init(), mpu6050_set_hpf(), mpu6050_set_lpf(), mpu6050_task(), mpu6050_uart_print_Accelometer(), mpu6050_uart_print_Gyroscope(), mpu6050_uart_print_raw_Accelometer(), mpu6050_uart_print_raw_Array(), mpu6050_uart_print_raw_Gyroscope(), mpu6050_uart_print_raw_Temperature(), mpu6050_uart_print_Temperature(), uart_print_Array(), uart_print_float(), uart_print_integer(), uart_println_Array(), and uart_task().
uart_print_Array()
void uart_print_Array (USART_TypeDef * usartx, uint8_t * data, uint8_t len)
a generic print message on the uart in hexadecimal format
a generic print message as hexadecimal format on the uart
similar to uart_send_buffer, except it converrs ASCII data to hexadecimal format
Parameters
data a pointer to start of message buffer
len the length of the buffer message
Definition at line 495 of file uart.c.
{
    char buf[16]="";
    uint8_t val=0;
   for(uint8_t i=0;i<len;i++)
   {
      val=data[i];
       uart_print(usartx ," 0x");
       itoa(val,buf,16);
       uart_print(usartx ,buf);
       if (i%5==0)
        uart_println(usartx," ");
  }
}
References uart_print(), and uart_println().
uart_print_float()
void uart_print_float (USART_TypeDef * usartx, float val, uint8_t digits)
Definition at line 473 of file uart.c.
{
char buf[16]="";
    real_t r;
    r=float_to_real(val,digits);
    if(r.sig==1)
    uart_print(usartx,"-");
    itoa(r.integer,buf,10);
    uart_print(usartx,buf);
        uart_print(usartx,".");
    itoa(r.decimal,buf,10);
    uart_print(usartx,buf);
}
References real_t::decimal, float_to_real(), real_t::integer, real_t::sig, and uart_print().
Referenced by mpu6050_uart_print_Temperature().
uart_print_integer()
void uart_print_integer (USART_TypeDef * usartx, uint32_t dword, uint8_t base)
Parameters
usartx
dword
Definition at line 459 of file uart.c.
{
    char buf[16]="";
    switch(base)
    {
      case 16:  uart_print(usartx,"0x"); break;
      case 2:   uart_print(usartx,"0b"); break;
      default:  uart_print(usartx," ");  break;
    }
    itoa(dword,buf,base);
    uart_print(usartx,buf);
}
References uart_print().
Referenced by i2c_uart_print(), mpu6050_init(), mpu6050_set_hpf(), mpu6050_set_lpf(), mpu6050_task(), mpu6050_uart_print_Accelometer(), mpu6050_uart_print_Gyroscope(), mpu6050_uart_print_raw_Accelometer(), mpu6050_uart_print_raw_Array(), mpu6050_uart_print_raw_Gyroscope(), and mpu6050_uart_print_raw_Temperature().
uart_println()
void uart_println (USART_TypeDef * usartx, char * str)
a generic println message on the uart
similar to uart_send_buffer, except it handles characters as an ASCII data with \newline \r
Parameters
str a pointer to character string
Definition at line 446 of file uart.c.
{
    uart_send_buffer(usartx ,(uint8_t*)str,strlen(str));
    uart_send_byte(usartx,'\r');
    uart_send_byte(usartx,'\n');
}
References uart_send_buffer(), and uart_send_byte().
Referenced by uart_print_Array(), uart_println_Array(), and uart_task().
uart_println_Array()
void uart_println_Array (USART_TypeDef * usartx, uint8_t * data, uint8_t len)
a generic println message on the uart in hexadecimal format
a generic println message as hexadecimal format on the uart
similar to uart_send_buffer, except it converrs ASCII data to hexadecimal format
Parameters
data a pointer to start of message buffer
len the length of the buffer message
Definition at line 518 of file uart.c.
{
    char buf[16]="";
    uint8_t val=0;
   for(uint8_t i=0;i<len;i++)
   {
      val=data[i];
       uart_print(usartx,"0x");
       itoa(val,buf,16);
       uart_println(usartx,buf);
  }
}
References uart_print(), and uart_println().
uart_receive()
uint8_t uart_receive (USART_TypeDef * usartx)
performs areceive operation of one byte on uart
receives one byte on uart at the trigger of the receive complete interrupt and appends this received byte to the receive buffer this method is called in the uart receive complete interrupt service routine
Returns
the received byte on the uart rx module
uint8_t
USART_FLAG_ORE: OverRun Error flag
USART_FLAG_NE: Noise Error flag
USART_FLAG_FE: Framing Error flag
USART_FLAG_PE: Parity Error flag
PE (Parity error) , FE (Framing error), NE (Noise error),
ORE (OverRun error) and IDLE (Idle line detected) flags are cleared by software sequence:
a read operation to USART_SR register (USART_GetFlagStatus())
followed by a read operation to USART_DR register (USART_ReceiveData()).
RXNE flag can be also cleared by a read to the USART_DR register (USART_ReceiveData()).
Definition at line 569 of file uart.c.
{
  //uint8_t data=0;
  //uart_status_t status;
 // read data byte received from the rx buffer as soon as possible
   //data= uart_data_reg.val;
  // get the status of the uart
   //status.val=uart_status_reg.val;
   //uart_status_reg.val=0;
  // check no error in the received byte
   //if(!status.data_over_run &&
//     !status.frame_error   &&
//     !status.parity_error)
    // clear the Interrupt
     //USART_ClearITPendingBit(USART1,USART_IT_RXNE);
      volatile uint8_t data=0;
      volatile uint16_t status=0;
      status=usartx->SR;
      // read the received data from the usart receive buffer
      data=usartx->DR & 0x00ff;    // onlu 8_bit
     // reset the receive interrupt flag by software optional, reading data  reset IT_RXNE by hardware
     //RXNE flag can be also cleared by a read to the USART_DR register (USART_ReceiveData()).
     //USART_GetFlagStatus(USART1,USART_IT_TXE);
     //USART_ClearITPendingBit(USART1,USART_IT_RXNE);
     // push it to the receive queue
    uart_put_char(USART1,data);
    if(data==';')
        relays.val=0;
    if(USART_GetFlagStatus(USART1,USART_FLAG_PE | USART_FLAG_FE |
                           USART_FLAG_NE | USART_FLAG_ORE)==RESET)
    {
       //
      // here try to append the data to the received buffer
        if(!uart_rx_buffer_add(data))
        {
          // it is failed to add a new data as buffer is full
            uart_reset();
            buffer_overflow=1;
        }
    }
  return data;
}
References buffer_overflow, relays, uart_put_char(), uart_reset(), uart_rx_buffer_add(), and rly_t::val.
Referenced by USART1_IRQHandler().
uart_receive_start()
void uart_receive_start (void)
puts the uart in the receive mode
initializes the uart to operate in the receive mode
initializes the uart to operate in the receive mode and resets the receive buffer
Returns
void
Definition at line 321 of file uart.c.
{
 // define the data direction of tx,rx pins
 /*  uart_CNTA_DIR.tx=1;   // set as output pin        //sbit(DDRD,PD1) DDRD |=(1<<PD1)
   uart_CNTA_DIR.rx=0;   // set as an input pin      //sbit(DDRD,PD0) DDRD &=~(1<<PD1)
   uart_CNTA_PORT.tx=1;  // set to High State        //sbit(PORT,PD1) PORTD|=(1<<PD1)
   uart_CNTA_PORT.rx=1;  // Enable Weak up resistor  //sbit(PORT,PD0) PORTD|=(1<<PD1)
   //UCSR0A=0x00;
   uart_status_reg.val=0;
  //UCSR0B=(1<<RXEN0)|(1<<RXCIE0);
   uart_control_reg.val=0;
   uart_control_reg.rx_enable=1;
   uart_control_reg.receive_complete_ie=1;
   */
   //reset the uart buffer
    uart_reset();
}
References uart_reset().
uart_receive_stop()
void uart_receive_stop (void)
stop the current receiving message
stop the current receive operation and resets the the receive module of the uart
Definition at line 346 of file uart.c.
{
// Stop listening.
  //uart_status_reg.val=0;  //UCSR0A=0x00;
  //uart_control_reg.val=0; //UCSR0B=0x00;
   //reset the uart buffer
   uart_reset();
}
References uart_reset().
uart_reg_read_byte()
uint8_t uart_reg_read_byte (USART_TypeDef * usartx)
read a byte to the uart data register
configures the uart module
configures the uart module using the options defined by static uart_options variable
Returns
void
initializes the receive mask interrupt
sets or resets the receive complete interrupt mask bit based on the passed value
Parameters
enable sets/resets the receive complete interrupt mask bit
Returns
void
read a byte to the uart data register
reseved for future use
Returns
uint8_t
Definition at line 188 of file uart.c.
{
   while(USART_GetFlagStatus(usartx,USART_FLAG_RXNE)==RESET);
     return usartx->DR & (uint16_t) 0x00ff;
}
uart_reg_write_buffer()
void uart_reg_write_buffer (USART_TypeDef * usartx, uint8_t * buff, uint16_t size)
write an array of data to the uart transmit buffer
writes this array of bytes to the uart data rgister in sequnce to be transmisted on the TX output pin
Parameters
buff a pointer to the data array
size the length of this data array buffer
Returns
void
Definition at line 225 of file uart.c.
{
    uint16_t i=0;
    for(i=0;i<size;i++)
     uart_reg_write_byte((USART_TypeDef *) usartx ,buff[i]);
}
References uart_reg_write_byte().
Referenced by uart_send_buffer().
uart_reg_write_byte()
void uart_reg_write_byte (USART_TypeDef * usartx, uint8_t val)
write a byte to the uart data register
writes a byte to the uart data register
writes a byte to the uart data register which be later sent on the uart TX output pin
Parameters
val the passed value to be sent on the uart TX line
Definition at line 203 of file uart.c.
{
 /*
  uint32_t i=0;
   while(!uart_status_reg.data_register_empty);
    uart_data_reg.val=val;
*/
while(USART_GetFlagStatus(usartx,USART_FLAG_TXE)==RESET);
  usartx->DR=(val & (uint16_t) 0x00ff);
 }
Referenced by uart_reg_write_buffer(), and uart_send_byte().
uart_reset()
void uart_reset (void)
resets the received buffer
resets the received buffer by setting each member a zero value
Returns
void
Definition at line 238 of file uart.c.
{
    rx_buffer_length=0;
    for(uint8_t i=0;i<UART_BUFFER_SIZE;i++)
      rx_buffer[i]=0;
}
References rx_buffer, rx_buffer_length, and UART_BUFFER_SIZE.
Referenced by uart_init(), uart_receive(), uart_receive_start(), uart_receive_stop(), and uart_task().
uart_rx_buffer_add()
uint8_t uart_rx_buffer_add (uint8_t val)
append the new received byte to the receive buffer
Parameters
val the byte value intended to be appended to the end of the received buffer
Returns
uint8_t
Return values
0 failed to add this byte no enough space
1 succeeded to add this byte to the end of the buffer
Definition at line 253 of file uart.c.
{
if(rx_buffer_length<=UART_BUFFER_SIZE)
 {
  rx_buffer_length++;
  rx_buffer[rx_buffer_length-1]=val;
  return 1;
 }
 return 0;
}
References rx_buffer, rx_buffer_length, and UART_BUFFER_SIZE.
Referenced by uart_receive().
uart_send_buffer()
void uart_send_buffer (USART_TypeDef * usartx, uint8_t * buf, uint16_t buf_size)
sends an array of bytes on the uart
it is an extension to uart_send_byte, hence it sends an array of data bytes on the uart
Parameters
buf a pointer to array of bytes
buf_size the length of data array/buffer
Definition at line 397 of file uart.c.
{
    // send payload
    uart_reg_write_buffer(usartx,buf,buf_size);
}
References uart_reg_write_buffer().
Referenced by uart_print(), uart_println(), and uart_send_message().
uart_send_byte()
uint8_t uart_send_byte (USART_TypeDef * usartx, uint8_t byte)
sends one byte on the uart
it first change the uart mode to work in the transmist mode then sends the byte by first configure the TX IO pin , then write to the uart data register. finally returns the module to the receive mode to avoid losing any received data on the RX Input pin
Parameters
byte
Returns
uint8_t
Definition at line 381 of file uart.c.
{
    // send payload
    uart_reg_write_byte(usartx,byte);
    return 1;
}
References uart_reg_write_byte().
Referenced by uart_println().
uart_send_message()
void uart_send_message (USART_TypeDef * usartx, uint8_t * buff, uint16_t length)
sends a message on the uart
it is an extension to uart_send_buffer, hence, it may builds a header or a delimiter to the information data portion
on the uart
Parameters
buf a pointer to data array of bytes
buf_size the length of data array/buffer
Definition at line 415 of file uart.c.
{
// Send header - a start of the message :
 // send payload
 uart_send_buffer(usartx,buff,length);
 // Send delimiter- a end of the message :
}
References uart_send_buffer().
Variable Documentation
buffer_overflow
volatile uint8_t buffer_overflow =0
Definition at line 28 of file uart.c.
Referenced by uart_receive().
rx_buffer
uint8_t rx_buffer[UART_BUFFER_SIZE] ={0}
Definition at line 26 of file uart.c.
Referenced by uart_reset(), uart_rx_buffer_add(), and uart_task().
rx_buffer_length
volatile uint8_t rx_buffer_length =0
Definition at line 27 of file uart.c.
Referenced by uart_data_is_available(), uart_reset(), uart_rx_buffer_add(), and uart_task().
rx_index
volatile uint16_t rx_index =0
Definition at line 25 of file uart.c.
uart_delimiter
uint8_t uart_delimiter[UART_DELIMITER_SIZE] ={0x55,0xaa,0x55,0xaa} static
Definition at line 37 of file uart.c.
uart_rx
gpio_t uart_rx ={GPIOA,10}
Definition at line 31 of file uart.c.
Referenced by USART1_init().
uart_state
volatile uint8_t uart_state =UART_WAIT
uart.c
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering) uart state variable it defines thes state in the FSM (Finite state machine)
Definition at line 22 of file uart.c.
Referenced by uart_task().
uart_ticks
volatile uint32_t uart_ticks =0
Definition at line 23 of file uart.c.
Referenced by uart_task().
uart_tx
gpio_t uart_tx ={GPIOA,9}
Definition at line 30 of file uart.c.
Referenced by USART1_init().