STM32F103_IMU6050App: uart/uart_com.c File Reference
uart_com.c File Reference
#include "init.h"
Functions
void USART1_init (void)
uart-common.c
void USART2_init (void)
void USART3_init (void)
void USART1_IRQHandler (void)
USART1_IRQHandler Interrupt request for USART3 peripheral.
void USART2_IRQHandler (void)
USART2_IRQHandler Interrupt request for USART3 peripheral.
void USART3_IRQHandler (void)
USART3_IRQHandler Interrupt request for USART3 peripheral.
uint8_t uart_put_char (USART_TypeDef *usartx, uint8_t data)
uint8_t uart_get_char (USART_TypeDef *usartx)
Function Documentation
uart_get_char()
uint8_t uart_get_char (USART_TypeDef * usartx)
Definition at line 383 of file uart_com.c.
{
  while(USART_GetFlagStatus(usartx,USART_FLAG_RXNE)==RESET);
  return usartx->DR & (uint16_t) 0x00ff;
}
uart_put_char()
uint8_t uart_put_char (USART_TypeDef * usartx, uint8_t data)
Definition at line 375 of file uart_com.c.
{
  while(USART_GetFlagStatus(usartx,USART_FLAG_TXE)==RESET);
  usartx->DR=(data & (uint16_t) 0x00ff);
  return 0;
}
Referenced by uart_receive().
USART1_init()
void USART1_init (void)
uart-common.c
Parameters
student Sameer Almaldein
ID 679699
University TU-Chemnitz
Master : ASE(Automotive Software Engineering)
To Configure any Pripheral Module you have to follow the following:
Enable the Clock of peripheral Module (RCC_APBXPeriphClockCmd or RCC_AHBPeriphClockCmd)
Configure the pins required by the Module (AFIO_OUT or INPUT, ANALOG ...) & remap incase of requirement
Configure the peripheral hardware interrupt @ level of NVIC link to IRQ and set priority
Configure the peripheral hardware
Configure the peripheral interrupt @ level of the peripheral or DMA
Enable the peripheral Module
Implement the the IRQ_handler a function
in stm32f1038ct6 USART2 is shared with ADC define in the following pins
Parameters
PA9 — TX1 /SCL1/T4C2
PA10 — RX1 /SDA1/T4C1
PA11 — CTS1 /USB-/CANRX
PA12 — RTS1 /USB+/CANTX
Definition at line 54 of file uart_com.c.
{
  //1. Enable the Clock of peripheral USART1/AFIO/GPIOA Modules using RCC_APB2PeriphClockCmd
    //RCC_APB2PeriphClockCmd(RCC_APB2Periph_USART1,ENABLE);
    //RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO|
    //                       RCC_APB2Periph_GPIOA,ENABLE);
   RCC->APB2ENR|=RCC_APB2ENR_AFIOEN|RCC_APB2ENR_IOPAEN|RCC_APB2ENR_USART1EN;
  /* 2. Configure the pins required by the Module (AFIO_OUT or INPUT, ANALOG...)
      & remap incase of requirement */
      gpio_pin_mode(uart_tx,GPIO_MODE_AF_PP_50MHZ);
      /*GPIO_InitTypeDef _gpio_init_struct;
      GPIO_StructInit((GPIO_InitTypeDef*)& _gpio_init_struct);
      // init TX1=PA9
      _gpio_init_struct.GPIO_Pin=GPIO_Pin_9;
      _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
      _gpio_init_struct.GPIO_Mode=GPIO_Mode_AF_PP;
      GPIO_Init(GPIOA,&_gpio_init_struct);
      */
    // PA9 as a AFIO_PP_50MHZ MODE2[1:0]=11,CNF2[1:0]=10
    // GPIOA->CRH& =~(GPIO_CRH_MODE9|GPIO_CRH_CNF9); // at register level
    // GPIOA->CRH|=GPIO_CRH_MODE9 | GPIO_CRH_CNF9_1;
      // init RX1=PA10
      gpio_pin_mode(uart_rx,GPIO_MODE_IN_FLOATING);
    /*
      _gpio_init_struct.GPIO_Pin=GPIO_Pin_10;
      _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
      _gpio_init_struct.GPIO_Mode=GPIO_Mode_IN_FLOATING;
      GPIO_Init(GPIOA,&_gpio_init_struct);
      //GPIOA->ODR|=GPIO_ODR_ODR10;
    */
    // PA10 as a floating input MODE10[1:0]=00,CNF10[1:0]=01
    // GPIOA->CRH & =~(GPIO_CRH_MODE10|GPIO_CRH_CNF10);
    // GPIOA->CRH | =  GPIO_CRH_CNF10_0;
  /* 3. Configure the peripheral hardware interrupt @ level of  NVIC  link to IRQ and set priority */
     NVIC_InitTypeDef NVIC_InitStruct;
     NVIC_InitStruct.NVIC_IRQChannel=USART1_IRQn;
     NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority=0;
     NVIC_InitStruct.NVIC_IRQChannelSubPriority=8;
     NVIC_InitStruct.NVIC_IRQChannelCmd=ENABLE;
     NVIC_Init((NVIC_InitTypeDef*) &NVIC_InitStruct);
  /* 4. Configure the peripheral hardware  of the USART3 */
    USART_InitTypeDef _usart_init_struct;
    USART_StructInit((USART_InitTypeDef *)& _usart_init_struct);
    _usart_init_struct.USART_BaudRate=115200;
    _usart_init_struct.USART_Mode=USART_Mode_Rx | USART_Mode_Tx ;
    _usart_init_struct.USART_Parity=USART_Parity_No;
    _usart_init_struct.USART_StopBits=USART_StopBits_1;
    _usart_init_struct.USART_WordLength=USART_WordLength_8b;
    _usart_init_struct.USART_HardwareFlowControl=USART_HardwareFlowControl_None;
    USART_Init((USART_TypeDef*)USART1,(USART_InitTypeDef *)& _usart_init_struct);
/* 5. Configure the peripheral interrupt @ level of the peripheral or DMA */
  USART_ITConfig(USART1,USART_IT_RXNE,ENABLE);
/* 6. Enable the peripheral Module */
  USART_Cmd(USART1,ENABLE);
}
References GPIO_MODE_AF_PP_50MHZ, GPIO_MODE_IN_FLOATING, gpio_pin_mode(), uart_rx, and uart_tx.
Referenced by uart_init().
USART1_IRQHandler()
void USART1_IRQHandler (void)
USART1_IRQHandler Interrupt request for USART3 peripheral.
it checks: a. the receive data interrupt b. the transmit data complete interrupt
it pushs in the received data to the received Queue to be later handled
it pop up the data from the transmit Queue to be send through USART transmit buffer
Parameters
void
Returns
void
Definition at line 260 of file uart_com.c.
{
    // clear the Interrupt
     //USART_ClearITPendingBit(USART1,USART_IT_RXNE);
     volatile uint8_t data=0;
     volatile uint16_t t=0;
    if(USART_GetITStatus(USART1,USART_IT_RXNE)!=RESET)
      uart_receive(USART1);
    //  TX : check if data is sent
    /*if(USART_GetITStatus(USART1,USART_IT_TXE)!=RESET)
    {
      // pop data  from the transmit queue to send
      // reset the transmit interrupt flag by software optional,
        //USART_ClearITPendingBit(USART1,USART_IT_TXE);
       //data=0x37;//relays.val;
      // send data to USART1 transmit buffer
        USART_SendData(USART1,data);
    }
    */
}
References uart_receive().
USART2_init()
void USART2_init (void)
in stm32f1038ct6 USART2 is shared with ADC define in the following pins
Parameters
PA3 — RX2 /ADC3
PA2 — TX2 /ADC2
PA1 — RTS2 /ADC1
PA0 — CTS2 /ADC0
Definition at line 120 of file uart_com.c.
{
  // 1. Enable the Clock of peripheral USART2 Module using RCC_APB1PeriphClockCmd
    RCC->APB1ENR |=RCC_APB1Periph_USART2;  //RCC_APB1PeriphClockCmd(RCC_APB1Periph_USART2,ENABLE);
    RCC->APB2ENR |=RCC_APB2Periph_AFIO | RCC_APB2Periph_GPIOA;
  /* 2. Configure the pins required by the Module (AFIO_OUT or INPUT, ANALOG...)
      & remap incase of requirement */
      GPIO_InitTypeDef _gpio_init_struct;
      GPIO_StructInit((GPIO_InitTypeDef*)& _gpio_init_struct);
      // init TX2=PA2
      _gpio_init_struct.GPIO_Pin=GPIO_Pin_2;
      _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
      _gpio_init_struct.GPIO_Mode=GPIO_Mode_AF_PP;
      GPIO_Init(GPIOA,&_gpio_init_struct);
   // PA2 as a AFIO_PP_50MHZ MODE2[1:0]=11,CNF2[1:0]=10
    // GPIOA->CRL& =~(GPIO_CRL_MODE2|GPIO_CRL_CNF2); // at register level
    // GPIOA->CRL|=GPIO_CRL_MODE2 | GPIO_CRL_CNF2_1;
      // init RX2=PA3
      _gpio_init_struct.GPIO_Pin=GPIO_Pin_3;
      _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
      _gpio_init_struct.GPIO_Mode=GPIO_Mode_IN_FLOATING;
      GPIO_Init(GPIOA,&_gpio_init_struct);
  // PA3 as a floating input MODE3[1:0]=00,CNF3[1:0]=01
    // GPIOA->CRL& =~(GPIO_CRL_MODE3|GPIO_CRL_CNF3);
    // GPIOA->CRL| =  GPIO_CRL_CNF3_0;
  /* 3. Configure the peripheral hardware interrupt @ level of  NVIC  link to IRQ and set priority */
     NVIC_InitTypeDef NVIC_InitStruct;
     NVIC_InitStruct.NVIC_IRQChannel=USART2_IRQn;
     NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority=0;
     NVIC_InitStruct.NVIC_IRQChannelSubPriority=8;
     NVIC_InitStruct.NVIC_IRQChannelCmd=ENABLE;
     NVIC_Init((NVIC_InitTypeDef*) &NVIC_InitStruct);
/* 4. Configure the peripheral hardware  of the USART2 */
    USART_InitTypeDef _usart_init_struct;
    USART_StructInit((USART_InitTypeDef*)& _usart_init_struct);
    _usart_init_struct.USART_BaudRate=115200;
    _usart_init_struct.USART_Mode=USART_Mode_Rx | USART_Mode_Tx ;
    _usart_init_struct.USART_Parity=USART_Parity_No;
    _usart_init_struct.USART_StopBits=USART_StopBits_1;
    _usart_init_struct.USART_WordLength=USART_WordLength_8b;
    _usart_init_struct.USART_HardwareFlowControl=USART_HardwareFlowControl_None;
    USART_Init(USART2,&_usart_init_struct);
/* 5. Configure the peripheral interrupt @ level of the peripheral or DMA */
    USART_ITConfig(USART2,USART_IT_RXNE | USART_IT_TXE,ENABLE);
/* 6. Enable the peripheral Module */
    USART_Cmd(USART2,ENABLE);
}
USART2_IRQHandler()
void USART2_IRQHandler (void)
USART2_IRQHandler Interrupt request for USART3 peripheral.
it checks: a. the receive data interrupt b. the transmit data complete interrupt
it pushs in the received data to the received Queue to be later handled
it pop up the data from the transmit Queue to be send through USART transmit buffer
Parameters
void
Returns
void
Definition at line 296 of file uart_com.c.
{
    // clear the Interrupt
     //USART_ClearITPendingBit(USART1,USART_IT_RXNE);
   /*
    // RX: check if a data is received
    if(USART_GetITStatus(USART2,USART_IT_RXNE)!=RESET)
    {
        uint8_t data=0;
        // read the received data from the usart receive buffer
        data=USART_ReceiveData(USART2) & 0x00ff;    // onlu 8_bit
        // reset the receive interrupt flag by software optional, reading data  reset IT_RXNE by hardware
        USART_ClearITPendingBit(USART2,USART_IT_RXNE);
        // push it to the receive queue
          USART_SendData(USART2,data); // for test only
    }
    //  TX : check if data is sent
    if(USART_GetITStatus(USART2,USART_IT_TXE)!=RESET)
    {
      uint8_t data=0;
      // pop data  from the transmit queue to send
      // reset the transmit interrupt flag by software optional,
        USART_ClearITPendingBit(USART2,USART_IT_TXE);
      // send data to USART1 transmit buffer
      USART_SendData(USART2,data);
    }
   */
}
USART3_init()
void USART3_init (void)
in stm32f1038ct6 USART3 is shared with I2c2 define in the following pins
Parameters
PB11 — RX3/SDA2
PB10 — TX3/SCL2
Definition at line 187 of file uart_com.c.
{
  //1. Enable the Clock of peripheral USART3 Module using RCC_APB1PeriphClockCmd
    RCC_APB1PeriphClockCmd(RCC_APB1Periph_USART3,ENABLE);
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO|
                           RCC_APB2Periph_GPIOB,ENABLE);
  /* 2. Configure the pins required by the Module (AFIO_OUT or INPUT, ANALOG...)
      & remap incase of requirement */
      GPIO_InitTypeDef _gpio_init_struct;
      GPIO_StructInit((GPIO_InitTypeDef*)& _gpio_init_struct);
      // init TX3=PB10
      _gpio_init_struct.GPIO_Pin=GPIO_Pin_10;
      _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
      _gpio_init_struct.GPIO_Mode=GPIO_Mode_AF_PP;
      GPIO_Init(GPIOB,&_gpio_init_struct);
      // init RX3=PB11
      _gpio_init_struct.GPIO_Pin=GPIO_Pin_11;
      _gpio_init_struct.GPIO_Speed=GPIO_Speed_50MHz;
      _gpio_init_struct.GPIO_Mode=GPIO_Mode_IN_FLOATING;
      GPIO_Init(GPIOB,&_gpio_init_struct);
  /* 3. Configure the peripheral hardware interrupt @ level of  NVIC  link to IRQ and set priority */
     NVIC_InitTypeDef NVIC_InitStruct;
     NVIC_InitStruct.NVIC_IRQChannel=USART3_IRQn;
     NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority=0;
     NVIC_InitStruct.NVIC_IRQChannelSubPriority=8;
     NVIC_InitStruct.NVIC_IRQChannelCmd=ENABLE;
     NVIC_Init((NVIC_InitTypeDef*) &NVIC_InitStruct);
  /* 4. Configure the peripheral hardware  of the USART3 */
    USART_InitTypeDef _usart_init_struct;
    USART_StructInit((USART_InitTypeDef *)& _usart_init_struct);
    _usart_init_struct.USART_BaudRate=115200;
    _usart_init_struct.USART_Mode=USART_Mode_Rx | USART_Mode_Tx ;
    _usart_init_struct.USART_Parity=USART_Parity_No;
    _usart_init_struct.USART_StopBits=USART_StopBits_1;
    _usart_init_struct.USART_WordLength=USART_WordLength_8b;
    _usart_init_struct.USART_HardwareFlowControl=USART_HardwareFlowControl_None;
    USART_Init((USART_TypeDef*)USART3,(USART_InitTypeDef *)& _usart_init_struct);
/* 5. Configure the peripheral interrupt @ level of the peripheral or DMA */
    USART_ITConfig(USART3,USART_IT_RXNE|USART_IT_TXE,ENABLE);
/* 6. Enable the peripheral Module */
    USART_Cmd(USART3,ENABLE);
}
USART3_IRQHandler()
void USART3_IRQHandler (void)
USART3_IRQHandler Interrupt request for USART3 peripheral.
it checks: a. the receive data interrupt b. the transmit data complete interrupt
it pushs in the received data to the received Queue to be later handled
it pop up the data from the transmit Queue to be send through USART transmit buffer
Parameters
void
Returns
void
Definition at line 338 of file uart_com.c.
{
    // clear the Interrupt
     //USART_ClearITPendingBit(USART1,USART_IT_RXNE);
   /*
    // RX: check if a data is received
    if(USART_GetITStatus(USART3,USART_IT_RXNE)!=RESET)
    {
        uint8_t data=0;
        // read the received data from the usart receive buffer
        data=USART_ReceiveData(USART3) & 0x00ff;    // onlu 8_bit
        // reset the receive interrupt flag by software optional, reading data  reset IT_RXNE by hardware
        USART_ClearITPendingBit(USART3,USART_IT_RXNE);
        // push it to the receive queue
          USART_SendData(USART3,data); // for test only
    }
    //  TX : check if data is sent
    if(USART_GetITStatus(USART3,USART_IT_TXE)!=RESET)
    {
      uint8_t data=0;
      // pop data  from the transmit queue to send
      // reset the transmit interrupt flag by software optional,
        USART_ClearITPendingBit(USART3,USART_IT_TXE);
      // send data to USART1 transmit buffer
        USART_SendData(USART3,data);
    }
 */
}